'use client'
import {useEffect,useMemo,useState} from 'react'
import {CheckCircle2,RotateCcw,ShieldCheck,Save,Plus,Trash2} from 'lucide-react'
import SignatureEditor from '@/app/components/signature/SignatureEditor'

const stageLabels:any={employee:'الموظف',finance:'الإدارة المالية',hr:'الموارد البشرية',project_manager:'مدير المشاريع',general_manager:'المدير العام'}
const statusLabels:any={pending_employee:'بانتظار اعتماد الموظف',pending_finance:'بانتظار اعتماد المالية',pending_hr:'بانتظار اعتماد الموارد البشرية',pending_project_manager:'بانتظار اعتماد مدير المشاريع',pending_general_manager:'بانتظار اعتماد المدير العام',completed:'معتمدة نهائيًا',needs_revision:'تحتاج إلى تعديل',rejected:'مرفوضة'}

export default function FinancialClearancePublic({params}:{params:Promise<{token:string}>}){
 const [token,setToken]=useState(''),[data,setData]=useState<any>(null),[signature,setSignature]=useState(''),[notes,setNotes]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[items,setItems]=useState<any[]>([])
 useEffect(()=>{void params.then(p=>setToken(p.token))},[params])
 const load=async()=>{if(!token)return;setLoading(true);try{const r=await fetch('/api/financial-clearances/public/'+token,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d?.error||'الرابط غير صالح');setData(d.link);setItems(d.link?.clearance?.items||[])}catch(e:any){setMessage(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[token])
 const c=data?.clearance,e=c?.employee||{},stage=data?.stage||c?.current_stage
 const ent=items.filter((x:any)=>x.item_type==='entitlement'),obl=items.filter((x:any)=>x.item_type==='obligation')
 const entTotal=ent.reduce((s:number,x:any)=>s+Number(x.amount||0),0),oblTotal=obl.reduce((s:number,x:any)=>s+Number(x.amount||0),0),net=entTotal-oblTotal
 const addItem=(type:string)=>setItems(v=>[...v,{item_type:type,label:'',amount:0,notes:'',editable:true,code:'manual'}])
 const saveFinance=async()=>{setSaving(true);const r=await fetch('/api/financial-clearances/public/'+token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',items})});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)return setMessage(d?.error||'تعذر الحفظ');setMessage('تم حفظ بيان المستحقات والالتزامات.');await load()}
 const submit=async(action:string)=>{setSaving(true);const r=await fetch('/api/financial-clearances/public/'+token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,signature,notes,name:e.full_name,title:stageLabels[stage]})});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)return setMessage(d?.error||'تعذر تنفيذ الإجراء');setMessage(action==='approve'?(d.status==='completed'?'تم الاعتماد النهائي للمخالصة.':'تم الاعتماد والانتقال للمرحلة التالية.'):(action==='reject'?'تم رفض المخالصة.':'تم إرجاع المخالصة للتعديل.'));setSignature('');setNotes('');await load()}
 const canEditFinance=stage==='finance'&&c?.status==='pending_finance'
 const editableItems=items
 if(loading)return <main dir="rtl" className="min-h-screen bg-slate-50 p-10 text-center">جارٍ تحميل المخالصة...</main>
 if(!data||!c)return <main dir="rtl" className="min-h-screen bg-slate-50 p-10 text-center text-red-700">{message||'الرابط غير صالح'}</main>
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl">
  <header className="rounded-2xl bg-[#09233f] p-6 text-white"><div className="flex items-center gap-3"><ShieldCheck className="text-[#e2bd62]"/><div><div className="font-black">شركة البنية الأساسية للمقاولات</div><h1 className="mt-1 text-xl font-black">مخالصة مالية وإدارية نهائية وإبراء ذمة</h1><div className="mt-1 text-xs text-slate-300">{c.clearance_number} · {statusLabels[c.status]||c.status}</div></div></div><div className="mt-4 rounded-xl bg-white/10 p-3 text-sm font-black">المرحلة الحالية: {stageLabels[stage]||stage}</div></header>

  <section className="mt-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black text-[#09233f]">بيانات الموظف</h2><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">{[['الاسم',e.full_name],['الرقم الوظيفي',e.employee_number],['الهوية/الإقامة',e.national_id],['المسمى الوظيفي',e.job_title],['القسم',e.department],['الشركة',e.company?.name],['تاريخ المباشرة',e.hire_date],['آخر يوم عمل',c.source_snapshot?.clearance?.last_work_date]].map(([k,v])=><div key={String(k)} className="rounded-lg bg-slate-50 p-3"><div className="text-xs text-slate-500">{k}</div><div className="mt-1 font-black">{v||'—'}</div></div>)}</div></section>

  <section className="mt-4 rounded-2xl border bg-white p-5"><h2 className="font-black text-[#09233f]">البيانات الوظيفية والمالية</h2><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">{[['تاريخ المباشرة',c.financial_data?.contract_start_date],['آخر يوم عمل',c.financial_data?.last_work_date||c.source_snapshot?.clearance?.last_work_date],['الراتب الأساسي',c.financial_data?.basic_salary],['بدل السكن',c.financial_data?.housing_allowance],['بدل النقل',c.financial_data?.transportation_allowance],['بدلات أخرى',c.financial_data?.other_allowances],['رصيد الإجازات بالأيام',c.financial_data?.leave_balance_days],['الأجر اليومي',c.financial_data?.daily_wage]].map(([k,v])=><div key={String(k)} className="rounded-lg border p-3"><div className="text-xs text-slate-500">{k}</div><div className="mt-1 font-black">{v===null||v===undefined||v===''?'—':v}</div></div>)}</div></section>

  <section className="mt-4 rounded-2xl border bg-white p-5"><h2 className="font-black text-[#09233f]">بيان المستحقات</h2>{ent.map((x:any,i:number)=>canEditFinance&&x.editable!==false?<div key={x.id||i} className="mt-2 grid grid-cols-[1fr_130px_40px] gap-2 rounded-xl border p-2"><div><input value={x.label||''} onChange={e=>setItems(v=>v.map(it=>it===x?{...it,label:e.target.value}:it))} placeholder="نوع المستحق / البيان" className="w-full rounded-lg border p-2 font-bold"/><textarea value={x.notes||''} onChange={e=>setItems(v=>v.map(it=>it===x?{...it,notes:e.target.value}:it))} placeholder="ملاحظات" className="mt-1 w-full rounded-lg border p-2 text-xs"/></div><input type="number" min="0" step="0.01" value={x.amount??0} onChange={e=>setItems(v=>v.map(it=>it===x?{...it,amount:e.target.value}:it))} className="h-fit rounded-lg border p-2 text-left font-black"/><button onClick={()=>setItems(v=>v.filter(it=>it!==x))} className="h-fit rounded-lg border p-2 text-red-700"><Trash2 size={16}/></button></div>:<div key={x.id||i} className="mt-2 rounded-xl border p-3"><div className="flex justify-between gap-3"><div className="font-bold">{x.label||'—'}</div><b>{Number(x.amount||0).toFixed(2)} ر.س</b></div>{x.notes&&<div className="mt-1 text-xs text-slate-500">{x.notes}</div>}</div>)}<div className="mt-3 flex justify-between rounded-xl bg-slate-50 p-3 font-black"><span>إجمالي المستحقات</span><span>{entTotal.toFixed(2)} ر.س</span></div></section>

  <section className="mt-4 rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black text-[#09233f]">بيان الالتزامات</h2>{canEditFinance&&<button onClick={()=>addItem('obligation')} className="inline-flex items-center gap-1 rounded-lg bg-[#09233f] px-3 py-2 text-xs font-black text-white"><Plus size={14}/> إضافة التزام</button>}</div>{obl.map((x:any,i:number)=>canEditFinance&&x.editable!==false?<div key={x.id||i} className="mt-2 grid grid-cols-[1fr_130px_40px] gap-2 rounded-xl border p-2"><div><input value={x.label||''} onChange={e=>setItems(v=>v.map((it,j)=>it===x?{...it,label:e.target.value}:it))} placeholder="البيان / الوصف" className="w-full rounded-lg border p-2 font-bold"/><textarea value={x.notes||''} onChange={e=>setItems(v=>v.map((it,j)=>it===x?{...it,notes:e.target.value}:it))} placeholder="ملاحظات" className="mt-1 w-full rounded-lg border p-2 text-xs"/></div><input type="number" min="0" step="0.01" value={x.amount??0} onChange={e=>setItems(v=>v.map((it,j)=>it===x?{...it,amount:e.target.value}:it))} className="h-fit rounded-lg border p-2 text-left font-black"/><button onClick={()=>setItems(v=>v.filter(it=>it!==x))} className="h-fit rounded-lg border p-2 text-red-700"><Trash2 size={16}/></button></div>:<div key={x.id||i} className="mt-2 rounded-xl border p-3"><div className="flex justify-between gap-3"><div className="font-bold">{x.label}</div><b>{Number(x.amount||0).toFixed(2)} ر.س</b></div>{x.notes&&<div className="mt-1 text-xs text-slate-500">{x.notes}</div>}</div>)}<div className="mt-3 flex justify-between rounded-xl bg-slate-50 p-3 font-black"><span>إجمالي الالتزامات</span><span>{oblTotal.toFixed(2)} ر.س</span></div>{canEditFinance&&<div className="mt-3 flex gap-2"><button onClick={()=>addItem('entitlement')} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-black"><Plus size={14}/> إضافة مستحق</button><button disabled={saving} onClick={()=>void saveFinance()} className="inline-flex items-center gap-1 rounded-lg bg-[#09233f] px-4 py-2 text-xs font-black text-white"><Save size={14}/> حفظ البيانات المالية</button></div>}</section>

  <section className={"mt-4 rounded-2xl border-2 p-5 text-center "+(net>=0?'border-[#09233f]':'border-red-500 bg-red-50')}><div className="text-sm font-bold">{net>=0?'صافي المستحق للموظف':'المبلغ المتبقي على الموظف'}</div><div className="mt-1 text-3xl font-black">{Math.abs(net).toFixed(2)} ر.س</div><div className="mt-1 text-xs text-slate-500">إجمالي المستحقات − إجمالي الالتزامات</div></section>

  {c.source_snapshot?.clearance?.finance_notes&&<section className="mt-4 rounded-2xl border bg-amber-50 p-5"><h2 className="font-black text-[#09233f]">ملاحظات الإدارة المالية الواردة من إخلاء الطرف</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{c.source_snapshot.clearance.finance_notes}</p></section>}

  <section className="mt-4 rounded-2xl border bg-white p-5"><h2 className="font-black text-[#09233f]">الاعتمادات</h2><div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-5">{['employee','finance','hr','project_manager','general_manager'].map(k=>{const a=(c.approvals||[]).find((x:any)=>x.stage===k);return <div key={k} className="rounded-xl border p-3"><b>{stageLabels[k]}</b><div className="mt-2 text-xs text-slate-500">{a?.status==='approved'?'تم الاعتماد':'بانتظار الاعتماد'}</div><div className="mt-1 text-xs">{a?.approver_name||'—'}</div><div className="text-[11px] text-slate-500">{a?.acted_at?new Date(a.acted_at).toLocaleString('ar-SA'):'—'}</div></div>})}</div></section>

  {message&&<div className="mt-4 rounded-xl bg-blue-50 p-3 font-bold text-blue-800">{message}</div>}
  {stage&&c.current_stage===stage&&!['completed','rejected'].includes(c.status)&&<section className="mt-4 rounded-2xl border bg-white p-5"><h2 className="font-black text-[#09233f]">اعتماد {stageLabels[stage]}</h2><SignatureEditor value={signature} onChange={setSignature}/><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظات الاعتماد أو سبب الإرجاع/الرفض" className="mt-3 h-28 w-full rounded-xl border p-3"/><div className="mt-3 flex flex-wrap gap-2"><button disabled={saving} onClick={()=>void submit('approve')} className="inline-flex items-center gap-2 rounded-xl bg-[#09233f] px-5 py-3 font-black text-white"><CheckCircle2 size={17}/> اعتماد</button><button disabled={saving} onClick={()=>void submit('return')} className="inline-flex items-center gap-2 rounded-xl border bg-amber-50 px-5 py-3 font-black text-amber-800"><RotateCcw size={17}/> إرجاع للتعديل</button><button disabled={saving} onClick={()=>void submit('reject')} className="inline-flex items-center gap-2 rounded-xl border bg-red-50 px-5 py-3 font-black text-red-700">رفض</button></div></section>}
  {canEditFinance&&<section className="mt-4 rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-800">أدخلت المالية المستحقات والالتزامات والملاحظات. بعد الحفظ يمكن اعتماد المرحلة المالية.</section>}
 </div></main>
}
