'use client'
import {useEffect,useState} from 'react'
import {CheckCircle2,RotateCcw,ShieldCheck} from 'lucide-react'
import SignatureEditor from '@/app/components/signature/SignatureEditor'
export default function FinancialClearancePublic({params}:{params:Promise<{token:string}>}){
 const [token,setToken]=useState(''),[data,setData]=useState<any>(null),[signature,setSignature]=useState(''),[notes,setNotes]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 useEffect(()=>{void params.then(p=>setToken(p.token))},[params])
 useEffect(()=>{if(!token)return;fetch('/api/financial-clearances/public/'+token,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error||'الرابط غير صالح');setData(d.link)}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[token])
 const submit=async(action:string)=>{setMessage('');const r=await fetch('/api/financial-clearances/public/'+token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,signature,notes})});const d=await r.json().catch(()=>({}));if(!r.ok)return setMessage(d?.error||'تعذر تنفيذ الإجراء');setMessage(action==='approve'?'تم اعتماد المخالصة وإرسالها للإدارة المالية.':'تم إرجاع المخالصة للمراجعة.');setData((x:any)=>({...x,clearance:{...x.clearance,status:action==='approve'?'pending_finance':'returned'}}));setSignature('')}
 if(loading)return <main dir="rtl" className="min-h-screen bg-slate-50 p-10 text-center">جارٍ تحميل المخالصة...</main>
 if(!data)return <main dir="rtl" className="min-h-screen bg-slate-50 p-10 text-center text-red-700">{message||'الرابط غير صالح'}</main>
 const c=data.clearance,e=c.employee||{},items=c.items||[];const ent=items.filter((x:any)=>x.item_type==='entitlement');const obl=items.filter((x:any)=>x.item_type==='obligation');const total=(xs:any[])=>xs.reduce((s,x)=>s+Number(x.amount||0),0)
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-5xl"><header className="rounded-2xl bg-[#09233f] p-6 text-white"><div className="flex items-center gap-3"><ShieldCheck className="text-[#e2bd62]"/><div><div className="font-black">شركة البنية الأساسية للمقاولات</div><h1 className="mt-1 text-xl font-black">مخالصة مالية وإدارية نهائية وإبراء ذمة</h1><div className="text-xs text-slate-300">FINAL FINANCIAL & ADMINISTRATIVE SETTLEMENT AND RELEASE · {c.clearance_number}</div></div></div></header>
 <section className="mt-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black text-[#09233f]">بيانات الموظف</h2><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">{[['الاسم',e.full_name],['الرقم الوظيفي',e.employee_number],['الهوية/الإقامة',e.national_id],['المسمى',e.job_title],['القسم',e.department],['الشركة',e.company?.name],['تاريخ المباشرة',e.hire_date],['آخر يوم عمل',c.source_snapshot?.clearance?.last_work_date]].map(([k,v])=><div key={String(k)} className="rounded-lg bg-slate-50 p-3"><div className="text-xs text-slate-500">{k}</div><div className="mt-1 font-black">{v||'—'}</div></div>)}</div></section>
 <section className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-black">المستحقات</h2>{ent.map((x:any)=><div key={x.id} className="flex justify-between border-b py-2 text-sm"><span>{x.label}</span><b>{Number(x.amount).toFixed(2)} ر.س</b></div>)}<div className="mt-3 flex justify-between font-black"><span>الإجمالي</span><span>{total(ent).toFixed(2)} ر.س</span></div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-black">الالتزامات</h2>{obl.map((x:any)=><div key={x.id} className="flex justify-between border-b py-2 text-sm"><span>{x.label}</span><b>{Number(x.amount).toFixed(2)} ر.س</b></div>)}<div className="mt-3 flex justify-between font-black"><span>الإجمالي</span><span>{total(obl).toFixed(2)} ر.س</span></div></div></section>
 <section className="mt-4 rounded-2xl border-2 border-[#09233f] bg-white p-5 text-center"><div className="text-sm font-bold">صافي المستحق للموظف</div><div className="mt-1 text-3xl font-black text-[#09233f]">{(total(ent)-total(obl)).toFixed(2)} ر.س</div></section>
 <section className="mt-4 rounded-2xl border bg-white p-5"><h2 className="font-black text-[#09233f]">إقرار وإبراء الذمة</h2><p className="mt-3 text-sm leading-8">أقر بمراجعة بيانات المخالصة والمستحقات والالتزامات الواردة فيها، وبأنها تمثل التسوية المالية والإدارية حتى تاريخ آخر يوم عمل، وألتزم بالمحافظة على سرية بيانات ووثائق الشركة وتسليم جميع العهد والمتعلقات التابعة لها.</p></section>
 {message&&<div className="mt-4 rounded-xl bg-blue-50 p-3 font-bold text-blue-800">{message}</div>}
 {c.status==="pending_employee" ? (<section className="mt-4 rounded-2xl border bg-white p-5"><h2 className="font-black text-[#09233f]">اعتماد الموظف</h2><div className="mt-3"><SignatureEditor value={signature} onChange={setSignature}/></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظة أو سبب الإرجاع عند الحاجة" className="mt-3 h-28 w-full rounded-xl border p-3"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void submit("approve")} className="inline-flex items-center gap-2 rounded-xl bg-[#09233f] px-5 py-3 font-black text-white"><CheckCircle2 size={17}/> اعتماد</button><button onClick={()=>void submit("return")} className="inline-flex items-center gap-2 rounded-xl border bg-amber-50 px-5 py-3 font-black text-amber-800"><RotateCcw size={17}/> إرجاع للمراجعة</button></div></section>) : null}
 </div></main>
}
