import { NextRequest, NextResponse } from 'next/server'
import { getServerAuth, supabaseHeaders } from '@/lib/server-auth'
const ALLOWED=['admin','hr','interviewer','manager']
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://pdkdvaisggntdrvpxuur.supabase.co'
const editable=['employee_number','full_name','nationality','national_id','residency_status','phone','email','degree','specialization','job_title','department','project_name','work_location','manager_name','hire_date','contract_type','employment_status','basic_salary','housing_allowance','transportation_allowance','other_allowances','total_salary_with_allowances','notes']
async function rest(path:string,auth:any,init?:RequestInit){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...supabaseHeaders(auth),...(init?.headers||{})},cache:'no-store'})}
export async function GET(req:NextRequest,{params}:{params:Promise<{id:string}>}){try{const auth=await getServerAuth(req,ALLOWED);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});const{id}=await params;const[e,d]=await Promise.all([rest(`employee_records?select=*&id=eq.${encodeURIComponent(id)}&limit=1`,auth),rest(`employee_documents?select=*&employee_id=eq.${encodeURIComponent(id)}&order=created_at.desc`,auth)]);if(!e.ok)return NextResponse.json({error:await e.text()},{status:500});const employee=(await e.json())[0]||null;if(!employee)return NextResponse.json({error:'لم يتم العثور على الموظف'},{status:404});return NextResponse.json({employee,documents:d.ok?await d.json():[]},{headers:{'Cache-Control':'no-store'}})}catch(err){return NextResponse.json({error:err instanceof Error?err.message:'تعذر تحميل الملف'},{status:500})}}
export async function PATCH(req:NextRequest,{params}:{params:Promise<{id:string}>}){try{const auth=await getServerAuth(req,ALLOWED);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});const{id}=await params,body=await req.json(),payload=Object.fromEntries(editable.filter(k=>Object.prototype.hasOwnProperty.call(body,k)).map(k=>[k,body[k]]));const r=await rest(`employee_records?id=eq.${encodeURIComponent(id)}`,auth,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)return NextResponse.json({error:await r.text()},{status:500});return NextResponse.json({employee:(await r.json())[0]||null})}catch(err){return NextResponse.json({error:err instanceof Error?err.message:'تعذر حفظ البيانات'},{status:500})}}
export async function POST(req:NextRequest,{params}:{params:Promise<{id:string}>}){try{const auth=await getServerAuth(req,ALLOWED);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});const{id}=await params,body=await req.json();if(!body.document_name)return NextResponse.json({error:'اسم المستند مطلوب'},{status:400});const payload={document_type:body.document_type||'مستند آخر',document_name:body.document_name,document_number:body.document_number||null,issue_date:body.issue_date||null,expiry_date:body.expiry_date||null,status:body.status||'ساري',notes:body.notes||null,employee_id:id};const r=await rest('employee_documents',auth,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)return NextResponse.json({error:await r.text()},{status:500});return NextResponse.json({document:(await r.json())[0]||null})}catch(err){return NextResponse.json({error:err instanceof Error?err.message:'تعذر إضافة المستند'},{status:500})}}
