'use client'

import Link from 'next/link'
import {useParams,useRouter} from 'next/navigation'
import {useEffect,useMemo,useState} from 'react'
import {ArrowRight,Copy,ExternalLink,MessageCircle,Plus,RefreshCw,UserRoundCheck,Pencil,Trash2,Printer,FileText} from 'lucide-react'

type Requirement={id:string;name:string;category:string;weight:number;required:boolean;sort_order:number}
type Candidate={id:string;request_id:string;share_token:string;full_name:string;phone:string;status:string;degree:string;specialization:string;total_experience_years:number|null;saudi_experience_years:number|null;updated_at:string}
type Score={candidate_id:string;requirement_id:string;score:number;evidence:string}
const statuses=['جديد','تم إرسال الرابط','أكمل البيانات','تحت المراجعة','مطابق','مطابق جزئيًا','غير مطابق','مرشح للمقابلة','تم القبول','مرفوض']

export default function RequestDetails(){
 const{id}=useParams<{id:string}>(),router=useRouter();const[request,setRequest]=useState<any>(null),[requirements,setRequirements]=useState<Requirement[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[scores,setScores]=useState<Score[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[creating,setCreating]=useState(false),[createdLink,setCreatedLink]=useState(''),[copied,setCopied]=useState(''),[readOnly,setReadOnly]=useState(false)
 const load=async()=>{if(!id)return;setLoading(true);setError('');try{const r=await fetch(`/api/requests/${id}/data`,{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'تعذر تحميل الطلب');if(!b.request)throw new Error('الطلب غير موجود');setRequest(b.request);setRequirements(b.requirements||[]);setCandidates(b.candidates||[]);setScores(b.scores||[]);setReadOnly(b.role==='interview_viewer')}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الطلب')}finally{setLoading(false)}}
 useEffect(()=>{load()},[id])
 const scoreMap=useMemo(()=>{const m:Record<string,Record<string,number>>={};scores.forEach(s=>(m[s.candidate_id]??={})[s.requirement_id]=Number(s.score||0));return m},[scores])
 const metrics=(cid:string)=>{const tw=requirements.reduce((s,r)=>s+Number(r.weight||0),0);if(!tw)return{overall:0,requiredCompliance:0};const overall=Math.round(requirements.reduce((s,r)=>s+Number(r.weight||0)*(scoreMap[cid]?.[r.id]||0)/100,0)/tw*100);const req=requirements.filter(r=>r.required),matched=req.filter(r=>(scoreMap[cid]?.[r.id]||0)>=50);return{overall,requiredCompliance:req.length?Math.round(matched.length/req.length*100):100}}
 const candidateLink=(t:string)=>`${window.location.origin}/candidate/${t}`
 const copy=async(t:string)=>{const l=candidateLink(t);await navigator.clipboard?.writeText(l);setCopied(t);setTimeout(()=>setCopied(''),1500)}
 const whatsapp=(c:Candidate)=>{const raw=(c.phone||'').replace(/\D/g,'');const pn=raw.startsWith('0')?`966${raw.slice(1)}`:raw;window.open(`https://wa.me/${pn}?text=${encodeURIComponent(`مرحباً ${c.full_name}، نرجو تعبئة نموذج بياناتك الوظيفية عبر الرابط التالي: ${candidateLink(c.share_token)}`)}`,'_blank')}
 const createCandidate=async()=>{if(readOnly)return;setCreating(true);setError('');try{const r=await fetch('/api/candidates/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',requestId:id,fullName:name.trim()||'مرشح جديد',phone:phone.trim()})});const b=await r.json();if(!r.ok)throw new Error(b.error||'تعذر إضافة المرشح');setCreatedLink(candidateLink(b.candidate.share_token));setName('');setPhone('');await load()}catch(e){setError(e instanceof Error?e.message:'تعذر إضافة المرشح')}finally{setCreating(false)}}
 const updateStatus=async(cid:string,status:string)=>{if(readOnly)return;const r=await fetch('/api/candidates/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',candidateId:cid,status})});const b=await r.json();if(!r.ok){setError(b.error||'تعذر تحديث الحالة');return}setCandidates(x=>x.map(c=>c.id===cid?{...c,status}:c))}
 const deleteCandidate=async(cid:string)=>{if(readOnly||!confirm('هل تريد حذف هذا المرشح فقط؟'))return;const r=await fetch('/api/candidates/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',candidateId:cid})});const b=await r.json();if(!r.ok){setError(b.error||'تعذر حذف المرشح');return}setCandidates(x=>x.filter(c=>c.id!==cid));setScores(x=>x.filter(s=>s.candidate_id!==cid))}
 const deleteRequest=async()=>{if(readOnly||!confirm('هل أنت متأكد من حذف الطلب وجميع بياناته المرتبطة؟'))return;const r=await fetch(`/api/requests/${id}/manage`,{method:'DELETE'});const b=await r.json().catch(()=>({}));if(!r.ok){setError(b.error||'تعذر حذف الطلب');return}router.push('/requests')}
 if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center">جاري تحميل الطلب...</main>
 if(error&&!request)return <main dir="rtl" className="min-h-screen grid place-items-center p-6"><div className="bg-white border-2 border-red-200 rounded-2xl p-8 text-red-700 font-bold">{error}</div></main>
 return <main className="min-h-screen bg-[#f5f7fa]" dir="rtl"><header className="bg-[#09233f] text-white px-6 py-5"><div className="max-w-7xl mx-auto flex flex-wrap items-center justify-between gap-4"><div><div className="text-[#d4a72c] font-bold">البنية الاساسية للمقاولات</div><h1 className="text-2xl font-black mt-1">{request?.exact_type||'طلب وظيفي'}</h1><p className="text-slate-300 text-sm mt-1">{request?.request_type} • {request?.status}</p></div><div className="flex flex-wrap gap-2"><Link href={`/reports/request/${id}`} className="bg-[#b88618] rounded-xl px-4 py-2 font-bold flex items-center gap-2"><Printer size={16}/> تقرير الطلب</Link>{!readOnly&&<><Link href={`/requests/${id}/edit`} className="border border-white/20 rounded-xl px-4 py-2 flex items-center gap-2"><Pencil size={16}/> تعديل</Link><button onClick={deleteRequest} className="border border-red-300/40 text-red-200 rounded-xl px-4 py-2 flex items-center gap-2"><Trash2 size={16}/> حذف</button></>}<Link href="/requests" className="border border-white/20 rounded-xl px-4 py-2 flex items-center gap-2"><ArrowRight size={17}/> الطلبات</Link></div></div></header>
 <div className="max-w-7xl mx-auto p-5 md:p-8">{error&&<div className="mb-5 bg-red-50 text-red-700 p-4 rounded-xl">{error}</div>}{readOnly&&<div className="mb-5 bg-blue-50 border border-blue-200 text-blue-800 p-4 rounded-xl font-bold">وضع الاطلاع فقط: يمكنك مشاهدة الطلب والمرشحين والتقييمات دون تعديل.</div>}
 <section className="grid lg:grid-cols-[1.4fr_.6fr] gap-5 mb-6"><div className="card p-6 bg-white rounded-2xl border border-slate-200"><div className="flex justify-between items-center"><div><h2 className="section-title mb-0">متطلبات ومعايير الطلب</h2><p className="text-xs text-slate-500 mt-1">المعايير التي يتم بناء عليها تقييم المرشحين</p></div><button onClick={load} className="text-slate-500 p-2"><RefreshCw size={18}/></button></div><div className="grid md:grid-cols-2 gap-3 mt-5">{requirements.map(r=><div key={r.id} className={`border rounded-xl p-4 ${r.required?'border-[#b88618] bg-amber-50/40':'bg-slate-50/50'}`}><div className="flex justify-between gap-3"><b>{r.name}</b><span className="text-[#b88618] font-bold">{Number(r.weight)}%</span></div><div className="text-xs text-slate-500 mt-2">{r.category||'عام'} {r.required?'• متطلب أساسي':''}</div></div>)}</div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm font-bold flex justify-between border"><span>إجمالي أوزان المتطلبات</span><span>{requirements.reduce((s,r)=>s+Number(r.weight||0),0).toFixed(2)}%</span></div></div>
 <div className="card p-6 bg-white rounded-2xl border border-slate-200">{readOnly?<><h2 className="section-title">روابط المرشحين</h2><p className="text-xs text-slate-500">يمكن فتح بيانات المرشحين ومتابعة تقييماتهم.</p></>:<><h2 className="section-title">إضافة مرشح جديد</h2><p className="text-xs text-slate-500 mb-3">إنشاء رابط مباشر للمرشح لتعبئة بياناته.</p><input className="input mb-3 w-full border rounded-xl p-3 text-sm" placeholder="اسم المرشح الكامل" value={name} onChange={e=>setName(e.target.value)}/><input className="input mb-3 w-full border rounded-xl p-3 text-sm" placeholder="رقم الجوال (05xxxxxxxx)" value={phone} onChange={e=>setPhone(e.target.value)}/><button onClick={createCandidate} disabled={creating} className="w-full rounded-xl py-3 font-bold flex justify-center gap-2 bg-[#b88618] text-white">{creating?'جاري الإضافة...':<><Plus size={18}/> إنشاء رابط مرشح</>}</button>{createdLink&&<div className="mt-4 bg-green-50 text-green-700 rounded-xl p-3 text-sm break-all border border-green-200"><b>تم إنشاء الرابط:</b><div className="mt-1">{createdLink}</div><button onClick={()=>navigator.clipboard?.writeText(createdLink)} className="mt-2 text-xs font-bold underline">نسخ الرابط</button></div>}</>}</div></section>
 <section className="card p-6 bg-white rounded-2xl border border-slate-200"><div className="flex justify-between items-center mb-5"><div><h2 className="section-title mb-1">المرشحون للوظيفة</h2><p className="text-sm text-slate-500">تحليل التوافق حسب أوزان المتطلبات والمتطلبات الأساسية.</p></div><div className="font-bold text-[#09233f] text-sm bg-slate-100 px-3 py-1.5 rounded-xl">{candidates.length} مرشح</div></div>{!candidates.length?<div className="py-12 text-center text-slate-500">لم تتم إضافة مرشحين بعد في هذا الطلب.</div>:<div className="space-y-4">{candidates.map(c=>{const m=metrics(c.id);return <div key={c.id} className="border border-slate-200 rounded-2xl p-5 bg-white"><div className="flex flex-col xl:flex-row xl:items-center justify-between gap-5"><div className="min-w-0"><div className="flex items-center gap-2"><UserRoundCheck size={20} className="text-[#b88618]"/><h3 className="font-black text-lg text-[#09233f]">{c.full_name}</h3></div><p className="text-sm text-slate-500 mt-1">{c.phone||'بدون جوال'} {c.specialization?`• ${c.specialization}`:''} {c.total_experience_years!=null?`• ${c.total_experience_years} سنة خبرة`:''}</p><div className="flex flex-wrap gap-2 mt-3"><span className="px-3 py-1 rounded-full bg-slate-100 text-xs font-bold">المطابقة {m.overall}%</span><span className="px-3 py-1 rounded-full bg-amber-50 text-amber-800 text-xs font-bold">المتطلبات الأساسية {m.requiredCompliance}%</span></div></div><div className="flex flex-wrap items-center gap-2">{!readOnly&&<select value={c.status||'جديد'} onChange={e=>updateStatus(c.id,e.target.value)} className="border rounded-xl px-3 py-2 bg-white text-sm">{statuses.map(s=><option key={s}>{s}</option>)}</select>}<Link href={`/requests/${id}/candidates/${c.id}`} className="bg-[#09233f] text-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><FileText size={16}/> فتح التقييم</Link><button onClick={()=>copy(c.share_token)} className="border rounded-xl px-3 py-2 font-bold inline-flex items-center gap-1"><Copy size={15}/>{copied===c.share_token?'تم النسخ':'رابط المرشح'}</button><button onClick={()=>whatsapp(c)} className="border rounded-xl px-3 py-2 font-bold inline-flex items-center gap-1"><MessageCircle size={15}/> واتساب</button>{!readOnly&&<button onClick={()=>deleteCandidate(c.id)} className="border border-red-200 text-red-600 rounded-xl px-3 py-2 font-bold"><Trash2 size={15}/></button>}</div></div></div>})}</div>}</section>
 <section className="grid md:grid-cols-3 gap-4 mt-6"><div className="card p-5"><div className="text-slate-500 text-sm">إجمالي المرشحين</div><div className="text-3xl font-black text-[#09233f] mt-1">{candidates.length}</div></div><div className="card p-5"><div className="text-slate-500 text-sm">متوسط المطابقة</div><div className="text-3xl font-black text-[#09233f] mt-1">{candidates.length?Math.round(candidates.reduce((s,c)=>s+metrics(c.id).overall,0)/candidates.length):0}%</div></div><div className="card p-5"><div className="text-slate-500 text-sm">المقابلات والتقييم</div><Link href="/interviews" className="text-[#b88618] font-bold mt-2 inline-flex items-center gap-1">فتح القسم الرئيسي <ExternalLink size={15}/></Link></div></section></div></main>
}
