'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {ArrowLeft,FileText,Save,UserRound,CalendarDays,ClipboardCheck,BriefcaseBusiness,Printer,Briefcase,WalletCards,ShieldCheck,FolderOpen} from 'lucide-react'
type Employee=Record<string,any>;type Job=Record<string,any>;type Document=Record<string,any>;type Company={id:string;name:string;unified_number:string}
const docTypes=['الهوية الوطنية / الإقامة','العقد','المؤهل العلمي','العضوية المهنية','شهادة التأمينات','شهادة صحية','رخصة القيادة','مستند آخر']
const fields=[['employee_number','الرقم الوظيفي'],['full_name','الاسم الكامل'],['nationality','الجنسية'],['residency_status','حالة العامل / الإقامة'],['phone','الجوال'],['email','البريد الإلكتروني'],['degree','المؤهل'],['specialization','التخصص'],['department','الإدارة'],['project_name','المشروع'],['work_location','موقع العمل'],['manager_name','المدير المباشر'],['hire_date','تاريخ التعيين'],['contract_type','نوع العقد'],['employment_status','الحالة الوظيفية'],['basic_salary','الراتب الأساسي'],['housing_allowance','بدل السكن'],['transportation_allowance','بدل النقل'],['other_allowances','البدلات الأخرى'],['total_salary_with_allowances','إجمالي الراتب مع البدلات']] as const
const arr=(v:any)=>Array.isArray(v)?v:[]
const isSaudi=(v:any)=>String(v??'').trim().toLowerCase()==='سعودي'
const isResidencyDoc=(d:any)=>String(d?.document_name||'').includes('الإقامة')||String(d?.document_type||'').includes('الإقامة')||String(d?.document_type||'').toLowerCase().includes('residency')||String(d?.document_type||'').toLowerCase().includes('iqama')
export default function EmployeePage({params}:{params:Promise<{id:string}>}){
 const[id,setId]=useState(''),[employee,setEmployee]=useState<Employee|null>(null),[jobs,setJobs]=useState<Job[]>([]),[job,setJob]=useState<Job|null>(null),[docs,setDocs]=useState<Document[]>([]),[companies,setCompanies]=useState<Company[]>([]),[residencyExpiry,setResidencyExpiry]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState('overview')
 const[doc,setDoc]=useState({document_type:docTypes[0],document_name:'',document_number:'',issue_date:'',expiry_date:'',status:'ساري',notes:''})
 useEffect(()=>{params.then(p=>setId(p.id))},[params])
 useEffect(()=>{if(!id)return;(async()=>{try{const[r,j,c]=await Promise.all([fetch('/api/employees/'+id+'/full',{cache:'no-store'}),fetch('/api/job-descriptions',{cache:'no-store'}),fetch('/api/companies',{cache:'no-store'})]);const b=await r.json(),jb=await j.json();if(!r.ok)throw new Error(b.error||'تعذر تحميل ملف الموظف');setEmployee(b.employee);setDocs(b.documents||[]);const residency=(b.documents||[]).find((d:any)=>isResidencyDoc(d));setResidencyExpiry(residency?.expiry_date||'');setJob(b.job_description||null);if(j.ok)setJobs(jb.jobs||[]);if(c.ok){const cb=await c.json();setCompanies(cb.companies||[])}}catch(e){setMessage(e instanceof Error?e.message:'تعذر تحميل الملف')}finally{setLoading(false)}})()},[id])
 const change=(k:string,v:any)=>setEmployee((e:any)=>({...e,[k]:v}))
 const selectJob=(jobId:string)=>{const j=jobs.find(x=>x.id===jobId)||null;setJob(j);setEmployee(e=>e?{...e,job_description_id:jobId||null,job_title:j?.name||e.job_title,department:j?.department||e.department}:e)}
 const save=async()=>{if(!employee)return;setSaving(true);setMessage('');try{if(isSaudi(employee.nationality)&&!String(employee.national_id||'').trim())throw new Error('رقم الهوية الوطنية مطلوب للموظف السعودي.');if(!isSaudi(employee.nationality)&&(!String(employee.national_id||'').trim()||!residencyExpiry))throw new Error('لغير السعودي يجب إدخال رقم الإقامة وتاريخ انتهاء الإقامة.');const r=await fetch('/api/employees/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(employee)});const b=await r.json();if(!r.ok)throw new Error(b.error||'تعذر الحفظ');if(!isSaudi(employee.nationality)){const dr=await fetch('/api/employees/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_type:'الهوية الوطنية / الإقامة',document_name:'الإقامة',document_number:employee.national_id,expiry_date:residencyExpiry,status:'ساري',replace_residency:true})});const db=await dr.json();if(!dr.ok)throw new Error(db.error||'تعذر حفظ تاريخ انتهاء الإقامة');setDocs(d=>{const filtered=d.filter((x:any)=>!isResidencyDoc(x));return db.document?[db.document,...filtered]:d})}else setResidencyExpiry('');setEmployee(b.employee||employee);setMessage('تم حفظ بيانات الموظف.')}catch(e){setMessage(e instanceof Error?e.message:'تعذر الحفظ')}finally{setSaving(false)}}
 const addDoc=async()=>{if(!doc.document_name)return setMessage('اكتب اسم المستند أولًا.');try{const r=await fetch('/api/employees/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(doc)});const b=await r.json();if(!r.ok)throw new Error(b.error||'تعذر إضافة المستند');setDocs(d=>[b.document,...d]);setDoc({...doc,document_name:'',document_number:'',issue_date:'',expiry_date:'',notes:''});setMessage('تمت إضافة المستند.')}catch(e){setMessage(e instanceof Error?e.message:'تعذر إضافة المستند')}}
 if(loading)return <main className="employee-loading" dir="rtl"><div className="loading-skeleton h-8 w-60 mx-auto mb-3"/><div className="loading-skeleton h-32 max-w-5xl mx-auto"/></main>
 if(!employee)return <main className="empty-state m-6" dir="rtl"><strong>{message||'لم يتم العثور على الموظف.'}</strong></main>
 const company=companies.find(c=>c.id===employee.company_id)
 const formLinks=[['/forms/leave','طلب إجازة',CalendarDays],['/forms/advance','طلب سلفة',WalletCards],['/forms/clearance','إخلاء طرف',ClipboardCheck],['/forms/joining/'+id,'مباشرة العمل',BriefcaseBusiness]] as const
 const tabs=[['overview','نظرة عامة',UserRound],['personal','البيانات الشخصية',UserRound],['job','البيانات الوظيفية',Briefcase],['documents','المستندات',FolderOpen],['actions','الإجراءات',ClipboardCheck]] as const
 return <main className="employee-profile" dir="rtl"><div className="employee-shell">
  <div className="employee-breadcrumb"><Link href="/employees">الموظفون</Link><span>/</span><span>ملف الموظف</span></div>
  <header className="employee-hero"><div className="employee-identity"><div className="employee-avatar">{String(employee.full_name||'م').trim().slice(0,1)}</div><div><span className="hr-page-kicker">EMPLOYEE PROFILE</span><h1>{employee.full_name}</h1><p>{employee.employee_number||'بدون رقم وظيفي'} <span>•</span> {employee.job_title||'المسمى غير محدد'}</p><div className="employee-meta"><span>{company?.name||'شركة غير محددة'}</span><span>{employee.department||'إدارة غير محددة'}</span><span className={employee.employment_status?'status-badge success':'status-badge'}>{employee.employment_status||'الحالة غير محددة'}</span></div></div></div><div className="employee-actions"><Link href={'/employees/'+id+'/print'} className="btn-gold rounded-lg px-4 py-2.5 font-black inline-flex items-center gap-2"><Printer size={16}/> طباعة الملف</Link><Link href="/employees" className="text-link"><ArrowLeft size={15}/> العودة</Link></div></header>
  <nav className="employee-tabs">{tabs.map(([k,label,Icon])=>{const I=Icon as any;return <button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I size={15}/>{label}</button>})}</nav>
  {tab==='overview'&&<div className="employee-overview"><section className="profile-main-panel"><div className="panel-head"><div><span className="eyebrow">OVERVIEW</span><h2>ملخص الموظف</h2></div></div><div className="profile-facts"><div><span>الرقم الوظيفي</span><b>{employee.employee_number||'—'}</b></div><div><span>الجنسية</span><b>{employee.nationality||'—'}</b></div><div><span>الهوية / الإقامة</span><b>{employee.national_id||'—'}</b></div><div><span>الجوال</span><b>{employee.phone||'—'}</b></div><div><span>تاريخ التعيين</span><b>{employee.hire_date||'—'}</b></div><div><span>الحالة</span><b>{employee.employment_status||'—'}</b></div></div></section><aside className="profile-side-panel"><div className="panel-head"><div><span className="eyebrow">QUICK ACTIONS</span><h2>إجراءات الموظف</h2></div></div><div className="quick-action-list">{formLinks.map(([href,title,Icon])=>{const I=Icon as any;return <Link key={href} href={href}><I size={17}/><span>{title}</span><ArrowLeft size={14}/></Link>})}</div></aside></div>}
  {tab==='personal'&&<section className="profile-form-panel"><SectionHead title="البيانات الشخصية والاتصال" kicker="PERSONAL DATA"/><div className="profile-form-grid">{[['full_name','الاسم الكامل'],['nationality','الجنسية'],['phone','الجوال'],['email','البريد الإلكتروني'],['degree','المؤهل'],['specialization','التخصص']].map(([k,l])=><label key={k}><span>{l}</span><input value={employee[k]??''} onChange={e=>change(k,e.target.value)}/></label>)}<label><span>{isSaudi(employee.nationality)?'رقم الهوية الوطنية':'رقم الإقامة'}</span><input value={employee.national_id??''} onChange={e=>change('national_id',e.target.value)}/></label>{!isSaudi(employee.nationality)&&<label><span>تاريخ انتهاء الإقامة</span><input type="date" value={residencyExpiry} onChange={e=>setResidencyExpiry(e.target.value)}/></label>}</div><SaveBar saving={saving} onSave={save}/></section>}
  {tab==='job'&&<><section className="profile-form-panel"><SectionHead title="البيانات الوظيفية والشركة" kicker="EMPLOYMENT"/><div className="profile-form-grid"><label><span>الشركة</span><select value={employee.company_id||''} onChange={e=>change('company_id',e.target.value||null)}><option value="">اختر الشركة</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name} — {c.unified_number}</option>)}</select></label><label><span>المسمى الوظيفي المرتبط</span><select value={employee.job_description_id||''} onChange={e=>selectJob(e.target.value)}><option value="">اختر المسمى الوظيفي</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.name} — {j.department}</option>)}</select></label>{fields.filter(([k])=>!['employee_number','full_name','nationality','residency_status','phone','email','degree','specialization'].includes(k)).map(([k,l])=><label key={k}><span>{l}</span><input type={k==='hire_date'?'date':k.includes('salary')||k.includes('allowance')?'number':'text'} value={employee[k]??''} onChange={e=>change(k,e.target.value)}/></label>)}</div><SaveBar saving={saving} onSave={save}/></section>{job&&<section className="profile-job-detail"><div><span className="eyebrow">JOB DESCRIPTION</span><h2>{job.name}</h2><p>{job.purpose||'—'}</p></div><div><h3>المسؤوليات والمهام</h3><ul>{arr(job.responsibilities).map((x:any,i:number)=><li key={i}>{String(x)}</li>)}</ul></div></section>}</>}
  {tab==='documents'&&<section className="profile-documents"><div className="profile-form-panel"><SectionHead title="إضافة مستند" kicker="DOCUMENTS"/><div className="profile-form-grid">{[['document_name','اسم المستند'],['document_number','رقم المستند'],['issue_date','تاريخ الإصدار'],['expiry_date','تاريخ الانتهاء'],['status','الحالة'],['notes','ملاحظات']].map(([k,l])=><label key={k}><span>{l}</span><input type={k.includes('date')?'date':'text'} value={doc[k as keyof typeof doc]} onChange={e=>setDoc({...doc,[k]:e.target.value})}/></label>)}<label><span>نوع المستند</span><select value={doc.document_type} onChange={e=>setDoc({...doc,document_type:e.target.value})}>{docTypes.map(x=><option key={x}>{x}</option>)}</select></label></div><button onClick={addDoc} className="btn-primary rounded-lg px-5 py-2.5 font-black mt-4">إضافة المستند</button></div><div className="document-list">{docs.length===0?<div className="empty-state"><strong>لا توجد مستندات</strong><span>أضف أول مستند من النموذج أعلاه.</span></div>:docs.map(d=><article key={d.id}><div className="document-type"><FileText size={17}/></div><div className="document-copy"><b>{d.document_name}</b><span>{d.document_type} {d.document_number?'• '+d.document_number:''}</span><small>الإصدار: {d.issue_date||'—'} • الانتهاء: {d.expiry_date||'—'} • {d.status||'—'}</small></div></article>)}</div></section>}
  {tab==='actions'&&<section className="profile-actions-page"><div className="panel-head"><div><span className="eyebrow">EMPLOYEE ACTIONS</span><h2>الإجراءات والنماذج</h2></div></div><div className="action-board">{formLinks.map(([href,title,Icon])=>{const I=Icon as any;return <Link key={href} href={href}><I size={20}/><span><b>{title}</b><small>فتح الإجراء الخاص بالموظف</small></span><ArrowLeft size={15}/></Link>})}</div></section>}
  {message&&<div className="profile-message">{message}</div>}
 </div></main>
}
function SectionHead({title,kicker}:{title:string;kicker:string}){return <div className="panel-head"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2></div></div>}
function SaveBar({saving,onSave}:{saving:boolean;onSave:()=>void}){return <div className="save-bar"><span>تأكد من مراجعة البيانات قبل الحفظ.</span><button onClick={onSave} disabled={saving} className="btn-primary rounded-lg px-5 py-2.5 font-black inline-flex items-center gap-2"><Save size={16}/>{saving?'جاري الحفظ...':'حفظ التغييرات'}</button></div>}
