'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, FileText, Save, UserRound, CalendarDays, WalletCards, ClipboardCheck, BriefcaseBusiness } from 'lucide-react'

type Employee=Record<string,any>; type Document=Record<string,any>
const docTypes=['الهوية الوطنية / الإقامة','العقد','المؤهل العلمي','العضوية المهنية','شهادة التأمينات','شهادة صحية','رخصة القيادة','مستند آخر']
const fields=[['employee_number','الرقم الوظيفي'],['full_name','الاسم الكامل'],['nationality','الجنسية'],['national_id','رقم الهوية / الإقامة'],['residency_status','حالة العامل'],['phone','الجوال'],['email','البريد الإلكتروني'],['degree','المؤهل'],['specialization','التخصص'],['job_title','المسمى الوظيفي'],['department','الإدارة'],['project_name','المشروع'],['work_location','موقع العمل'],['manager_name','المدير المباشر'],['hire_date','تاريخ التعيين'],['contract_type','نوع العقد'],['employment_status','الحالة الوظيفية'],['basic_salary','الراتب الأساسي'],['housing_allowance','بدل السكن'],['transportation_allowance','بدل النقل'],['other_allowances','البدلات الأخرى'],['total_salary_with_allowances','إجمالي الراتب مع البدلات']] as const

export default function EmployeePage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''); const [employee,setEmployee]=useState<Employee|null>(null); const [docs,setDocs]=useState<Document[]>([]); const [doc,setDoc]=useState({document_type:docTypes[0],document_name:'',document_number:'',issue_date:'',expiry_date:'',status:'ساري',notes:''}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
 useEffect(()=>{params.then(p=>setId(p.id))},[params])
 useEffect(()=>{if(!id)return;(async()=>{try{const r=await fetch(`/api/employees/${id}`,{cache:'no-store'});const body=await r.json();if(!r.ok)throw new Error(body.error||'تعذر تحميل ملف الموظف');setEmployee(body.employee);setDocs(body.documents||[])}catch(e){setMessage(e instanceof Error?e.message:'تعذر تحميل ملف الموظف')}finally{setLoading(false)}})()},[id])
 const change=(k:string,v:any)=>setEmployee((e:any)=>({...e,[k]:v}))
 const save=async()=>{if(!employee)return;setSaving(true);setMessage('');try{const r=await fetch(`/api/employees/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(employee)});const body=await r.json();if(!r.ok)throw new Error(body.error||'تعذر الحفظ');setEmployee(body.employee||employee);setMessage('تم حفظ بيانات الموظف.')}catch(e){setMessage(e instanceof Error?e.message:'تعذر الحفظ')}finally{setSaving(false)}}
 const addDoc=async()=>{if(!doc.document_name)return setMessage('اكتب اسم المستند أولًا.');try{const r=await fetch(`/api/employees/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(doc)});const body=await r.json();if(!r.ok)throw new Error(body.error||'تعذر إضافة المستند');setDocs(d=>[body.document,...d]);setDoc({...doc,document_name:'',document_number:'',issue_date:'',expiry_date:'',notes:''});setMessage('تمت إضافة المستند.')}catch(e){setMessage(e instanceof Error?e.message:'تعذر إضافة المستند')}}
 if(loading)return <main className="min-h-screen bg-[#f5f7fa] p-10 text-center" dir="rtl">جاري التحميل...</main>
 if(!employee)return <main className="min-h-screen bg-[#f5f7fa] p-10 text-center" dir="rtl">{message||'لم يتم العثور على الموظف.'}</main>
 const formLinks=[['/forms/leave','طلب إجازة','إنشاء وطباعة طلب إجازة',CalendarDays],['/forms/advance','طلب سلفة','إنشاء وطباعة طلب سلفة مالية',WalletCards],['/forms/clearance','إخلاء طرف','إنشاء وطباعة إخلاء طرف',ClipboardCheck],['/forms/joining/'+id,'مباشرة العمل','فتح نموذج مباشرة العمل',BriefcaseBusiness]] as const
 return <main className="min-h-screen bg-[#f5f7fa]" dir="rtl"><div className="max-w-7xl mx-auto p-5 md:p-8"><header className="flex justify-between items-center mb-7"><div><div className="text-sm text-[#b88618] font-bold">ملف موظف</div><h1 className="text-3xl font-black text-[#09233f]">{employee.full_name}</h1><p className="text-slate-500">{employee.employee_number||'بدون رقم وظيفي'} • {employee.job_title||'—'}</p></div><Link href="/employees" className="flex items-center gap-2 font-bold text-[#09233f]"><ArrowLeft size={18}/> الموظفون</Link></header>
 <section className="mb-5"><div className="flex items-center gap-2 mb-3 font-black text-[#09233f]"><FileText size={20}/> النماذج السريعة</div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{formLinks.map(([href,title,desc,Icon])=><Link key={href} href={href} className="bg-white border rounded-2xl p-4 hover:shadow-md transition"><Icon size={21} className="text-[#b88618]"/><div className="font-black text-[#09233f] mt-2">{title}</div><div className="text-xs text-slate-500 mt-1">{desc}</div></Link>)}</div></section>
 <div className="grid lg:grid-cols-2 gap-5"><section className="card p-6"><div className="flex items-center gap-2 mb-5 font-black text-[#09233f]"><UserRound size={20}/> البيانات الأساسية والمالية</div><div className="grid md:grid-cols-2 gap-4">{fields.map(([k,l])=><label key={k} className="block"><span className="block font-bold mb-1 text-sm">{l}</span><input type={k==='hire_date'?'date':k.includes('salary')||k.includes('allowance')?'number':'text'} value={employee[k]??''} onChange={e=>change(k,e.target.value)} className="w-full border rounded-xl px-3 py-2.5"/></label>)}</div><label className="block mt-4 font-bold">ملاحظات<textarea value={employee.notes||''} onChange={e=>change('notes',e.target.value)} rows={4} className="w-full border rounded-xl px-3 py-2.5 mt-1"/></label><button onClick={save} disabled={saving} className="btn-primary mt-5 rounded-xl px-5 py-3 font-bold inline-flex gap-2 items-center"><Save size={17}/>{saving?'جاري الحفظ...':'حفظ البيانات'}</button></section>
 <section className="card p-6"><div className="flex items-center gap-2 mb-5 font-black text-[#09233f]"><FileText size={20}/> مستندات الموظف</div><div className="grid md:grid-cols-2 gap-3">{[['document_type','نوع المستند'],['document_name','اسم المستند'],['document_number','رقم المستند'],['issue_date','تاريخ الإصدار'],['expiry_date','تاريخ الانتهاء'],['status','الحالة'],['notes','ملاحظات']].map(([k,l])=>k==='document_type'?<label key={k} className="block"><span className="block font-bold mb-1 text-sm">{l}</span><select value={doc[k as keyof typeof doc]} onChange={e=>setDoc({...doc,[k]:e.target.value})} className="w-full border rounded-xl px-3 py-2.5">{docTypes.map(x=><option key={x}>{x}</option>)}</select></label>:<label key={k} className="block"><span className="block font-bold mb-1 text-sm">{l}</span><input type={k.includes('date')?'date':'text'} value={doc[k as keyof typeof doc]} onChange={e=>setDoc({...doc,[k]:e.target.value})} className="w-full border rounded-xl px-3 py-2.5"/></label>)}</div><button onClick={addDoc} className="mt-4 btn-primary rounded-xl px-5 py-3 font-bold">إضافة المستند</button><div className="mt-6 space-y-3">{docs.length===0?<div className="text-slate-500">لا توجد مستندات مسجلة.</div>:docs.map(d=><div key={d.id} className="border rounded-xl p-4"><div className="font-bold text-[#09233f]">{d.document_name}</div><div className="text-sm text-slate-500">{d.document_type} {d.document_number?`• ${d.document_number}`:''}</div><div className="text-xs mt-2">الإصدار: {d.issue_date||'—'} • الانتهاء: {d.expiry_date||'—'} • {d.status}</div></div>)}</div></section></div>{message&&<div className="mt-5 p-4 rounded-xl bg-slate-50">{message}</div>}</div></main>
}
