'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, FileText, Save, UserRound, CalendarDays, WalletCards, ClipboardCheck, BriefcaseBusiness } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Employee=Record<string,any>; type Document=Record<string,any>
const docTypes=['الهوية الوطنية / الإقامة','العقد','المؤهل العلمي','العضوية المهنية','شهادة التأمينات','شهادة صحية','رخصة القيادة','مستند آخر']

export default function EmployeePage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''); const [employee,setEmployee]=useState<Employee|null>(null); const [docs,setDocs]=useState<Document[]>([]); const [doc,setDoc]=useState({document_type:docTypes[0],document_name:'',document_number:'',issue_date:'',expiry_date:'',status:'ساري',notes:''}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
 useEffect(()=>{params.then(p=>setId(p.id))},[params])
 useEffect(()=>{if(!id)return;(async()=>{const [{data:e},{data:d}]=await Promise.all([supabase.from('employee_records').select('*').eq('id',id).single(),supabase.from('employee_documents').select('*').eq('employee_id',id).order('created_at',{ascending:false})]);setEmployee(e);setDocs(d||[]);setLoading(false)})()},[id])
 const save=async()=>{if(!employee)return;setSaving(true);setMessage('');const {error}=await supabase.from('employee_records').update(employee).eq('id',id);setMessage(error?`تعذر الحفظ: ${error.message}`:'تم حفظ بيانات الموظف.');setSaving(false)}
 const addDoc=async()=>{if(!doc.document_name)return setMessage('اكتب اسم المستند أولًا.');const {data,error}=await supabase.from('employee_documents').insert({...doc,employee_id:id,issue_date:doc.issue_date||null,expiry_date:doc.expiry_date||null}).select('*').single();if(error)setMessage(`تعذر إضافة المستند: ${error.message}`);else{setDocs([data,...docs]);setDoc({...doc,document_name:'',document_number:'',issue_date:'',expiry_date:'',notes:''});setMessage('تمت إضافة المستند.')}}
 if(loading)return <main className="min-h-screen bg-[#f5f7fa] p-10 text-center" dir="rtl">جاري التحميل...</main>
 if(!employee)return <main className="min-h-screen bg-[#f5f7fa] p-10 text-center" dir="rtl">لم يتم العثور على الموظف.</main>
 const formLinks=[['/forms/leave','طلب إجازة','إنشاء وطباعة طلب إجازة',CalendarDays],['/forms/advance','طلب سلفة','إنشاء وطباعة طلب سلفة مالية',WalletCards],['/forms/clearance','إخلاء طرف','إنشاء وطباعة إخلاء طرف',ClipboardCheck],['/forms/joining/'+id,'مباشرة العمل','فتح نموذج مباشرة العمل',BriefcaseBusiness]] as const
 return <main className="min-h-screen bg-[#f5f7fa]" dir="rtl"><div className="max-w-7xl mx-auto p-5 md:p-8"><header className="flex justify-between items-center mb-7"><div><div className="text-sm text-[#b88618] font-bold">ملف موظف</div><h1 className="text-3xl font-black text-[#09233f]">{employee.full_name}</h1><p className="text-slate-500">{employee.employee_number||'بدون رقم وظيفي'} • {employee.job_title||'—'}</p></div><Link href="/employees" className="flex items-center gap-2 font-bold text-[#09233f]"><ArrowLeft size={18}/> الموظفون</Link></header>
 <section className="mb-5"><div className="flex items-center gap-2 mb-3 font-black text-[#09233f]"><FileText size={20}/> النماذج السريعة</div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{formLinks.map(([href,title,desc,Icon])=><Link key={href} href={href} className="bg-white border rounded-2xl p-4 hover:shadow-md transition"><Icon size={21} className="text-[#b88618]"/><div className="font-black text-[#09233f] mt-2">{title}</div><div className="text-xs text-slate-500 mt-1">{desc}</div></Link>)}</div></section>
 <div className="grid lg:grid-cols-2 gap-5"><section className="card p-6"><div className="flex items-center gap-2 mb-5 font-black text-[#09233f]"><UserRound size={20}/> البيانات الأساسية والوظيفية</div><div className="grid md:grid-cols-2 gap-4">{[['employee_number','الرقم الوظيفي'],['full_name','الاسم الكامل'],['national_id','رقم الهوية / الإقامة'],['phone','الجوال'],['email','البريد الإلكتروني'],['nationality','الجنسية'],['degree','المؤهل'],['specialization','التخصص'],['job_title','المسمى الوظيفي'],['department','الإدارة'],['project_name','المشروع'],['work_location','موقع العمل'],['manager_name','المدير المباشر'],['hire_date','تاريخ المباشرة'],['contract_type','نوع العقد'],['salary','الراتب / الحزمة المالية'],['employment_status','حالة الموظف']].map(([k,l])=><label key={k} className="block"><span className="block font-bold mb-1 text-sm">{l}</span><input type={k==='hire_date'?'date':'text'} value={employee[k]||''} onChange={e=>setEmployee({...employee,[k]:e.target.value})} className="w-full border rounded-xl px-3 py-2.5"/></label>)}</div><label className="block mt-4 font-bold">ملاحظات<textarea value={employee.notes||''} onChange={e=>setEmployee({...employee,notes:e.target.value})} rows={4} className="w-full border rounded-xl px-3 py-2.5 mt-1"/></label><button onClick={save} disabled={saving} className="btn-primary mt-5 rounded-xl px-5 py-3 font-bold inline-flex gap-2 items-center"><Save size={17}/>{saving?'جاري الحفظ...':'حفظ البيانات'}</button></section>
 <section className="card p-6"><div className="flex items-center gap-2 mb-5 font-black text-[#09233f]"><FileText size={20}/> مستندات الموظف</div><div className="grid md:grid-cols-2 gap-3">{[['document_type','نوع المستند'],['document_name','اسم المستند'],['document_number','رقم المستند'],['issue_date','تاريخ الإصدار'],['expiry_date','تاريخ الانتهاء'],['status','الحالة'],['notes','ملاحظات']].map(([k,l])=>k==='document_type'?<label key={k} className="block"><span className="block font-bold mb-1 text-sm">{l}</span><select value={doc[k as keyof typeof doc]} onChange={e=>setDoc({...doc,[k]:e.target.value})} className="w-full border rounded-xl px-3 py-2.5">{docTypes.map(x=><option key={x}>{x}</option>)}</select></label>:<label key={k} className="block"><span className="block font-bold mb-1 text-sm">{l}</span><input type={k.includes('date')?'date':'text'} value={doc[k as keyof typeof doc]} onChange={e=>setDoc({...doc,[k]:e.target.value})} className="w-full border rounded-xl px-3 py-2.5"/></label>)}</div><button onClick={addDoc} className="mt-4 btn-primary rounded-xl px-5 py-3 font-bold">إضافة المستند</button><div className="mt-6 space-y-3">{docs.length===0?<div className="text-slate-500">لا توجد مستندات مسجلة.</div>:docs.map(d=><div key={d.id} className="border rounded-xl p-4"><div className="font-bold text-[#09233f]">{d.document_name}</div><div className="text-sm text-slate-500">{d.document_type} {d.document_number?`• ${d.document_number}`:''}</div><div className="text-xs mt-2">الإصدار: {d.issue_date||'—'} • الانتهاء: {d.expiry_date||'—'} • {d.status}</div></div>)}</div></section></div>{message&&<div className="mt-5 p-4 rounded-xl bg-slate-50">{message}</div>}</div></main>
}
