import {NextRequest,NextResponse} from 'next/server'
const COOKIE='hr2_access_token'
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://pdkdvaisggntdrvpxuur.supabase.co'
const PUBLIC_KEY=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''
const WRITE_ROLES=['admin','hr','interviewer','manager']
async function auth(req:NextRequest){const token=req.cookies.get(COOKIE)?.value,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!token||!key)return null;const ar=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:PUBLIC_KEY,Authorization:`Bearer ${token}`},cache:'no-store'});if(!ar.ok)return null;const user=await ar.json();const ur=await fetch(`${SUPABASE_URL}/rest/v1/app_users?select=role,is_active&user_id=eq.${user.id}&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`},cache:'no-store'});const rows=ur.ok?await ur.json():[];const role=user.email?.toLowerCase()==='hr@albenyah.sa'?'admin':rows[0]?.role;if(!WRITE_ROLES.includes(role)||(role!=='admin'&&rows[0]?.is_active!==true))return null;return key}
const headers=(key:string)=>({apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'})
export async function POST(req:NextRequest){try{const key=await auth(req);if(!key)return NextResponse.json({error:'غير مصرح أو الحساب للقراءة فقط'},{status:401});const b=await req.json();if(b.action==='create'){if(!b.requestId)return NextResponse.json({error:'الطلب الوظيفي مطلوب'},{status:400});const r=await fetch(`${SUPABASE_URL}/rest/v1/candidates`,{method:'POST',headers:{...headers(key),Prefer:'return=representation'},body:JSON.stringify({request_id:b.requestId,full_name:(b.fullName||'مرشح جديد').trim(),phone:(b.phone||'').trim(),status:'جديد'})});if(!r.ok)return NextResponse.json({error:await r.text()},{status:500});return NextResponse.json({candidate:(await r.json())[0]})}
if(b.action==='status'){if(!b.candidateId||!b.status)return NextResponse.json({error:'بيانات الحالة ناقصة'},{status:400});const r=await fetch(`${SUPABASE_URL}/rest/v1/candidates?id=eq.${b.candidateId}`,{method:'PATCH',headers:{...headers(key),Prefer:'return=representation'},body:JSON.stringify({status:b.status,updated_at:new Date().toISOString()})});if(!r.ok)return NextResponse.json({error:await r.text()},{status:500});return NextResponse.json({candidate:(await r.json())[0]})}
if(b.action==='delete'){if(!b.candidateId)return NextResponse.json({error:'معرف المرشح مطلوب'},{status:400});const r=await fetch(`${SUPABASE_URL}/rest/v1/candidates?id=eq.${b.candidateId}`,{method:'DELETE',headers:{...headers(key),Prefer:'return=minimal'}});if(!r.ok)return NextResponse.json({error:await r.text()},{status:500});return NextResponse.json({ok:true})}
return NextResponse.json({error:'عملية غير معروفة'},{status:400})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'تعذر تنفيذ العملية'},{status:500})}}
