import { NextRequest, NextResponse } from 'next/server'
import { getServerAuth, supabaseHeaders, SUPABASE_URL } from '@/lib/server-auth'
import { calculateNitaqat, targetSaudiCount } from '@/lib/nitaqat'

const ROLES=['admin','hr','manager']
const BASE=`${SUPABASE_URL}/rest/v1/`
async function rest(auth:any,path:string,init:RequestInit={}){const r=await fetch(BASE+path,{...init,headers:{...supabaseHeaders(auth),...(init.headers||{})},cache:'no-store'});const text=await r.text();let data:any=[];try{data=text?JSON.parse(text):[]}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.hint||'تعذر تنفيذ الطلب');return data}
async function audit(auth:any,action:string,entity_type:string,entity_id:any,after:any){try{await rest(auth,'nitaqat_audit_log',{method:'POST',body:JSON.stringify({action,entity_type,entity_id:entity_id||null,after_data:after,user_id:auth.user.id})})}catch{}}
async function permission(auth:any,p:string){if(auth.role==='admin')return true;const rows=await rest(auth,`nitaqat_permissions?select=enabled&role=eq.${encodeURIComponent(auth.role)}&permission=eq.${encodeURIComponent(p)}&limit=1`);return rows[0]?.enabled===true}
function isSaudi(v:any){return ['سعودي','سعودية','Saudi','Saudi Arabian','Saudi Arabia'].includes(String(v||'').trim())}
async function settings(auth:any){return (await rest(auth,'nitaqat_company_settings?select=*&id=eq.true&limit=1'))[0]||{}}
async function employees(auth:any,onlyActive=true){const s=await settings(auth);const rows=await rest(auth,'employee_records?select=id,employee_number,full_name,national_id,nationality,job_title,department,project_name,contract_type,employment_status,residency_status,hire_date,gosi_status,gosi_subscriber_wage&order=full_name');const active=new Set(Array.isArray(s.active_statuses)?s.active_statuses:[]);return rows.map((e:any)=>{const activeFlag=!onlyActive||active.has(e.employment_status);const sponsored=e.residency_status==='على الكفالة';const nationalityKnown=!!e.nationality;const saudi=isSaudi(e.nationality);const included=activeFlag&&sponsored&&nationalityKnown;const exclusion_reason=!sponsored?'الموظف خارج كفالة المنشأة ولا يدخل في حاسبة نطاقات':!activeFlag?'حالة الموظف غير مدرجة ضمن الحالات النشطة المحددة في بيانات نطاقات':!nationalityKnown?'الجنسية غير متوفرة':'';return {...e,is_active_for_nitaqat:activeFlag,is_on_company_sponsorship:sponsored,is_saudi:saudi,nationality_known:nationalityKnown,included,exclusion_reason,contract_verification:'غير معروف',special_case:'غير محدد'}})}
async function ruleFor(auth:any,activity:string,year:number){const rows=await rest(auth,`nitaqat_rules?select=*&activity_group=eq.${encodeURIComponent(activity)}&active=eq.true&effective_from=lte.${year}-12-31&or=(effective_to.is.null,effective_to.gte.${year}-01-01)&limit=1`);return rows[0]||null}
export async function GET(req:NextRequest){try{const auth=await getServerAuth(req,ROLES);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});const url=new URL(req.url),action=url.searchParams.get('action')||'summary',year=Number(url.searchParams.get('year')||new Date().getFullYear());if(!(await permission(auth,'view')))return NextResponse.json({error:'لا تملك صلاحية عرض نطاقات'},{status:403})
 if(action==='settings')return NextResponse.json({settings:await settings(auth)})
 if(action==='rules'){return NextResponse.json({rules:await rest(auth,'nitaqat_rules?select=*&order=activity_group'),cases:await rest(auth,'nitaqat_special_cases?select=*&order=name')})}
 if(action==='special_cases')return NextResponse.json({cases:await rest(auth,'nitaqat_special_cases?select=*&order=name')})
 if(action==='employees'){const rows=await employees(auth,true);return NextResponse.json({employees:rows})}
 if(action==='history')return NextResponse.json({rows:await rest(auth,'nitaqat_history?select=*&order=snapshot_date.desc,created_at.desc'),audit:await rest(auth,'nitaqat_audit_log?select=*&order=created_at.desc')})
 if(action==='scenarios')return NextResponse.json({rows:await rest(auth,'nitaqat_scenarios?select=*&order=created_at.desc')})
 if(action==='official')return NextResponse.json({rows:await rest(auth,'nitaqat_official_snapshots?select=*&order=checked_at.desc,created_at.desc')})
 const es=await employees(auth,true);const included=es.filter((e:any)=>e.included);const saudi=included.filter((e:any)=>e.is_saudi).length;const nonSaudi=included.length-saudi;const total=included.length;const s=await settings(auth);const activity=s.main_activity||'';const rule=activity?await ruleFor(auth,activity,year):null;const sc=(await rest(auth,'nitaqat_special_cases?select=parameters&code=eq.small_establishment&active=eq.true&limit=1'))[0]?.parameters||null;const result=calculateNitaqat({total,saudi,nonSaudi,year,rule,smallCase:sc});const official=(await rest(auth,'nitaqat_official_snapshots?select=*&order=checked_at.desc,created_at.desc&limit=1'))[0]||null;const missing=es.filter((e:any)=>!e.nationality_known||!e.is_active_for_nitaqat||!e.is_on_company_sponsorship);return NextResponse.json({settings:s,summary:{...result,total,saudi,nonSaudi,last_updated:new Date().toISOString(),official_band:official?.official_band||null,missing_count:missing.length},employees:included,missing})
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'تعذر تحميل بيانات نطاقات'},{status:500})}}
export async function POST(req:NextRequest){try{const auth=await getServerAuth(req,ROLES);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});const b=await req.json();const action=b.action
 if(action==='calculate'){if(!(await permission(auth,'calculate')))return NextResponse.json({error:'لا تملك صلاحية الحساب'},{status:403});const year=Number(b.year||new Date().getFullYear());const rule=b.activity?await ruleFor(auth,b.activity,year):null;const sc=(await rest(auth,'nitaqat_special_cases?select=parameters&code=eq.small_establishment&active=eq.true&limit=1'))[0]?.parameters||null;const result=calculateNitaqat({total:Number(b.total||0),saudi:Number(b.saudi||0),nonSaudi:Number(b.nonSaudi),year,rule,smallCase:sc});let required:any=null;if(result.thresholds&&b.targetBand&&result.thresholds[b.targetBand]!=null)required=targetSaudiCount(Number(b.total||0),result.thresholds[b.targetBand]);return NextResponse.json({result,required_saudi_for_target:required})}
 if(action==='save_settings'){if(!(await permission(auth,'edit_company')))return NextResponse.json({error:'لا تملك صلاحية تعديل بيانات المنشأة'},{status:403});const row={id:true,...b.settings,updated_by:auth.user.id,updated_at:new Date().toISOString()};delete row.action;const out=(await rest(auth,'nitaqat_company_settings?id=eq.true',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0]||row;await audit(auth,'update','company_settings',null,out);return NextResponse.json({settings:out})}
 if(action==='save_rule'){if(!(await permission(auth,'manage_rules')))return NextResponse.json({error:'إدارة القواعد للمستخدمين المخولين فقط'},{status:403});const row={...b.rule,updated_at:new Date().toISOString()};const id=row.id;delete row.id;const out=(await rest(auth,id?`nitaqat_rules?id=eq.${id}`:'nitaqat_rules',{method:id?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0];await audit(auth,id?'update':'create','rule',out?.id||id,out);return NextResponse.json({rule:out})}
 if(action==='save_case'){if(!(await permission(auth,'manage_special_cases')))return NextResponse.json({error:'إدارة الحالات الخاصة للمستخدمين المخولين فقط'},{status:403});const row={...b.case,updated_at:new Date().toISOString()};delete row.id;const out=(await rest(auth,'nitaqat_special_cases',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0];await audit(auth,'create','special_case',out?.id,out);return NextResponse.json({case:out})}
 if(action==='toggle_case'){if(!(await permission(auth,'manage_special_cases')))return NextResponse.json({error:'إدارة الحالات الخاصة للمستخدمين المخولين فقط'},{status:403});const out=(await rest(auth,`nitaqat_special_cases?id=eq.${b.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({active:b.active,updated_at:new Date().toISOString()})}))[0];await audit(auth,'toggle','special_case',b.id,out);return NextResponse.json({case:out})}
 if(action==='toggle_rule'){if(!(await permission(auth,'manage_rules')))return NextResponse.json({error:'إدارة القواعد للمستخدمين المخولين فقط'},{status:403});const out=(await rest(auth,`nitaqat_rules?id=eq.${b.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({active:b.active,updated_at:new Date().toISOString()})}))[0];await audit(auth,'toggle','rule',b.id,out);return NextResponse.json({rule:out})}
 if(action==='save_scenario'){if(!(await permission(auth,'calculate')))return NextResponse.json({error:'لا تملك صلاحية الحفظ'},{status:403});const year=Number(b.year||new Date().getFullYear());const rule=b.activity?await ruleFor(auth,b.activity,year):null;const result=calculateNitaqat({total:Number(b.saudi||0)+Number(b.nonSaudi||0),saudi:Number(b.saudi||0),nonSaudi:Number(b.nonSaudi||0),year,rule});const row={name:b.name||'سيناريو توطين',activity_group:b.activity||null,sub_activity:b.sub_activity||null,base_saudi:Number(b.base_saudi||0),base_non_saudi:Number(b.base_non_saudi||0),simulated_saudi:Number(b.saudi||0),simulated_non_saudi:Number(b.nonSaudi||0),result,created_by:auth.user.id};const out=(await rest(auth,'nitaqat_scenarios',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0];await audit(auth,'create','scenario',out?.id,out);return NextResponse.json({scenario:out})}
 if(action==='save_history'){if(!(await permission(auth,'reports')))return NextResponse.json({error:'لا تملك صلاحية حفظ السجل'},{status:403});const row={...b,created_by:auth.user.id,source:b.source||'بيانات HR2 + قواعد نطاقات المحفوظة بالنظام'};delete row.action;const out=(await rest(auth,'nitaqat_history',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0];await audit(auth,'create','history',out?.id,out);return NextResponse.json({row:out})}
 if(action==='save_official'){if(!(await permission(auth,'official_snapshot')))return NextResponse.json({error:'لا تملك صلاحية تسجيل النطاق الرسمي'},{status:403});const row={official_band:b.official_band,checked_at:b.checked_at||new Date().toISOString().slice(0,10),source:b.source||'قوى',notes:b.notes||null,created_by:auth.user.id};const out=(await rest(auth,'nitaqat_official_snapshots',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0];await audit(auth,'create','official_snapshot',out?.id,out);return NextResponse.json({row:out})}
 return NextResponse.json({error:'عملية غير معروفة'},{status:400})
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'تعذر تنفيذ العملية'},{status:500})}}
