'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {ArrowRight,RefreshCw,Search,MapPin,UserPlus} from 'lucide-react'
type Data={employees:any[];mappings:any[];locations:any[];employeeLocations:any[]}
export default function AttendanceUsersPage(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[employeeId,setEmployeeId]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[query,setQuery]=useState(''),[locationIds,setLocationIds]=useState<string[]>([]),[message,setMessage]=useState<{ok:boolean;text:string}|null>(null),[editId,setEditId]=useState<string|null>(null)
 async function load(){setLoading(true);const r=await fetch('/api/attendance/users',{cache:'no-store'});if(r.ok)setData(await r.json());else setMessage({ok:false,text:'تعذر تحميل البيانات'});setLoading(false)}
 useEffect(()=>{load()},[])
 const mapped=new Set((data?.mappings||[]).filter(x=>x.is_active).map(x=>x.employee_id))
 const employees=useMemo(()=> (data?.employees||[]).filter(e=>!mapped.has(e.id)&&(!query||[e.full_name,e.employee_number,e.job_title,e.department].filter(Boolean).some((v:any)=>String(v).toLowerCase().includes(query.toLowerCase())))),[data,query])
 const toggle=(id:string)=>setLocationIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])
 const editLocations=(m:any)=>{setEditId(m.id);setEmployeeId(m.employee_id);setLocationIds((data?.employeeLocations||[]).filter(x=>x.employee_id===m.employee_id).map(x=>x.location_id));window.scrollTo({top:0,behavior:'smooth'})}
 async function saveLocations(){const r=await fetch('/api/attendance/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'set_locations',employee_id:employeeId,location_ids:locationIds})});const b=await r.json().catch(()=>({}));if(!r.ok){setMessage({ok:false,text:b.error||'تعذر تحديث المواقع'});return}setMessage({ok:true,text:'تم تحديث مواقع الحضور المعتمدة'});setEditId(null);setEmployeeId('');setLocationIds([]);await load()}
 async function create(){setMessage(null);if(!employeeId||!username||!/^[a-z0-9._-]{3,40}$/.test(username)||password.length<8||password!==confirm||!locationIds.length){setMessage({ok:false,text:'اختر الموظف والموقع وأدخل اسم المستخدم وكلمة المرور بشكل صحيح'});return}const r=await fetch('/api/attendance/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create_account',employee_id:employeeId,username,password,location_ids:locationIds})});const b=await r.json().catch(()=>({}));if(!r.ok){setMessage({ok:false,text:b.error||'تعذر إنشاء الحساب'});return}setMessage({ok:true,text:'تم إنشاء حساب التطبيق وربطه بالموظف وتحديد مواقع الحضور بنجاح'});setEmployeeId('');setUsername('');setPassword('');setConfirm('');setLocationIds([]);await load()}
 return <main dir="rtl" className="p-5 md:p-8 space-y-6">
 <div className="flex items-center justify-between gap-4"><div><div className="text-xs font-black tracking-widest text-[#b88618]">HR2 / ATTENDANCE</div><h1 className="mt-1 text-3xl font-black text-[#09233f]">{editId?'تعديل مواقع الحضور':'إنشاء حسابات تطبيق الحضور'}</h1><p className="mt-1 text-sm text-slate-500">{editId?'تعديل المواقع المعتمدة للموظف.':'إنشاء حساب مستقل للتطبيق مع تحديد مواقع الحضور والانصراف المعتمدة.'}</p></div><Link href="/attendance" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-extrabold text-[#09233f]"><ArrowRight size={17}/> الحضور والانصراف</Link></div>
 {message&&<div className={'rounded-xl p-3 text-sm font-bold '+(message.ok?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700')}>{message.text}</div>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-5 flex items-center gap-2 text-lg font-black text-[#09233f]">{editId?<MapPin size={19}/>:<UserPlus size={19}/>} {editId?'تعديل المواقع المعتمدة':'بيانات حساب التطبيق'}</h2>
 <div className="grid gap-4 lg:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">الموظف</label>{!editId&&<div className="relative mb-2"><Search className="absolute right-3 top-3 text-slate-400" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالاسم أو الرقم الوظيفي" className="w-full rounded-xl border border-slate-200 py-2.5 pr-10 pl-3 text-sm"/></div>}<select disabled={!!editId} value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option value="">اختر الموظف</option>{(editId?data?.employees||[]:employees).map(e=><option key={e.id} value={e.id}>{e.full_name} — {e.employee_number||'بدون رقم'}{e.job_title?' — '+e.job_title:''}</option>)}</select></div>
 {!editId&&<div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">اسم مستخدم التطبيق</label><input value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="مثال: ahmed.123" className="w-full rounded-xl border border-slate-200 p-3 text-sm" dir="ltr"/></div><div><label className="mb-2 block text-sm font-bold">كلمة المرور</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="8 أحرف على الأقل" className="w-full rounded-xl border border-slate-200 p-3 text-sm" dir="ltr"/></div><div><label className="mb-2 block text-sm font-bold">تأكيد كلمة المرور</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="w-full rounded-xl border border-slate-200 p-3 text-sm" dir="ltr"/></div></div>}</div>
 <div className="mt-6 border-t pt-5"><h3 className="mb-3 flex items-center gap-2 font-black text-[#09233f]"><MapPin size={18}/> مواقع الحضور والانصراف المعتمدة</h3><p className="mb-3 text-xs text-slate-500">يمكن اختيار أكثر من موقع. التحقق يتم من السيرفر عند التسجيل.</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{(data?.locations||[]).map(l=><label key={l.id} className={'cursor-pointer rounded-xl border p-4 '+(locationIds.includes(l.id)?'border-[#b88618] bg-amber-50':'border-slate-200')}><div className="flex items-start gap-3"><input type="checkbox" checked={locationIds.includes(l.id)} onChange={()=>toggle(l.id)} className="mt-1"/><div><div className="font-black">{l.name}</div><div className="mt-1 text-xs text-slate-500">نطاق {l.radius_meters||0} متر</div></div></div></label>)}</div></div>
 <div className="mt-6 flex justify-end gap-2">{editId&&<button onClick={()=>{setEditId(null);setEmployeeId('');setLocationIds([])}} className="rounded-xl border px-6 py-3 text-sm font-black">إلغاء</button>}<button disabled={loading} onClick={editId?saveLocations:create} className="rounded-xl bg-[#10233f] px-8 py-3 text-sm font-black text-white disabled:opacity-40">{editId?'حفظ المواقع':'إنشاء الحساب وربط المواقع'}</button></div>
 </section>
 <section className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="flex items-center justify-between border-b p-4"><h2 className="text-lg font-black text-[#09233f]">الحسابات الحالية</h2><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold"><RefreshCw size={15}/> تحديث</button></div>{loading?<div className="p-8 text-center text-slate-500">جارٍ التحميل...</div>:<div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr className="border-b bg-slate-50 text-slate-500"><th className="p-3">المستخدم</th><th className="p-3">الموظف</th><th className="p-3">المواقع المعتمدة</th><th className="p-3">الحالة</th><th className="p-3">الإجراءات</th></tr></thead><tbody>{(data?.mappings||[]).map(m=>{const e=data?.employees.find(x=>x.id===m.employee_id);const ls=(data?.employeeLocations||[]).filter(x=>x.employee_id===m.employee_id).map(x=>data?.locations.find(l=>l.id===x.location_id)?.name).filter(Boolean);return <tr key={m.id} className="border-b last:border-0"><td className="p-3 font-bold" dir="ltr">{m.app_username||'—'}</td><td className="p-3">{e?.full_name||'—'}<div className="text-xs text-slate-400">{e?.employee_number||'—'}</div></td><td className="p-3">{ls.length?ls.join('، '):'غير محدد'}</td><td className="p-3">{m.is_active?'نشط':'موقوف'}</td><td className="p-3"><button onClick={()=>editLocations(m)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><MapPin size={14}/> تعديل المواقع</button></td></tr>})}</tbody></table></div>}</section>
 </main>
}