'use client'
import {useEffect,useMemo,useState} from 'react'
import dynamic from 'next/dynamic'
import Link from 'next/link'
import {ArrowRight,RefreshCw,Search,MapPin,UserPlus,Power,KeyRound,Trash2} from 'lucide-react'
const AttendanceMap=dynamic(()=>import('@/components/AttendanceMap'),{ssr:false})
type Data={employees:any[];mappings:any[];locations:any[];employeeLocations:any[]}
export default function AttendanceUsersPage(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[employeeId,setEmployeeId]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[query,setQuery]=useState(''),[lat,setLat]=useState<number|null>(null),[lng,setLng]=useState<number|null>(null),[radius,setRadius]=useState(200),[locationName,setLocationName]=useState(''),[editId,setEditId]=useState<string|null>(null),[message,setMessage]=useState<{ok:boolean;text:string}|null>(null)
 async function load(){setLoading(true);const r=await fetch('/api/attendance/users',{cache:'no-store'});if(r.ok)setData(await r.json());else setMessage({ok:false,text:'تعذر تحميل البيانات'});setLoading(false)}
 useEffect(()=>{load()},[])
 const mapped=new Set((data?.mappings||[]).filter(x=>x.is_active).map(x=>x.employee_id))
 const employees=useMemo(()=> (data?.employees||[]).filter(e=>!mapped.has(e.id)&&(!query||[e.full_name,e.employee_number,e.job_title,e.department].filter(Boolean).some((v:any)=>String(v).toLowerCase().includes(query.toLowerCase())))),[data,query])
 const currentLocation=(id:string)=>{const link=data?.employeeLocations.find(x=>x.employee_id===id&&x.is_active);return link?data?.locations.find(x=>x.id===link.location_id):null}
 const reset=()=>{setEditId(null);setEmployeeId('');setUsername('');setPassword('');setConfirm('');setLat(null);setLng(null);setRadius(200);setLocationName('')}
 const edit=(m:any)=>{const e=currentLocation(m.employee_id);setEditId(m.id);setEmployeeId(m.employee_id);setLat(e?.latitude??null);setLng(e?.longitude??null);setRadius(Number(e?.radius_meters||200));setLocationName(e?.name||'');window.scrollTo({top:0,behavior:'smooth'})}
 async function action(payload:any,okText:string){const r=await fetch('/api/attendance/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({}));if(!r.ok){setMessage({ok:false,text:b.error||'تعذر تنفيذ العملية'});return false}setMessage({ok:true,text:okText});await load();return true}
 async function create(){if(!employeeId||!username||!/^[a-z0-9._-]{3,40}$/.test(username)||password.length<8||password!==confirm||lat===null||lng===null){setMessage({ok:false,text:'اختر الموظف وحدد الموقع على الخريطة وأدخل بيانات الحساب بشكل صحيح'});return}if(await action({action:'create_account',employee_id:employeeId,username,password,location:{latitude:lat,longitude:lng,radius_meters:radius,name:locationName}},'تم إنشاء الحساب وتحديد موقع الحضور بنجاح'))reset()}
 async function updateLocation(){if(lat===null||lng===null)return setMessage({ok:false,text:'حدد الموقع على الخريطة أولاً'});if(await action({action:'update_location',employee_id:employeeId,latitude:lat,longitude:lng,radius_meters:radius,name:locationName},'تم تحديث موقع الحضور'))reset()}
 async function toggle(m:any){await action({action:'set_status',employee_id:m.employee_id,is_active:!m.is_active},m.is_active?'تم تعطيل الحساب':'تم تفعيل الحساب')}
 async function passwordChange(m:any){const p=window.prompt('أدخل كلمة المرور الجديدة (8 أحرف على الأقل):');if(p)await action({action:'change_password',employee_id:m.employee_id,password:p},'تم تغيير كلمة المرور وتفعيل الحساب')}
 async function remove(m:any){if(window.confirm('سيتم إيقاف حساب التطبيق وحذف اسم المستخدم منه مع الاحتفاظ بسجل الحضور. هل تريد المتابعة؟'))await action({action:'delete_account',employee_id:m.employee_id},'تم حذف صلاحية حساب التطبيق')}
 return <main dir="rtl" className="p-5 md:p-8 space-y-6">
 <div className="flex items-center justify-between gap-4"><div><div className="text-xs font-black tracking-widest text-[#b88618]">HR2 / ATTENDANCE</div><h1 className="mt-1 text-3xl font-black text-[#09233f]">حسابات تطبيق الحضور</h1><p className="mt-1 text-sm text-slate-500">إنشاء الحساب وتحديد موقع الموظف مباشرة من الخريطة وإدارة الحسابات الحالية.</p></div><Link href="/attendance" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-extrabold text-[#09233f]"><ArrowRight size={17}/> الحضور والانصراف</Link></div>
 {message&&<div className={'rounded-xl p-3 text-sm font-bold '+(message.ok?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700')}>{message.text}</div>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
 <h2 className="mb-5 flex items-center gap-2 text-lg font-black text-[#09233f]">{editId?<MapPin size={19}/>:<UserPlus size={19}/>} {editId?'تعديل حساب وموقع الموظف':'إنشاء حساب تطبيق جديد'}</h2>
 <div className="grid gap-4 lg:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">الموظف</label>{!editId&&<div className="relative mb-2"><Search className="absolute right-3 top-3 text-slate-400" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالاسم أو الرقم الوظيفي" className="w-full rounded-xl border border-slate-200 py-2.5 pr-10 pl-3 text-sm"/></div>}<select disabled={!!editId} value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white p-3 text-sm"><option value="">اختر الموظف</option>{(editId?data?.employees||[]:employees).map(e=><option key={e.id} value={e.id}>{e.full_name} — {e.employee_number||'بدون رقم'}{e.job_title?' — '+e.job_title:''}</option>)}</select></div>
 {!editId&&<div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">اسم المستخدم</label><input value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="مثال: ahmed.123" className="w-full rounded-xl border border-slate-200 p-3 text-sm" dir="ltr"/></div><div><label className="mb-2 block text-sm font-bold">كلمة المرور</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="8 أحرف على الأقل" className="w-full rounded-xl border border-slate-200 p-3 text-sm" dir="ltr"/></div><div><label className="mb-2 block text-sm font-bold">تأكيد كلمة المرور</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="w-full rounded-xl border border-slate-200 p-3 text-sm" dir="ltr"/></div></div>}</div>
 <div className="mt-6 border-t pt-5"><div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 font-black text-[#09233f]"><MapPin size={18}/> تحديد الموقع من الخريطة</h3><p className="mt-1 text-xs text-slate-500">اضغط على الخريطة أو اسحب العلامة إلى الموقع المطلوب.</p></div><div className="flex items-center gap-2"><input value={locationName} onChange={e=>setLocationName(e.target.value)} placeholder="اسم الموقع" className="w-44 rounded-xl border p-2.5 text-sm"/><input type="number" min={20} max={5000} value={radius} onChange={e=>setRadius(Number(e.target.value)||200)} className="w-28 rounded-xl border p-2.5 text-sm" title="نطاق السماح بالمتر"/><span className="text-xs font-bold text-slate-500">متر</span></div></div>
 <AttendanceMap lat={lat} lng={lng} radius={radius} onChange={(a,b)=>{setLat(a);setLng(b)}}/><div className="mt-3 flex flex-wrap gap-3 text-xs font-bold text-slate-600"><span>خط العرض: {lat?.toFixed(6)||'—'}</span><span>خط الطول: {lng?.toFixed(6)||'—'}</span><span>نطاق السماح: {radius} متر</span></div></div>
 <div className="mt-6 flex justify-end gap-2">{editId&&<button onClick={reset} className="rounded-xl border px-6 py-3 text-sm font-black">إلغاء</button>}<button onClick={editId?updateLocation:create} disabled={loading} className="rounded-xl bg-[#10233f] px-8 py-3 text-sm font-black text-white disabled:opacity-40">{editId?'حفظ الموقع':'إنشاء الحساب وحفظ الموقع'}</button></div>
 </section>
 <section className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div className="flex items-center justify-between border-b p-4"><h2 className="text-lg font-black text-[#09233f]">الحسابات الحالية</h2><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold"><RefreshCw size={15}/> تحديث</button></div>{loading?<div className="p-8 text-center text-slate-500">جارٍ التحميل...</div>:<div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr className="border-b bg-slate-50 text-slate-500"><th className="p-3">المستخدم</th><th className="p-3">الموظف</th><th className="p-3">الموقع</th><th className="p-3">الحالة</th><th className="p-3">الإجراءات</th></tr></thead><tbody>{(data?.mappings||[]).map(m=>{const e=data?.employees.find(x=>x.id===m.employee_id),l=currentLocation(m.employee_id);return <tr key={m.id} className="border-b last:border-0"><td className="p-3 font-bold" dir="ltr">{m.app_username||'—'}</td><td className="p-3">{e?.full_name||'—'}<div className="text-xs text-slate-400">{e?.employee_number||'—'}</div></td><td className="p-3">{l?.name||'غير محدد'}<div className="text-xs text-slate-400">{l?.radius_meters||0} متر</div></td><td className="p-3"><span className={m.is_active?'text-emerald-700':'text-red-600'}>{m.is_active?'نشط':'موقوف'}</span></td><td className="p-3"><div className="flex flex-wrap gap-2"><button onClick={()=>edit(m)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><MapPin size={14}/> تعديل</button><button onClick={()=>toggle(m)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><Power size={14}/> {m.is_active?'تعطيل':'تفعيل'}</button><button onClick={()=>passwordChange(m)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><KeyRound size={14}/> كلمة المرور</button><button onClick={()=>remove(m)} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-600"><Trash2 size={14}/> حذف</button></div></td></tr>})}</tbody></table></div>}</section>
 </main>
}