'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {FileCheck2,Search,RefreshCw,ChevronLeft,ExternalLink,Link2,Copy,CheckCircle2} from 'lucide-react'

const labels:any={pending_employee:'بانتظار اعتماد الموظف',pending_finance:'بانتظار اعتماد المالية',pending_hr:'بانتظار اعتماد الموارد البشرية',pending_project_manager:'بانتظار اعتماد مدير المشاريع',pending_general_manager:'بانتظار اعتماد المدير العام',completed:'مكتملة ومعتمدة',returned:'تحتاج إلى تعديل',needs_revision:'تحتاج إلى تعديل',rejected:'مرفوضة',draft:'مسودة',cancelled:'ملغاة',not_started:'لم تبدأ'}
const badge=(s:string)=>s==='completed'?'bg-emerald-50 text-emerald-700':s==='rejected'?'bg-red-50 text-red-700':s==='returned'||s==='needs_revision'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-700'
export default function FinancialClearances(){
 const [rows,setRows]=useState<any[]>([]),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[company,setCompany]=useState(''),[department,setDepartment]=useState(''),[createdDate,setCreatedDate]=useState(''),[finalDate,setFinalDate]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<any|null>(null),[copied,setCopied]=useState('')
 const load=async()=>{setLoading(true);const q=new URLSearchParams();if(search)q.set('search',search);if(status)q.set('status',status);const r=await fetch('/api/financial-clearances?'+q,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d?.error||'تعذر تحميل المخالصات');else setRows(d.clearances||[]);setLoading(false)}
 useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t)},[search,status])
 const filtered=useMemo(()=>rows.filter(x=>(!company||x.employee?.employee_companies?.name===company)&&(!department||x.employee?.department===department)&&(!createdDate||String(x.created_at||'').slice(0,10)===createdDate)&&(!finalDate||String(x.final_approved_at||'').slice(0,10)===finalDate)),[rows,company,department,createdDate,finalDate])
 const companies=useMemo(()=>Array.from(new Set(rows.map(x=>x.employee?.employee_companies?.name).filter(Boolean))),[rows]); const departments=useMemo(()=>Array.from(new Set(rows.map(x=>x.employee?.department).filter(Boolean))),[rows]);
 const counts=useMemo(()=>({all:filtered.length,completed:filtered.filter(x=>x.status==='completed').length,pending:filtered.filter(x=>x.status!=='completed'&&x.status!=='cancelled').length}),[filtered])
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 md:p-7"><div className="mx-auto max-w-[1500px]">
  <header className="mb-6 rounded-2xl border bg-white p-5 shadow-sm md:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="text-xs font-black tracking-[.15em] text-[#b88618]">FINAL SETTLEMENT</div><h1 className="mt-1 text-2xl font-black text-[#09233f] md:text-3xl">المخالصات المالية</h1><p className="mt-2 text-sm text-slate-500">المخالصة المالية والإدارية النهائية وإبراء الذمة المرتبطة بإخلاء الطرف المكتمل.</p></div><Link href="/forms/clearance/records" className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 font-black text-[#09233f]"><ChevronLeft size={17}/> سجل إخلاء الطرف</Link></div></header>
  <div className="mb-5 grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-4"><div className="text-xs font-bold text-slate-500">إجمالي المخالصات</div><div className="mt-1 text-2xl font-black text-[#09233f]">{counts.all}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xs font-bold text-slate-500">قيد الاعتماد</div><div className="mt-1 text-2xl font-black text-amber-600">{counts.pending}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xs font-bold text-slate-500">مكتملة نهائيًا</div><div className="mt-1 text-2xl font-black text-emerald-600">{counts.completed}</div></div></div>
  <section className="rounded-2xl border bg-white shadow-sm overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 lg:flex-row"><div className="relative flex-1"><Search className="absolute right-3 top-3 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالاسم أو الرقم الوظيفي أو الهوية/الإقامة" className="w-full rounded-xl border py-2.5 pr-10 pl-3 outline-none focus:border-[#b88618]"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-3 py-2.5 font-bold"><option value="">كل الحالات</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select><button onClick={()=>void load()} className="rounded-xl bg-[#09233f] px-4 text-white"><RefreshCw size={17}/></button></div>
  {error&&<div className="m-4 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</div>}
  <div>{loading ? (<div className="p-12 text-center text-slate-500">جارٍ التحميل...</div>) : rows.length===0 ? (<div className="p-12 text-center text-slate-500">لا توجد مخالصات مالية.</div>) : (<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-50 text-xs font-black text-slate-600"><tr><th className="p-3 text-right">الموظف</th><th className="p-3 text-right">الرقم الوظيفي</th><th className="p-3 text-right">الشركة</th><th className="p-3 text-right">المسمى الوظيفي</th><th className="p-3 text-right">القسم</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">آخر تحديث</th><th className="p-3 text-right">الروابط</th><th className="p-3 text-right">الإجراءات</th></tr></thead><tbody className="divide-y">{filtered.map((x:any)=>(<tr key={x.id} className="hover:bg-slate-50"><td className="p-3 font-bold">{x.employee?.full_name||"—"}</td><td className="p-3">{x.employee?.employee_number||"—"}</td><td className="p-3">{x.employee?.employee_companies?.name||"—"}</td><td className="p-3">{x.employee?.job_title||"—"}</td><td className="p-3">{x.employee?.department||"—"}</td><td className="p-3"><span className={"rounded-full px-2.5 py-1 text-xs font-black "+badge(x.status)}>{labels[x.status]||x.status}</span></td><td className="p-3 text-xs text-slate-500">{x.updated_at?new Date(x.updated_at).toLocaleString("ar-SA"):(x.created_at?new Date(x.created_at).toLocaleString("ar-SA"):"—")}</td><td className="p-3"><button onClick={()=>setSelected(x)} className="inline-flex items-center gap-1.5 rounded-lg border bg-white px-3 py-2 text-xs font-black text-[#09233f]"><Link2 size={14}/> الروابط ({(x.links||[]).length})</button></td><td className="p-3"><Link href={"/financial-clearances/"+x.id} className="inline-flex items-center gap-1.5 rounded-lg bg-[#09233f] px-3 py-2 text-xs font-black text-white"><FileCheck2 size={14}/> فتح الملف</Link></td></tr>))}</tbody></table></div>)}</div>
  </section>{selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-0 md:items-center md:p-6" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="max-h-[90vh] w-full max-w-3xl overflow-hidden rounded-t-2xl bg-white shadow-2xl md:rounded-2xl"><header className="flex items-start justify-between bg-[#09233f] px-5 py-4 text-white"><div><div className="text-xs font-bold text-[#e2bd62]">روابط المخالصة المالية</div><h2 className="mt-1 text-lg font-black">{selected.employee?.full_name||'غير محدد'}</h2><p className="mt-1 text-xs text-slate-300">{selected.employee?.employee_number||'بدون رقم'} · {selected.employee?.job_title||'—'}</p></div><button onClick={()=>setSelected(null)} className="rounded-lg px-3 py-2 text-white">×</button></header><div className="max-h-[65vh] overflow-y-auto p-4 space-y-2">{(selected.links||[]).map((l:any)=>{const url=(typeof window!=='undefined'?window.location.origin:'')+'/financial-clearances/public/'+l.token;return <div key={l.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><b>{({employee:'الموظف',finance:'الإدارة المالية',hr:'الموارد البشرية',project_manager:'مدير المشاريع',general_manager:'المدير العام'} as any)[l.stage]||l.stage}</b><div className="text-xs text-slate-500">{l.status==='active'?'نشط':'مستخدم'}</div></div><div className="flex gap-2"><a href={url} target="_blank" rel="noopener noreferrer" className="inline-flex h-9 w-9 items-center justify-center rounded-lg bg-[#09233f] text-white"><ExternalLink size={15}/></a><button onClick={()=>{navigator.clipboard?.writeText(url);setCopied(l.id);setTimeout(()=>setCopied(''),1500)}} className="inline-flex h-9 w-9 items-center justify-center rounded-lg border">{copied===l.id?<CheckCircle2 size={15} className="text-emerald-600"/>:<Copy size={15}/>}</button></div></div>})}</div><footer className="border-t bg-slate-50 p-3 text-left"><button onClick={()=>setSelected(null)} className="rounded-lg border bg-white px-4 py-2 font-bold">إغلاق</button></footer></section></div>}
 </div></main>
}
