'use client'

import { FormEvent, useEffect, useState } from 'react'
import { Eye, EyeOff, KeyRound, ShieldCheck, UserPlus, Users } from 'lucide-react'

type Profile = { user_id: string; display_name: string; email: string; role: string; is_active: boolean; created_at: string; last_sign_in_at?: string | null }
const roleLabels: Record<string,string> = { admin: 'مدير النظام', hr: 'الموارد البشرية', interviewer: 'مقيم / مقابلات', manager: 'مدير' }

export default function UsersPage() {
  const [profiles, setProfiles] = useState<Profile[]>([]), [showModal, setShowModal] = useState(false), [showPassword, setShowPassword] = useState(false)
  const [loading, setLoading] = useState(false), [pageLoading, setPageLoading] = useState(true), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const [form, setForm] = useState({ display_name: '', email: '', password: '', role: 'hr' })
  async function load() { setPageLoading(true); try { const r=await fetch('/api/users/list',{cache:'no-store'}); const d=await r.json(); if(!r.ok) throw new Error(d.error||'تعذر تحميل المستخدمين.'); setProfiles(d.users||[]) } catch(e) { setError(e instanceof Error?e.message:'تعذر تحميل المستخدمين.') } finally { setPageLoading(false) } }
  useEffect(()=>{load()},[])
  async function submit(e:FormEvent){e.preventDefault();setError('');setSuccess('');setLoading(true);const r=await fetch('/api/users/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setError(d.error||'تعذر إنشاء المستخدم.');setLoading(false);return}setSuccess(`تم إنشاء المستخدم ${form.display_name} بنجاح وتم حفظ صلاحية ${roleLabels[form.role]}.`);setForm({display_name:'',email:'',password:'',role:'hr'});setShowModal(false);await load();setLoading(false)}
  return <main dir="rtl" className="min-h-screen bg-[#f5f7fa]">
    <header className="bg-[#09233f] text-white px-6 py-6 shadow-sm"><div className="max-w-6xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="text-[#d4a72c] font-bold text-sm">إدارة النظام</div><h1 className="text-2xl font-black mt-1">المستخدمون والصلاحيات</h1><p className="text-white/60 text-sm mt-1">إضافة المستخدمين وإدارة أدوار الوصول للنظام.</p></div><button onClick={()=>{setShowModal(true);setError('');setSuccess('')}} className="bg-[#b88618] hover:bg-[#d4a72c] rounded-xl px-5 py-3 font-black flex items-center justify-center gap-2"><UserPlus size={19}/> إضافة مستخدم</button></div></header>
    <div className="max-w-6xl mx-auto p-6 md:p-10">{error&&<div className="mb-5 rounded-2xl border border-red-200 bg-red-50 text-red-700 p-4 font-bold">{error}</div>}{success&&<div className="mb-5 rounded-2xl border border-green-200 bg-green-50 text-green-700 p-4 font-bold">{success}</div>}
      <div className="grid sm:grid-cols-3 gap-4 mb-7"><div className="card p-5"><Users className="text-[#b88618]"/><div className="text-slate-500 text-sm mt-3">إجمالي المستخدمين</div><div className="text-3xl font-black text-[#09233f] mt-1">{profiles.length}</div></div><div className="card p-5"><ShieldCheck className="text-[#b88618]"/><div className="text-slate-500 text-sm mt-3">المديرون</div><div className="text-3xl font-black text-[#09233f] mt-1">{profiles.filter(p=>p.role==='admin').length}</div></div><div className="card p-5"><KeyRound className="text-[#b88618]"/><div className="text-slate-500 text-sm mt-3">المستخدمون النشطون</div><div className="text-3xl font-black text-[#09233f] mt-1">{profiles.filter(p=>p.is_active).length}</div></div></div>
      <div className="card overflow-hidden"><div className="p-5 border-b border-slate-200 font-black text-[#09233f]">قائمة المستخدمين</div>{pageLoading?<div className="p-12 text-center text-slate-500">جاري تحميل المستخدمين...</div>:profiles.length?<div className="divide-y divide-slate-100">{profiles.map(p=><div key={p.user_id} className="p-5 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="font-black text-[#09233f]">{p.display_name}</div><div className="text-sm text-slate-500 mt-1">{p.email} · {roleLabels[p.role]||p.role}</div></div><div className="flex items-center gap-3"><span className={`px-3 py-1 rounded-full text-xs font-bold ${p.is_active?'bg-green-50 text-green-700':'bg-red-50 text-red-700'}`}>{p.is_active?'نشط':'موقوف'}</span><span className="text-xs text-slate-400">{new Date(p.created_at).toLocaleDateString('ar-SA')}</span></div></div>)}</div>:<div className="p-12 text-center text-slate-500">لا يوجد مستخدمون مسجلون في ملف الصلاحيات بعد.</div>}</div>
    </div>
    {showModal&&<div className="fixed inset-0 z-[100] bg-[#06172a]/70 backdrop-blur-sm p-4 flex items-center justify-center"><div className="w-full max-w-lg bg-white rounded-[2rem] shadow-2xl overflow-hidden"><div className="bg-[#09233f] text-white p-6 flex items-center justify-between"><div><div className="text-[#d4a72c] text-sm font-bold">مستخدم جديد</div><h2 className="text-xl font-black mt-1">إضافة مستخدم للنظام</h2></div><button onClick={()=>setShowModal(false)} className="text-white/70 hover:text-white text-2xl">×</button></div><form onSubmit={submit} className="p-6 space-y-4"><label className="block text-sm font-bold text-[#09233f]">اسم المستخدم<input required value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} className="input mt-2" placeholder="مثال: أحمد محمد"/></label><label className="block text-sm font-bold text-[#09233f]">البريد الإلكتروني<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="input mt-2" placeholder="name@company.com"/></label><label className="block text-sm font-bold text-[#09233f]">كلمة المرور<div className="relative mt-2"><input required minLength={8} type={showPassword?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="input pl-12" placeholder="8 أحرف على الأقل"/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute left-3 top-3 text-slate-400">{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label><label className="block text-sm font-bold text-[#09233f]">الصلاحية<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="input mt-2"><option value="hr">الموارد البشرية</option><option value="interviewer">مقيم / مقابلات</option><option value="manager">مدير</option><option value="admin">مدير النظام</option></select></label><div className="rounded-xl bg-slate-50 border border-slate-200 p-3 text-sm text-slate-600">سيتم حفظ هذه الصلاحية مع المستخدم، وسيتم تطبيقها على الصفحات المسموح له بدخولها.</div><div className="flex gap-3 pt-2"><button type="button" onClick={()=>setShowModal(false)} className="flex-1 rounded-xl border border-slate-200 py-3 font-bold">إلغاء</button><button disabled={loading} className="flex-1 rounded-xl bg-[#09233f] text-white py-3 font-black disabled:opacity-60">{loading?'جاري الإنشاء...':'إنشاء المستخدم'}</button></div></form></div></div>}
  </main>
}
