'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,FileText,RefreshCw,ExternalLink,Copy,Plus} from 'lucide-react'
import {supabase} from '@/lib/supabase'

type RecordRow={id:string;form_type:string;employee_name:string|null;employee_number:string|null;department:string|null;job_title:string|null;status:string;created_at:string;updated_at:string;last_ip_address:string|null;last_device_name:string|null;submitted_via_link:boolean}
type LinkRow={id:string;token:string;form_type:string;record_id:string|null;last_ip_address:string|null;last_device_name:string|null;last_opened_at:string|null;last_submitted_at:string|null;expires_at:string|null;status:string}
const names:Record<string,string>={leave:'طلب إجازة',clearance:'إخلاء طرف',advance:'طلب سلفة مالية'}

export default function FormRecords(){
 const [rows,setRows]=useState<RecordRow[]>([]); const [links,setLinks]=useState<LinkRow[]>([]); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState('all'); const [copied,setCopied]=useState('')
 const load=async()=>{setLoading(true);let q=supabase.from('hr_form_records').select('id,form_type,employee_name,employee_number,department,job_title,status,created_at,updated_at,last_ip_address,last_device_name,submitted_via_link').order('updated_at',{ascending:false});if(filter!=='all')q=q.eq('form_type',filter);const [{data},lr]=await Promise.all([q,fetch('/api/forms/links',{cache:'no-store'}).then(x=>x.json())]);setRows((data||[]) as RecordRow[]);setLinks((lr.links||[]) as LinkRow[]);setLoading(false)}
 useEffect(()=>{load()},[filter])
 const createLink=async(formType:string,recordId?:string)=>{const r=await fetch('/api/forms/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form_type:formType,record_id:recordId||null})});const d=await r.json();if(!r.ok){alert(d.error||'تعذر إنشاء الرابط');return}const url=location.origin+'/forms/public/'+d.link.token;await navigator.clipboard?.writeText(url);setCopied(d.link.token);setTimeout(()=>setCopied(''),1800);await load()}
 const url=(token:string)=>location.origin+'/forms/public/'+token
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-7xl mx-auto">
 <header className="flex flex-wrap items-center justify-between gap-3 mb-7"><div><div className="text-[#b88618] font-bold">إدارة الموارد البشرية</div><h1 className="text-3xl font-black text-[#09233f]">سجل النماذج</h1><p className="text-slate-500">النماذج المحفوظة مركزيًا، مع متابعة روابط النماذج الخارجية وبيانات الجهاز وعنوان IP.</p></div><div className="flex gap-2"><Link href="/forms" className="border bg-white rounded-xl px-4 py-2 font-bold inline-flex gap-2 items-center"><ArrowLeft size={17}/> مركز النماذج</Link><button onClick={load} className="bg-[#09233f] text-white rounded-xl px-4 py-2 font-bold inline-flex gap-2"><RefreshCw size={17}/> تحديث</button></div></header>
 <div className="bg-white border rounded-2xl p-4 mb-5 flex flex-wrap gap-2">{[['all','الكل'],['leave','الإجازات'],['clearance','إخلاء الطرف'],['advance','السلف']].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`px-4 py-2 rounded-xl font-bold ${filter===v?'bg-[#b88618] text-white':'border'}`}>{l}</button>)}</div>
 <div className="bg-white border rounded-2xl overflow-hidden mb-7"><div className="p-4 border-b flex items-center justify-between"><h2 className="font-black text-[#09233f]">النماذج المحفوظة</h2><span className="text-xs text-slate-500">{rows.length} نموذج</span></div>{loading?<div className="p-10 text-center">جارٍ تحميل السجل...</div>:rows.length===0?<div className="p-10 text-center text-slate-500">لا توجد نماذج محفوظة.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#09233f] text-white"><tr><th className="p-3 text-right">النموذج</th><th className="p-3 text-right">الموظف</th><th className="p-3 text-right">القسم</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">التحديث</th><th className="p-3 text-right">الجهاز / IP</th><th className="p-3 text-right">رابط خارجي</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-bold">{names[r.form_type]||r.form_type}</td><td className="p-3">{r.employee_name||'—'}<div className="text-xs text-slate-500">{r.employee_number||''}</div></td><td className="p-3">{r.department||'—'}<div className="text-xs text-slate-500">{r.job_title||''}</div></td><td className="p-3"><span className="rounded-lg bg-slate-100 px-3 py-1">{r.status}</span></td><td className="p-3">{new Date(r.updated_at).toLocaleString('ar-SA')}</td><td className="p-3">{r.submitted_via_link?<><div className="font-bold">{r.last_device_name||'غير معروف'}</div><div className="font-mono text-xs text-slate-500">{r.last_ip_address||'—'}</div></>:<span className="text-slate-400">داخلي</span>}</td><td className="p-3"><button onClick={()=>createLink(r.form_type,r.id)} className="bg-[#b88618] text-white rounded-lg px-3 py-1.5 font-bold inline-flex items-center gap-1"><Plus size={14}/> إنشاء/نسخ الرابط</button></td></tr>)}</tbody></table></div>}</div>
 <div className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 border-b flex items-center justify-between"><h2 className="font-black text-[#09233f]">روابط النماذج الخارجية وسجل الوصول</h2>{copied&&<span className="text-green-700 font-bold text-sm">تم نسخ الرابط</span>}</div>{links.length===0?<div className="p-8 text-center text-slate-500">لم يتم إنشاء روابط خارجية بعد.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-100"><tr><th className="p-3 text-right">النموذج</th><th className="p-3 text-right">الجهاز</th><th className="p-3 text-right">IP</th><th className="p-3 text-right">آخر فتح</th><th className="p-3 text-right">آخر إرسال</th><th className="p-3 text-right">الإجراء</th></tr></thead><tbody>{links.map(l=><tr key={l.id} className="border-t"><td className="p-3 font-bold">{names[l.form_type]||l.form_type}</td><td className="p-3">{l.last_device_name||'لم يفتح بعد'}</td><td className="p-3 font-mono text-xs">{l.last_ip_address||'—'}</td><td className="p-3">{l.last_opened_at?new Date(l.last_opened_at).toLocaleString('ar-SA'):'—'}</td><td className="p-3">{l.last_submitted_at?new Date(l.last_submitted_at).toLocaleString('ar-SA'):'—'}</td><td className="p-3 flex gap-2"><a href={url(l.token)} target="_blank" rel="noreferrer" className="rounded-lg border px-3 py-1.5 font-bold inline-flex items-center gap-1"><ExternalLink size={14}/>فتح</a><button onClick={async()=>{await navigator.clipboard?.writeText(url(l.token));setCopied(l.token);setTimeout(()=>setCopied(''),1800)}} className="rounded-lg border px-3 py-1.5 font-bold inline-flex items-center gap-1"><Copy size={14}/>نسخ</button></td></tr>)}</tbody></table></div>}</div>
 <div className="mt-4 text-xs text-slate-500 flex items-center gap-2"><FileText size={15}/>يتم تسجيل عنوان IP من طلب الخادم، واسم الجهاز يعتمد على معلومات المتصفح/Client Hints المتاحة؛ بعض المتصفحات لا تكشف اسم الموديل الدقيق.</div>
 </div></main>
