'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {Copy,ExternalLink,RefreshCw,ArrowLeft,Link2} from 'lucide-react'
import {supabase} from '@/lib/supabase'

const stages=[['hr','الموارد البشرية'],['specialized','الإدارة المختصة'],['executive','الإدارة التنفيذية'],['general_manager','المدير العام']] as const
export default function EvaluationLinksPage(){
 const[candidates,setCandidates]=useState<any[]>([]);const[links,setLinks]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState('')
 const load=async()=>{setLoading(true);const[{data:c},{data:l}]=await Promise.all([supabase.from('candidates').select('id,request_id,full_name,status').order('created_at',{ascending:false}),supabase.from('candidate_evaluation_links').select('*')]);setCandidates(c||[]);setLinks(l||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const makeLink=async(c:any,stage:string)=>{setMsg('');let existing=links.find(x=>x.candidate_id===c.id&&x.stage===stage);if(!existing){const{data,error}=await supabase.from('candidate_evaluation_links').insert({candidate_id:c.id,request_id:c.request_id,stage}).select('*').single();if(error){setMsg(error.message);return}existing=data;setLinks(x=>[...x,data])}await navigator.clipboard?.writeText(`${window.location.origin}/evaluation/${existing.token}`);setMsg(`تم إنشاء/نسخ رابط ${stages.find(x=>x[0]===stage)?.[1]} للمرشح ${c.full_name}`)}
 const url=(token:string)=>`${typeof window!=='undefined'?window.location.origin:''}/evaluation/${token}`
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-7xl mx-auto"><header className="flex items-center justify-between mb-6"><div><div className="text-[#b88618] font-bold">المقابلات والتقييم</div><h1 className="text-3xl font-black text-[#09233f]">روابط التقييم المرحلي</h1><p className="text-slate-500 mt-1">رابط مستقل لكل مرحلة، وكل جهة ترى فقط ما يخصها وما سبقها.</p></div><div className="flex gap-2"><button onClick={load} className="border rounded-xl px-4 py-2 font-bold inline-flex gap-2"><RefreshCw size={17}/> تحديث</button><Link href="/interviews" className="border rounded-xl px-4 py-2 font-bold inline-flex gap-2"><ArrowLeft size={17}/> المقابلات</Link></div></header>{msg&&<div className="mb-5 p-4 rounded-xl bg-green-50 border border-green-200 font-bold text-green-800">{msg}</div>}<section className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#09233f] text-white"><tr><th className="p-4 text-right">المرشح</th>{stages.map(s=><th key={s[0]} className="p-4 text-right">{s[1]}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-10 text-center">جاري التحميل...</td></tr>:candidates.map(c=><tr key={c.id} className="border-t"><td className="p-4"><div className="font-bold">{c.full_name}</div><div className="text-xs text-slate-500">{c.status||'—'}</div></td>{stages.map(s=>{const l=links.find(x=>x.candidate_id===c.id&&x.stage===s[0]);return <td key={s[0]} className="p-4"><div className="flex flex-wrap gap-2"><button onClick={()=>makeLink(c,s[0])} className="btn-primary rounded-lg px-3 py-2 font-bold inline-flex gap-1 items-center"><Link2 size={15}/>{l?'نسخ الرابط':'إنشاء الرابط'}</button>{l&&<Link href={url(l.token)} target="_blank" className="border rounded-lg px-3 py-2 inline-flex gap-1 items-center"><ExternalLink size={15}/>فتح</Link>}</div>{l&&<div className="text-[10px] text-slate-400 mt-2 break-all">{url(l.token)}</div>}</td>})}</tr>)}</tbody></table></div></section></div></main>}
