'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {RefreshCw,ArrowLeft,Link2,CalendarDays,MessageCircle,ExternalLink} from 'lucide-react'
import {supabase} from '@/lib/supabase'
const stages=[['hr','الموارد البشرية'],['specialized','الإدارة المختصة'],['executive','الإدارة التنفيذية'],['general_manager','المدير العام']] as const
function phone(v:string){return (v||'').replace(/[^0-9]/g,'')}
function teamsScheduleUrl(subject:string,start:string,end:string,content:string,email?:string|null){const p=new URLSearchParams({subject,startTime:start,endTime:end,content});if(email)p.set('attendees',email);return `https://teams.microsoft.com/l/meeting/new?${p.toString().replace(/\+/g,'%20')}`}
export default function EvaluationLinksPage(){
 const[candidates,setCandidates]=useState<any[]>([]);const[links,setLinks]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState('');const[selected,setSelected]=useState<any>(null);const[date,setDate]=useState('');const[start,setStart]=useState('');const[end,setEnd]=useState('');const[teamsLink,setTeamsLink]=useState('')
 const load=async()=>{setLoading(true);const[{data:c},{data:l}]=await Promise.all([supabase.from('candidates').select('id,request_id,full_name,status,phone,email').order('created_at',{ascending:false}),supabase.from('candidate_evaluation_links').select('*')]);setCandidates(c||[]);setLinks(l||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const makeLink=async(c:any,stage:string)=>{setMsg('');let existing=links.find(x=>x.candidate_id===c.id&&x.stage===stage);if(!existing){const{data,error}=await supabase.from('candidate_evaluation_links').insert({candidate_id:c.id,request_id:c.request_id,stage}).select('*').single();if(error){setMsg(error.message);return}existing=data;setLinks(x=>[...x,data])}await navigator.clipboard?.writeText(`${window.location.origin}/evaluation/${existing.token}`);setMsg(`تم إنشاء/نسخ رابط ${stages.find(x=>x[0]===stage)?.[1]} للمرشح ${c.full_name}`)}
 const openSchedule=(c:any)=>{setSelected(c);setDate('');setStart('');setEnd('');setTeamsLink('');setMsg('')}
 const buildTeams=()=>{if(!selected||!date||!start||!end){setMsg('حدد يوم المقابلة ووقت البداية والنهاية أولًا.');return}const s=`${date}T${start}:00+03:00`,e=`${date}T${end}:00+03:00`;const url=teamsScheduleUrl(`مقابلة توظيف - ${selected.full_name}`,s,e,`مقابلة توظيف للمرشح ${selected.full_name}`,selected.email);setTeamsLink(url);setMsg('تم تجهيز رابط جدولة Microsoft Teams بالموعد المحدد. افتحه من حساب المنظم وأنشئ الاجتماع، ثم انسخ رابط الانضمام النهائي وضعه في الحقل أدناه.')}
 const saveMeeting=async()=>{if(!selected||!date||!start||!end||!teamsLink){setMsg('أكمل بيانات الموعد ورابط Teams النهائي.');return}const s=`${date}T${start}:00+03:00`,e=`${date}T${end}:00+03:00`;const{error}=await supabase.from('candidate_interviews').upsert({candidate_id:selected.id,request_id:selected.request_id,interview_date:s,interview_type:'مقابلة توظيف',interview_platform:'Microsoft Teams',interview_start_at:s,interview_end_at:e,teams_scheduling_url:teamsLink,teams_join_url:teamsLink,meeting_status:'محدد'}, {onConflict:'candidate_id'});if(error){setMsg(`تعذر حفظ الموعد: ${error.message}`);return}setMsg('تم حفظ موعد المقابلة ورابط Teams.');setSelected(null);await load()}
 const messageFor=(c:any)=>{const i=links.find(x=>x.candidate_id===c.id);const iv=undefined;return `السلام عليكم ورحمة الله وبركاته،\nعزيزي/عزيزتي ${c.full_name}\n\nيسرنا دعوتكم لإجراء مقابلة توظيف.\n\n📅 التاريخ: ${date}\n🕐 الوقت: ${start} - ${end} (بتوقيت السعودية)\n💻 المنصة: Microsoft Teams\n🔗 رابط المقابلة: ${teamsLink}\n\nنأمل الالتزام بالموعد والتأكد من جاهزية الاتصال.\n\nمع تمنياتنا لكم بالتوفيق،\nشركة البنية الأساسية للمقاولات`}
 const sendWhatsApp=()=>{if(!selected||!teamsLink||!date||!start||!end){setMsg('أكمل بيانات الموعد ورابط Teams أولًا.');return}window.open(`https://wa.me/${phone(selected.phone)}?text=${encodeURIComponent(messageFor(selected))}`,'_blank')}
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-7xl mx-auto"><header className="flex items-center justify-between mb-6"><div><div className="text-[#b88618] font-bold">المقابلات والتقييم</div><h1 className="text-3xl font-black text-[#09233f]">روابط التقييم والمقابلات</h1><p className="text-slate-500 mt-1">التقييمات لها روابط مستقلة، والمقابلات تُحدد بموعد واضح عبر Microsoft Teams.</p></div><div className="flex gap-2"><button onClick={load} className="border rounded-xl px-4 py-2 font-bold inline-flex gap-2"><RefreshCw size={17}/> تحديث</button><Link href="/interviews" className="border rounded-xl px-4 py-2 font-bold inline-flex gap-2"><ArrowLeft size={17}/> المقابلات</Link></div></header>{msg&&<div className="mb-5 p-4 rounded-xl bg-green-50 border border-green-200 font-bold text-green-800">{msg}</div>}
 <section className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#09233f] text-white"><tr><th className="p-4 text-right">المرشح</th>{stages.map(s=><th key={s[0]} className="p-4 text-right">{s[1]}</th>)}<th className="p-4">موعد المقابلة</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-10 text-center">جاري التحميل...</td></tr>:candidates.map(c=><tr key={c.id} className="border-t"><td className="p-4"><div className="font-bold">{c.full_name}</div><div className="text-xs text-slate-500">{c.phone||'بدون جوال'}</div></td>{stages.map(s=>{const l=links.find(x=>x.candidate_id===c.id&&x.stage===s[0]);return <td key={s[0]} className="p-4"><div className="flex flex-wrap gap-2"><button onClick={()=>makeLink(c,s[0])} className="btn-primary rounded-lg px-3 py-2 font-bold inline-flex gap-1 items-center"><Link2 size={15}/>{l?'نسخ الرابط':'إنشاء الرابط'}</button>{l&&<Link href={`/evaluation/${l.token}`} target="_blank" className="border rounded-lg px-3 py-2 inline-flex gap-1 items-center"><ExternalLink size={15}/>فتح</Link>}</div></td>})}<td className="p-4"><button onClick={()=>openSchedule(c)} className="btn-primary rounded-lg px-3 py-2 font-bold inline-flex gap-1 items-center"><CalendarDays size={15}/> تحديد الموعد</button></td></tr>)}</tbody></table></div></section>
 {selected&&<div className="fixed inset-0 bg-black/40 grid place-items-center p-4 z-50"><div className="bg-white rounded-2xl p-6 w-full max-w-2xl" dir="rtl"><h2 className="text-2xl font-black text-[#09233f]">تحديد مقابلة Microsoft Teams</h2><p className="mt-2 text-slate-500">المرشح: {selected.full_name}</p><div className="grid md:grid-cols-3 gap-3 mt-5"><label className="font-bold">التاريخ<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="block w-full border rounded-xl px-3 py-2 mt-1"/></label><label className="font-bold">من<input type="time" value={start} onChange={e=>setStart(e.target.value)} className="block w-full border rounded-xl px-3 py-2 mt-1"/></label><label className="font-bold">إلى<input type="time" value={end} onChange={e=>setEnd(e.target.value)} className="block w-full border rounded-xl px-3 py-2 mt-1"/></label></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={buildTeams} className="btn-primary rounded-xl px-4 py-2 font-bold">تجهيز اجتماع Teams</button>{teamsLink&&<a href={teamsLink} target="_blank" rel="noreferrer" className="border rounded-xl px-4 py-2 font-bold">فتح Teams</a>}</div>{teamsLink&&<><label className="block font-bold mt-5">رابط الانضمام النهائي من Teams<input value={teamsLink} onChange={e=>setTeamsLink(e.target.value)} className="w-full border rounded-xl px-3 py-2 mt-1" placeholder="ألصق هنا رابط Teams الذي تم إنشاؤه"/></label><div className="mt-4 p-4 rounded-xl bg-slate-50 whitespace-pre-wrap text-sm">{messageFor(selected)}</div><div className="flex gap-2 mt-4"><button onClick={saveMeeting} className="btn-primary rounded-xl px-4 py-2 font-bold">حفظ الموعد</button><button onClick={sendWhatsApp} className="border rounded-xl px-4 py-2 font-bold inline-flex gap-2"><MessageCircle size={17}/> إرسال WhatsApp</button><button onClick={()=>navigator.clipboard?.writeText(messageFor(selected))} className="border rounded-xl px-4 py-2 font-bold">نسخ الرسالة</button></div></>}</div></div>}
 </div></main>}
