'use client'
import Link from 'next/link'
import { FileText, Printer, RefreshCw } from 'lucide-react'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
type Row={id:string;full_name:string;request_id:string}
export default function ReportsPage(){
 const [candidates,setCandidates]=useState<Row[]>([]);const [onboarding,setOnboarding]=useState<Row[]>([]);const [loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);if(!supabase){setLoading(false);return}const [{data:cs},{data:os}]=await Promise.all([supabase.from('candidate_interviews').select('candidate_id').order('created_at',{ascending:false}),supabase.from('employee_onboarding').select('candidate_id').order('created_at',{ascending:false})]);const ids=Array.from(new Set([...(cs||[]).map((x:any)=>x.candidate_id),...(os||[]).map((x:any)=>x.candidate_id)]));if(ids.length){const {data}=await supabase.from('candidates').select('id,full_name,request_id').in('id',ids);const map=new Map((data||[]).map((x:any)=>[x.id,x]));setCandidates((cs||[]).map((x:any)=>map.get(x.candidate_id)).filter(Boolean) as Row[]);setOnboarding((os||[]).map((x:any)=>map.get(x.candidate_id)).filter(Boolean) as Row[])}else{setCandidates([]);setOnboarding([])}setLoading(false)}
 useEffect(()=>{load()},[])
 const ReportRow=({x,url,label}:{x:Row;url:string;label:string})=><div className="border rounded-xl p-4 flex items-center justify-between gap-4"><div><b>{x.full_name}</b><div className="text-sm text-slate-500">{label}</div></div><Link href={url} className="btn-primary rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><Printer size={17}/> فتح وتصدير PDF</Link></div>
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-10"><div className="max-w-6xl mx-auto"><header className="flex items-center justify-between mb-7"><div><div className="text-[#b88618] font-bold">البنية الاساسية للمقاولات</div><h1 className="text-3xl font-black text-[#09233f]">التقارير الرسمية</h1><p className="text-slate-500 mt-1">تقارير جاهزة للطباعة والحفظ PDF بحجم A4.</p></div><button onClick={load} className="border rounded-xl p-3"><RefreshCw size={19}/></button></header>{loading?<div className="card p-12 text-center">جاري تحميل التقارير...</div>:<div className="space-y-6"><section className="card p-6"><div className="flex items-center gap-3 mb-5"><FileText className="text-[#b88618]"/><h2 className="text-xl font-black text-[#09233f]">تقارير المقابلات والتقييم</h2></div>{candidates.length?<div className="space-y-3">{candidates.map((x,i)=><ReportRow key={`${x.id}-${i}`} x={x} url={`/interviews/report/${x.id}`} label="تقرير المقابلة والتقييم النهائي"/>)}</div>:<p className="text-slate-500">لا توجد تقارير مقابلات حتى الآن.</p>}</section><section className="card p-6"><div className="flex items-center gap-3 mb-5"><FileText className="text-[#b88618]"/><h2 className="text-xl font-black text-[#09233f]">تقارير مباشرة العمل</h2></div>{onboarding.length?<div className="space-y-3">{onboarding.map((x,i)=><ReportRow key={`${x.id}-${i}`} x={x} url={`/onboarding/report/${x.id}`} label="نموذج مباشرة العمل الرسمي"/>)}</div>:<p className="text-slate-500">لا توجد نماذج مباشرة حتى الآن.</p>}</section></div>}<div className="mt-6 bg-white border rounded-xl p-4 text-sm text-slate-600">التقارير مضبوطة للطباعة على A4. من نافذة الطباعة اختر <b>Save as PDF / حفظ كملف PDF</b> للحصول على الملف الرسمي.</div></div></main>
}