'use client'
import {useEffect,useRef,useState} from 'react'
import {Eraser,RefreshCw,Save,Upload,PenLine,Type,Check} from 'lucide-react'

type Mode='name'|'draw'|'upload'
type Props={employeeId?:string|null;publicToken?:string;value?:string;onChange?:(v:string)=>void;onSaved?:(v:string)=>void;autoUseSaved?:boolean;disabled?:boolean}
const styles=[['كلاسيكي','cursive'],['أنيق','"Brush Script MT",cursive'],['رسمي','Georgia,serif'],['مميز','"Segoe Script",cursive']]

function nameSignature(name:string,color:string,index:number,scale:number){
 const esc=name.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[m]||m))
 const w=Math.round(1000*scale),h=Math.round(260*scale),font=styles[index][1]
 const svg='<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'"><text x="50%" y="57%" text-anchor="middle" fill="'+color+'" font-family="'+font+'" font-size="'+Math.round(92*scale)+'" font-style="italic" font-weight="600">'+esc+'</text><path d="M 100 '+Math.round(h*.78)+' C 300 '+Math.round(h*.95)+', 650 '+Math.round(h*.65)+', '+(w-90)+' '+Math.round(h*.8)+'" fill="none" stroke="'+color+'" stroke-width="'+Math.max(3,Math.round(5*scale))+'" stroke-linecap="round"/></svg>'
 return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)
}
async function normalizeImage(src:string){
 return new Promise<string>((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth||1200;c.height=img.naturalHeight||300;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);const d=ctx.getImageData(0,0,c.width,c.height),p=d.data;let minX=c.width,minY=c.height,maxX=-1,maxY=-1;for(let i=0;i<p.length;i+=4){const r=p[i],g=p[i+1],b=p[i+2],a=p[i+3],x=(i/4)%c.width,y=Math.floor((i/4)/c.width);if(a<15||(r>245&&g>245&&b>245)){p[i+3]=0;continue}minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}if(maxX<0)return resolve(src);ctx.putImageData(d,0,0);const pad=16,x=Math.max(0,minX-pad),y=Math.max(0,minY-pad),w=Math.min(c.width-x,maxX-minX+1+pad*2),h=Math.min(c.height-y,maxY-minY+1+pad*2),o=document.createElement('canvas');o.width=w;o.height=h;o.getContext('2d')!.drawImage(c,x,y,w,h,0,0,w,h);resolve(o.toDataURL('image/png'))};img.onerror=()=>reject(new Error('تعذر قراءة صورة التوقيع'));img.src=src})
}
export default function SignatureEditor({employeeId,publicToken,value='',onChange,onSaved,autoUseSaved=true,disabled=false}:Props){
 const [mode,setMode]=useState<Mode>('name'),[name,setName]=useState(''),[color,setColor]=useState('#111827'),[style,setStyle]=useState(0),[scale,setScale]=useState(1),[preview,setPreview]=useState(value),[saved,setSaved]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),last=useRef<{x:number;y:number}|null>(null)
 useEffect(()=>{if(value)setPreview(value)},[value])
 useEffect(()=>{if(!employeeId)return;let live=true;fetch('/api/signatures?employee_id='+encodeURIComponent(employeeId)+(publicToken?'&token='+encodeURIComponent(publicToken):''),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{if(live&&d?.signature?.signature_url){setSaved(d.signature.signature_url);if(autoUseSaved&&!value){setPreview(d.signature.signature_url);onChange?.(d.signature.signature_url)}}});return()=>{live=false}},[employeeId,publicToken,autoUseSaved,value,onChange])
 const emit=(v:string)=>{setPreview(v);onChange?.(v);setMsg('')}
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}}
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(disabled)return;e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;last.current=point(e)}
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!,p=point(e),q=last.current;ctx.strokeStyle=color;ctx.lineWidth=4;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();if(q){const m={x:(q.x+p.x)/2,y:(q.y+p.y)/2};ctx.moveTo(q.x,q.y);ctx.quadraticCurveTo(q.x,q.y,m.x,m.y)}else ctx.moveTo(p.x,p.y);ctx.stroke();last.current=p}
 const end=()=>{if(!drawing.current)return;drawing.current=false;last.current=null;if(canvas.current)emit(canvas.current.toDataURL('image/png'))}
 const clear=()=>{canvas.current?.getContext('2d')?.clearRect(0,0,canvas.current.width,canvas.current.height);emit('')}
 const upload=async(file:File)=>{setBusy(true);try{const r=new FileReader();r.onload=async()=>{try{emit(await normalizeImage(String(r.result)))}catch(e){setMsg(e instanceof Error?e.message:'تعذر تجهيز الصورة')}finally{setBusy(false)}};r.readAsDataURL(file)}catch{setBusy(false)}}
 const save=async()=>{if(!preview){setMsg('اختر أو أنشئ توقيعًا أولًا.');return}if(!employeeId){onSaved?.(preview);setMsg('تم تجهيز التوقيع.');return}setBusy(true);try{const r=await fetch('/api/signatures',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({employee_id:employeeId,token:publicToken,signature_data:preview,signature_type:mode==='name'?'name':mode==='draw'?'drawn':'upload',signature_color:color})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر حفظ التوقيع');setSaved(d.signature.signature_url);emit(d.signature.signature_url);onSaved?.(d.signature.signature_url);setMsg('تم حفظ التوقيع بنجاح.')}catch(e){setMsg(e instanceof Error?e.message:'تعذر حفظ التوقيع')}finally{setBusy(false)}}
 return <section dir="rtl" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
  <div className="flex items-center justify-between gap-2 mb-3"><h3 className="font-black text-[#09233f]">التوقيع الإلكتروني</h3>{saved&&<button type="button" onClick={()=>emit(saved)} className="rounded-lg bg-emerald-50 text-emerald-700 px-3 py-2 text-xs font-bold inline-flex gap-1"><Check size={14}/>استخدام التوقيع المحفوظ</button>}</div>
  {saved&&<div className="mb-3 rounded-xl bg-slate-50 p-2"><div className="text-[11px] font-bold text-slate-500">التوقيع المحفوظ</div><img src={saved} alt="التوقيع المحفوظ" className="h-16 w-full object-contain"/></div>}
  <div className="flex items-center gap-2 mb-3 text-xs font-bold"><span>لون التوقيع</span><button type="button" onClick={()=>setColor('#111827')} className="h-7 w-7 rounded-full bg-black ring-2 ring-slate-200" title="أسود"/><button type="button" onClick={()=>setColor('#0b3d91')} className="h-7 w-7 rounded-full bg-blue-800 ring-2 ring-slate-200" title="أزرق"/></div><div className="flex flex-wrap gap-2 mb-3">{([['name','إنشاء من الاسم',Type],['draw','رسم التوقيع',PenLine],['upload','رفع توقيع',Upload]] as const).map(([m,l,I])=><button key={m} type="button" disabled={disabled} onClick={()=>setMode(m)} className={'rounded-lg px-3 py-2 text-sm font-bold inline-flex gap-1 '+(mode===m?'bg-[#09233f] text-white':'border bg-white text-[#09233f]')}><I size={15}/>{l}</button>)}</div>
  {mode==='name'&&<div className="space-y-3"><input value={name} disabled={disabled} onChange={e=>{setName(e.target.value);setPreview(nameSignature(e.target.value,color,style,scale))}} placeholder="اكتب الاسم الذي سيظهر في التوقيع" className="w-full rounded-lg border p-3"/><div className="flex items-center gap-3 text-sm font-bold"><span>اللون</span><button type="button" onClick={()=>{setColor('#111827');setPreview(nameSignature(name,'#111827',style,scale))}} className="h-7 w-7 rounded-full bg-black"/><button type="button" onClick={()=>{setColor('#0b3d91');setPreview(nameSignature(name,'#0b3d91',style,scale))}} className="h-7 w-7 rounded-full bg-blue-800"/><span>الحجم</span><input type="range" min=".7" max="1.5" step=".1" value={scale} onChange={e=>{const v=Number(e.target.value);setScale(v);setPreview(nameSignature(name,color,style,v))}}/></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2">{styles.map((s,i)=><button type="button" key={s[0]} onClick={()=>{setStyle(i);setPreview(nameSignature(name,color,i,scale))}} className={'rounded-lg border p-2 '+(style===i?'border-[#b88618] ring-1 ring-[#b88618]':'')}><span className="block text-xs font-bold">{s[0]}</span><span style={{fontFamily:s[1],fontStyle:'italic',fontSize:22,color}}>{name||'التوقيع'}</span></button>)}</div></div>}
  {mode==='draw'&&<div><canvas ref={canvas} width={1200} height={300} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} className="w-full h-40 rounded-xl border-2 touch-none bg-white"/><button type="button" onClick={clear} className="mt-2 rounded-lg border px-3 py-2 text-xs font-bold inline-flex gap-1"><Eraser size={14}/>مسح وإعادة الرسم</button></div>}
  {mode==='upload'&&<label className="flex min-h-32 cursor-pointer items-center justify-center rounded-xl border-2 border-dashed font-bold text-slate-500"><input type="file" accept="image/png,image/jpeg" className="hidden" disabled={disabled||busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/>{busy?'جارٍ تجهيز الصورة...':'اضغط لاختيار PNG أو JPG'}</label>}
  <div className="mt-4 border-t pt-3"><div className="text-sm font-bold mb-2">معاينة التوقيع</div><div className="min-h-24 rounded-xl border flex items-center justify-center p-2"><img src={preview||value} alt="معاينة التوقيع" className="max-h-24 max-w-full object-contain"/></div><div className="mt-2 flex gap-2"><button type="button" disabled={disabled||busy} onClick={save} className="rounded-lg bg-[#09233f] text-white px-4 py-2 text-sm font-bold inline-flex gap-1"><Save size={15}/>حفظ التوقيع</button><button type="button" disabled={disabled} onClick={()=>emit('')} className="rounded-lg border px-4 py-2 text-sm font-bold inline-flex gap-1"><RefreshCw size={15}/>إعادة الاختيار</button></div>{msg&&<div className="mt-2 text-xs font-bold">{msg}</div>}</div>
 </section>
}