import {NextRequest,NextResponse} from 'next/server'
import {getServerAuth,supabaseHeaders,SUPABASE_URL} from '@/lib/server-auth'
const roles=['admin','hr','manager','interviewer'],bucket='employee-signatures'
const rest=(p:string)=>SUPABASE_URL+'/rest/v1/'+p
async function allowedPublic(req:NextRequest,employeeId:string,token:string){if(!token)return false;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';const r=await fetch(rest('hr_form_links?select=employee_id,status,link_scope&token=eq.'+encodeURIComponent(token)),{headers:{apikey:key,Authorization:'Bearer '+key},cache:'no-store'});const rows=await r.json().catch(()=>[]);return r.ok&&rows[0]?.employee_id===employeeId&&rows[0]?.status==='active'&&rows[0]?.link_scope==='advance:employee'}
function headers(auth:any){return auth?supabaseHeaders(auth):{apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'',Authorization:'Bearer '+(process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''),Accept:'application/json','Content-Type':'application/json'}}
async function signed(path:string,auth:any){const key=auth?.serviceKey||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';const authorization=auth?.serviceKey?'Bearer '+auth.serviceKey:auth?'Bearer '+auth.token:'Bearer '+key;const r=await fetch(SUPABASE_URL+'/storage/v1/object/sign/'+bucket+'/'+path,{method:'POST',headers:{apikey:key,Authorization:authorization,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});const d=await r.json().catch(()=>({}));const u=d?.signedURL||d?.signedUrl;return u?(u.startsWith('http')?u:SUPABASE_URL+'/storage/v1'+u):null}
export async function GET(req:NextRequest){const employeeId=req.nextUrl.searchParams.get('employee_id');if(!employeeId)return NextResponse.json({error:'employee_id مطلوب.'},{status:400});const token=req.nextUrl.searchParams.get('token');const auth=await getServerAuth(req,roles);if(!auth&&!(token&&await allowedPublic(req,employeeId,token)))return NextResponse.json({error:'غير مصرح.'},{status:403});const r=await fetch(rest('employee_signatures?select=*&employee_id=eq.'+encodeURIComponent(employeeId)+'&is_active=eq.true&limit=1'),{headers:headers(auth),cache:'no-store'});const rows=await r.json().catch(()=>[]);if(!r.ok)return NextResponse.json({error:'تعذر قراءة التوقيع.'},{status:r.status});if(!rows[0])return NextResponse.json({signature:null});return NextResponse.json({signature:{...rows[0],signature_url:await signed(rows[0].signature_url,auth)}})}
export async function POST(req:NextRequest){const body=await req.json().catch(()=>({})),employeeId=String(body.employee_id||'');if(!employeeId)return NextResponse.json({error:'employee_id مطلوب.'},{status:400});const token=String(body.token||''),auth=await getServerAuth(req,roles);if(!auth&&!(token&&await allowedPublic(req,employeeId,token)))return NextResponse.json({error:'غير مصرح.'},{status:403});if(!auth&&!process.env.SUPABASE_SERVICE_ROLE_KEY)return NextResponse.json({error:'حفظ التوقيع من الرابط العام يحتاج إعداد صلاحية الخادم.'},{status:503});const raw=String(body.signature_data||''),m=raw.match(/^data:image\/(png|jpeg|jpg);base64,(.+)$/);if(!m)return NextResponse.json({error:'صيغة التوقيع غير صالحة.'},{status:400});const ext=m[1]==='jpeg'||m[1]==='jpg'?'jpg':'png',mime=ext==='jpg'?'image/jpeg':'image/png',bytes=Buffer.from(m[2],'base64');if(bytes.length>3*1024*1024)return NextResponse.json({error:'حجم التوقيع كبير.'},{status:400});const path=employeeId+'/'+Date.now()+'-'+crypto.randomUUID()+'.'+ext,key=auth?.serviceKey||process.env.SUPABASE_SERVICE_ROLE_KEY||'',authorization='Bearer '+key;const up=await fetch(SUPABASE_URL+'/storage/v1/object/'+bucket+'/'+path,{method:'POST',headers:{apikey:key,Authorization:authorization,'Content-Type':mime,x-upsert:'false'},body:bytes});if(!up.ok)return NextResponse.json({error:'تعذر رفع ملف التوقيع.'},{status:up.status});const h=auth?supabaseHeaders(auth):headers(auth);await fetch(rest('employee_signatures?employee_id=eq.'+encodeURIComponent(employeeId)+'&is_active=eq.true'),{method:'PATCH',headers:{...h,Prefer:'return=minimal'},body:JSON.stringify({is_active:false,signature_updated_at:new Date().toISOString(),updated_by:auth?.user?.id||null})});const payload={employee_id:employeeId,signature_url:path,signature_type:body.signature_type||'drawn',signature_color:body.signature_color||'#111827',signature_created_at:new Date().toISOString(),signature_updated_at:new Date().toISOString(),created_by:auth?.user?.id||null,updated_by:auth?.user?.id||null,is_active:true};const ins=await fetch(rest('employee_signatures'),{method:'POST',headers:{...h,Prefer:'return=representation'},body:JSON.stringify(payload)});const rows=await ins.json().catch(()=>[]);if(!ins.ok)return NextResponse.json({error:'تعذر تسجيل التوقيع في قاعدة البيانات.'},{status:ins.status});return NextResponse.json({signature:{...(rows[0]||payload),signature_url:await signed(path,auth)}})}
