'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { useParams, useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

const contracts = ['دوام كامل','دوام جزئي','مؤقت','تدريب','أخرى']
const initial: Record<string, string> = {offer_number:'',issue_date:'',start_date:'',job_title:'',department:'',project_name:'',work_location:'',work_hours:'8 ساعات',work_days:'5 أيام',salary:'',housing_allowance:'',transportation_allowance:'',other_allowances:'',total_salary:'',annual_leave:'30 يومًا',probation_period:'90 يومًا',health_insurance:'وفق سياسة الشركة',gosi:'وفق الأنظمة السعودية',bonus:'',performance_bonus:'',confidentiality:'يلتزم الطرف الثاني بالمحافظة على سرية معلومات الشركة ومشروعاتها.',intellectual_property:'تؤول حقوق الأعمال والمخرجات المتعلقة بالعمل إلى الشركة وفق العقد والأنظمة.',termination_notice:'وفق العقد ونظام العمل السعودي',offer_validity:'7 أيام من تاريخ الإصدار',employer_representative:'',contract_type:'دوام كامل',notes:''}

export default function EditOfferPage(){
  const { candidateId } = useParams<{candidateId:string}>(); const router=useRouter(); const [candidate,setCandidate]=useState<any>(null); const [request,setRequest]=useState<any>(null); const [form,setForm]=useState(initial); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
  const set=(key:string,value:string)=>setForm((p:any)=>({...p,[key]:value}))
  const total=useMemo(()=>{const a=Number(form.salary)||0,b=Number(form.housing_allowance)||0,c=Number(form.transportation_allowance)||0,d=Number(form.other_allowances)||0;return a+b+c+d},[form.salary,form.housing_allowance,form.transportation_allowance,form.other_allowances])
  useEffect(()=>{(async()=>{const {data:a,error}=await supabase.from('candidate_hiring_approvals').select('*').eq('candidate_id',candidateId).single();if(error||!a){setMessage('تعذر العثور على العرض.');setLoading(false);return}const [{data:c},{data:r}]=await Promise.all([supabase.from('candidates').select('id,full_name,phone,request_id').eq('id',candidateId).single(),supabase.from('requests').select('id,exact_type').eq('id',a.request_id).single()]);setCandidate(c);setRequest(r);setForm({...initial,...Object.fromEntries(Object.keys(initial).map(k=>[k,a[k]??initial[k]])),salary:a.salary||'',total_salary:a.total_salary??''});setLoading(false)})()},[candidateId])
  const save=async()=>{setSaving(true);setMessage('');const payload:any={...form,salary:form.salary||null,start_date:form.start_date||null,issue_date:form.issue_date||null,housing_allowance:form.housing_allowance||null,transportation_allowance:form.transportation_allowance||null,other_allowances:form.other_allowances||null,total_salary:form.total_salary||String(total),notes:form.notes||null};const {error}=await supabase.from('candidate_hiring_approvals').update(payload).eq('candidate_id',candidateId);if(error)setMessage(`تعذر حفظ العرض: ${error.message}`);else{setMessage('تم حفظ العرض الوظيفي بالنموذج الرسمي.');setTimeout(()=>router.push('/offers'),700)}setSaving(false)}
  if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center">جاري تحميل العرض...</main>
  const field=(key:string,label:string,type='text',placeholder='')=><div><label className="block font-bold mb-2">{label}</label><input type={type} value={(form as any)[key]??''} onChange={e=>set(key,e.target.value)} placeholder={placeholder} className="w-full border rounded-xl px-4 py-3"/></div>
  return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-5xl mx-auto"><header className="flex items-center justify-between gap-4 mb-6"><div><div className="text-[#b88618] font-bold">العرض الوظيفي الرسمي</div><h1 className="text-3xl font-black text-[#09233f]">{candidate?.full_name||'عرض وظيفي'}</h1><p className="text-slate-500 mt-1">{request?.exact_type||form.job_title||'—'}</p></div><Link href="/offers" className="border rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><ArrowRight size={17}/> العروض</Link></header>
  <section className="card p-6 md:p-8 space-y-7"><div><h2 className="text-xl font-black text-[#09233f] mb-4">بيانات الإصدار والوظيفة</h2><div className="grid md:grid-cols-3 gap-4">{field('offer_number','رقم العرض')}{field('issue_date','تاريخ الإصدار','date')}{field('start_date','تاريخ المباشرة','date')}{field('job_title','المسمى الوظيفي')}{field('department','الإدارة / القسم')}{field('project_name','المشروع')}{field('work_location','موقع العمل')}{field('work_hours','ساعات العمل')}{field('work_days','أيام العمل')}{field('employer_representative','ممثل الشركة')}</div></div>
  <div><h2 className="text-xl font-black text-[#09233f] mb-4">الحزمة المالية</h2><div className="grid md:grid-cols-4 gap-4">{field('salary','الراتب الأساسي','number')}{field('housing_allowance','بدل السكن','number')}{field('transportation_allowance','بدل النقل','number')}{field('other_allowances','بدلات أخرى','number')}{field('total_salary','إجمالي الراتب','number',String(total))}</div></div>
  <div><h2 className="text-xl font-black text-[#09233f] mb-4">المزايا والشروط</h2><div className="grid md:grid-cols-2 gap-4">{field('annual_leave','الإجازة السنوية')}{field('probation_period','فترة التجربة')}{field('health_insurance','التأمين الطبي')}{field('gosi','التأمينات الاجتماعية')}{field('bonus','المكافآت')}{field('performance_bonus','مكافأة الأداء')}{field('termination_notice','إنهاء العقد / الإشعار')}{field('offer_validity','صلاحية العرض')}{field('contract_type','نوع العقد')}</div></div>
  <div><h2 className="text-xl font-black text-[#09233f] mb-4">البنود القانونية والإقرار</h2><div className="grid gap-4">{['confidentiality','intellectual_property'].map(k=><div key={k}><label className="block font-bold mb-2">{k==='confidentiality'?'السرية':'الملكية الفكرية / عدم المنافسة'}</label><textarea rows={4} value={(form as any)[k]} onChange={e=>set(k,e.target.value)} className="w-full border rounded-xl px-4 py-3"/></div>)}<div><label className="block font-bold mb-2">ملاحظات</label><textarea rows={5} value={form.notes} onChange={e=>set('notes',e.target.value)} className="w-full border rounded-xl px-4 py-3"/></div></div></div>
  <div className="flex gap-3"><button disabled={saving} onClick={save} className="btn-primary rounded-xl px-7 py-3 font-bold inline-flex items-center gap-2"><CheckCircle2 size={18}/>{saving?'جاري الحفظ...':'حفظ العرض الرسمي'}</button><Link href="/offers" className="border rounded-xl px-6 py-3 font-bold">إلغاء</Link></div>{message&&<div className="p-4 rounded-xl bg-slate-50 font-bold">{message}</div>}</section></div></main>
}
