'use client'
import {useEffect,useRef,useState} from 'react'
import {Save,Printer} from 'lucide-react'

function Sig({value,onChange}:{value:string;onChange:(v:string)=>void}){
 const ref=useRef<HTMLCanvasElement>(null)
 useEffect(()=>{const c=ref.current;if(!c)return;const x=c.getContext('2d');if(!x)return;x.clearRect(0,0,c.width,c.height);if(value){const i=new Image();i.onload=()=>x.drawImage(i,0,0,c.width,c.height);i.src=value}},[value])
 useEffect(()=>{const c=ref.current;if(!c)return;const x=c.getContext('2d');if(!x)return;x.lineWidth=2;x.lineCap='round';let down=false;const pos=(e:PointerEvent)=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};const start=(e:PointerEvent)=>{down=true;const p=pos(e);x.beginPath();x.moveTo(p.x,p.y)};const move=(e:PointerEvent)=>{if(!down)return;const p=pos(e);x.lineTo(p.x,p.y);x.stroke()};const end=()=>{if(down){down=false;onChange(c.toDataURL('image/png'))}};c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);window.addEventListener('pointerup',end);return()=>{c.removeEventListener('pointerdown',start);c.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end)}},[onChange])
 return <div><canvas ref={ref} width={700} height={140} className="w-full h-28 border rounded-lg touch-none bg-white"/><button type="button" onClick={()=>onChange('')} className="text-xs text-red-700 mt-1">مسح التوقيع</button></div>
}
export default function AdvanceEmployeePublic({token}:{token:string}){
 const [data,setData]=useState<any>(null),[form,setForm]=useState<any>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const load=async()=>{setLoading(true);const r=await fetch('/api/forms/public/'+token,{cache:'no-store'});const x=await r.json();if(r.ok){setData(x);setForm(x.record?.form_data||{})}else setMsg(x.error||'تعذر فتح الرابط');setLoading(false)}
 useEffect(()=>{void load()},[token])
 const employee=data?.data?.employee||{}
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}))
 const save=async()=>{if(!form.amount||!form.employee_name||!form.employee_date||!form.employee_signature){setMsg('يجب إدخال مبلغ السلفة واسم الموظف والتاريخ والتوقيع قبل الحفظ.');return}setBusy(true);const r=await fetch('/api/forms/public/'+token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form,device_name:navigator.userAgent})});const x=await r.json();setBusy(false);setMsg(r.ok?'تم إرسال طلب السلفة بنجاح، ولا يمكن تعديل رابط الموظف بعد الإرسال.':x.error||'تعذر الحفظ');if(r.ok)await load()}
 if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center">جارٍ تحميل طلب السلفة...</main>
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5"><section className="max-w-[210mm] min-h-[297mm] mx-auto bg-white p-[10mm] shadow-sm"><header className="text-center border-b-2 border-[#b88618] pb-4"><h1 className="text-2xl font-black text-[#09233f]">طلب سلفة مالية</h1><div className="font-bold text-[#b88618]">SALARY ADVANCE REQUEST</div><div className="text-xs text-slate-500 mt-2">رابط الموظف — تعبئة مبلغ السلفة والتوقيع</div></header>
 <h3 className="mt-5 border-y border-[#b88618] py-2 font-black">بيانات الموظف</h3><div className="grid grid-cols-2 gap-3 mt-3">{[['اسم الموظف',employee.full_name],['الرقم الوظيفي',employee.employee_number],['الجنسية',employee.nationality],['الهوية / الإقامة',employee.national_id],['الجوال',employee.phone],['البريد الإلكتروني',employee.email],['الإدارة / القسم',employee.department],['المسمى الوظيفي',employee.job_title],['المشروع / الموقع',employee.project_name||employee.work_location],['تاريخ التعيين',employee.hire_date],['الراتب الأساسي',employee.basic_salary],['بدل السكن',employee.housing_allowance],['بدل النقل',employee.transportation_allowance],['إجمالي الراتب',employee.total_salary_with_allowances]].map(([k,v])=><div key={String(k)} className="border-b p-2"><span className="text-xs text-slate-500 block">{k}</span><b>{v||'—'}</b></div>)}</div>
 <fieldset disabled={!!data?.link?.locked} className="mt-5"><h3 className="border-y border-[#b88618] py-2 font-black">بيانات السلفة وإقرار الموظف</h3><div className="grid grid-cols-2 gap-4 mt-4"><label className="font-bold">مبلغ السلفة *<input type="number" min="0" className="w-full border-b p-2" value={form.amount||''} onChange={e=>set('amount',e.target.value)}/></label><label className="font-bold">عدد الأقساط<input type="number" min="1" className="w-full border-b p-2" value={form.installments||''} onChange={e=>set('installments',e.target.value)}/></label><label className="font-bold">تاريخ الطلب<input type="date" className="w-full border-b p-2" value={form.request_date||''} onChange={e=>set('request_date',e.target.value)}/></label><label className="font-bold">طريقة السداد<select className="w-full border-b p-2" value={form.repayment||''} onChange={e=>set('repayment',e.target.value)}><option value="">اختر...</option><option>خصم من الراتب</option><option>تحويل بنكي</option><option>أخرى</option></select></label></div><label className="font-bold block mt-4">سبب السلفة<textarea className="w-full border rounded-lg p-2 mt-1 min-h-20" value={form.reason||''} onChange={e=>set('reason',e.target.value)}/></label><label className="font-bold block mt-3">ملاحظات<textarea className="w-full border rounded-lg p-2 mt-1 min-h-16" value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></label><div className="grid grid-cols-2 gap-4 mt-4"><label className="font-bold">اسم الموظف *<input className="w-full border-b p-2" value={form.employee_name||employee.full_name||''} onChange={e=>set('employee_name',e.target.value)}/></label><label className="font-bold">التاريخ *<input type="date" className="w-full border-b p-2" value={form.employee_date||''} onChange={e=>set('employee_date',e.target.value)}/></label></div><div className="mt-4"><b>توقيع الموظف *</b><Sig value={form.employee_signature||''} onChange={v=>set('employee_signature',v)}/></div></fieldset>
 {data?.link?.locked&&<div className="mt-5 bg-slate-100 p-3 rounded-lg font-bold text-center">تم إرسال الطلب ولا يمكن تعديله.</div>}{msg&&<div className="mt-4 bg-emerald-50 text-emerald-800 p-3 rounded-lg font-bold text-center">{msg}</div>}<div className="mt-5 flex gap-2 print:hidden">{!data?.link?.locked&&<button disabled={busy} onClick={save} className="bg-[#09233f] text-white rounded-xl px-6 py-2 font-bold"><Save size={17} className="inline ml-1"/>حفظ وإرسال الطلب</button>}<button onClick={()=>window.print()} className="bg-[#b88618] text-white rounded-xl px-6 py-2 font-bold"><Printer size={17} className="inline ml-1"/>طباعة</button></div></section></main>
}
