'use client'
import {useEffect,useState} from 'react'
import {Printer,ArrowLeft} from 'lucide-react'
import Link from 'next/link'
const arr=(v:any)=>Array.isArray(v)?v:[]
const money=(v:any)=>v===null||v===undefined||v===''?'—':Number(v).toLocaleString('ar-SA')
function Field({label,value}:{label:string,value:any}){return <div className="border-b py-2"><span className="font-bold">{label}: </span>{value??'—'}</div>}
export default function EmployeePrint({params}:{params:Promise<{id:string}>}){
 const[id,setId]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState('')
 useEffect(()=>{params.then(p=>setId(p.id))},[params]);useEffect(()=>{if(!id)return;fetch('/api/employees/'+id+'/full',{cache:'no-store'}).then(r=>r.json()).then(b=>{if(b.error)setError(b.error);else setData(b)})},[id])
 if(error)return <main dir="rtl" className="p-10 text-center text-red-700">{error}</main>
 if(!data)return <main dir="rtl" className="p-10 text-center">جاري تجهيز الملف الكامل للطباعة...</main>
 const e=data.employee,j=data.job_description,forms=data.forms||[],invest=data.investigations||[],docs=data.documents||[],evals=data.evaluations||[]
 return <main dir="rtl" className="bg-slate-100 min-h-screen p-4 md:p-8 text-[#09233f]"><div className="max-w-5xl mx-auto"><div className="no-print flex justify-between mb-4"><Link href={'/employees/'+id} className="font-bold inline-flex gap-2"><ArrowLeft size={18}/> العودة للملف</Link><button onClick={()=>window.print()} className="bg-[#09233f] text-white rounded-xl px-5 py-2 font-bold inline-flex gap-2"><Printer size={18}/> طباعة</button></div>
 <article className="bg-white p-8 md:p-12 print:p-8"><header className="text-center border-b-2 border-[#b88618] pb-5"><div className="text-xl font-black">شركة البنية الأساسية للمقاولات</div><h1 className="text-2xl font-black mt-3">الملف الشامل للموظف</h1><div className="text-sm mt-2">خاص وسري</div></header>
 <section className="mt-6"><h2 className="font-black text-xl border-r-4 border-[#b88618] pr-3">1. البيانات الشخصية والوظيفية</h2><div className="grid md:grid-cols-2 gap-x-8 mt-3"><Field label="الاسم" value={e.full_name}/><Field label="الرقم الوظيفي" value={e.employee_number}/><Field label="الجنسية" value={e.nationality}/><Field label="الهوية / الإقامة" value={e.national_id}/><Field label="الجوال" value={e.phone}/><Field label="البريد" value={e.email}/><Field label="المؤهل" value={e.degree}/><Field label="التخصص" value={e.specialization}/><Field label="الإدارة" value={e.department}/><Field label="المسمى الوظيفي" value={e.job_title}/><Field label="المشروع" value={e.project_name}/><Field label="موقع العمل" value={e.work_location}/><Field label="المدير المباشر" value={e.manager_name}/><Field label="تاريخ التعيين" value={e.hire_date}/><Field label="نوع العقد" value={e.contract_type}/><Field label="الحالة الوظيفية" value={e.employment_status}/><Field label="حالة الإقامة / الكفالة" value={e.residency_status}/></div></section>
 <section className="mt-7"><h2 className="font-black text-xl border-r-4 border-[#b88618] pr-3">2. الراتب والبدلات</h2><div className="grid md:grid-cols-2 gap-x-8 mt-3"><Field label="الراتب الأساسي" value={money(e.basic_salary)}/><Field label="بدل السكن" value={money(e.housing_allowance)}/><Field label="بدل النقل" value={money(e.transportation_allowance)}/><Field label="بدلات أخرى" value={money(e.other_allowances)}/><Field label="إجمالي الراتب" value={money(e.total_salary_with_allowances)}/><Field label="الراتب المسجل" value={e.salary}/></div></section>
 {j&&<section className="mt-7"><h2 className="font-black text-xl border-r-4 border-[#b88618] pr-3">3. الوصف الوظيفي والمهام</h2><div className="mt-3"><Field label="المسمى" value={j.name}/><Field label="الإدارة" value={j.department}/><Field label="الغرض من الوظيفة" value={j.purpose}/><h3 className="font-black mt-4">المهام والمسؤوليات</h3><ul className="mt-2 space-y-1">{arr(j.responsibilities).map((x:any,i:number)=><li key={i}>• {String(x)}</li>)}</ul><h3 className="font-black mt-4">المؤهلات والمهارات</h3><ul className="mt-2 space-y-1">{arr(j.qualifications).concat(arr(j.skills)).map((x:any,i:number)=><li key={i}>• {String(x)}</li>)}</ul></div></section>}
 <section className="mt-7"><h2 className="font-black text-xl border-r-4 border-[#b88618] pr-3">4. المستندات</h2>{docs.length?<div className="mt-3 space-y-2">{docs.map((d:any)=><div key={d.id} className="border rounded-lg p-3"><b>{d.document_name}</b> — {d.document_type} — رقم: {d.document_number||'—'} — الإصدار: {d.issue_date||'—'} — الانتهاء: {d.expiry_date||'—'} — {d.status||'—'}</div>)}</div>:<p className="mt-3 text-slate-500">لا توجد مستندات مسجلة.</p>}</section>
 <section className="mt-7"><h2 className="font-black text-xl border-r-4 border-[#b88618] pr-3">5. الإجازات والخصومات والنماذج والسجلات</h2>{forms.length?<div className="mt-3 space-y-3">{forms.map((f:any)=><div key={f.id} className="border rounded-lg p-3"><div className="font-black">{f.form_type||'نموذج'} — {f.status||'—'}</div><div className="text-sm text-slate-500">التاريخ: {f.created_at?new Date(f.created_at).toLocaleDateString('ar-SA'):'—'}</div><pre className="mt-2 whitespace-pre-wrap text-xs font-sans">{JSON.stringify(f.form_data||{},null,2)}</pre></div>)}</div>:<p className="mt-3 text-slate-500">لا توجد سجلات نماذج.</p>}</section>
 <section className="mt-7"><h2 className="font-black text-xl border-r-4 border-[#b88618] pr-3">6. التحقيقات الإدارية</h2>{invest.length?<div className="mt-3 space-y-3">{invest.map((x:any)=><div key={x.id} className="border rounded-lg p-4"><div className="font-black">{x.subject}</div><div className="text-sm mt-1">الحالة: {x.status||'—'} • التاريخ: {x.created_at?new Date(x.created_at).toLocaleDateString('ar-SA'):'—'}</div>{x.management_opinion&&<div className="mt-2"><b>رأي الإدارة:</b> {x.management_opinion}</div>}{x.final_analysis&&<pre className="mt-2 whitespace-pre-wrap text-xs font-sans">{JSON.stringify(x.final_analysis,null,2)}</pre>}</div>)}</div>:<p className="mt-3 text-slate-500">لا توجد تحقيقات مسجلة.</p>}</section>
 <section className="mt-7"><h2 className="font-black text-xl border-r-4 border-[#b88618] pr-3">7. تقييمات الأداء</h2>{evals.length?<div className="mt-3 space-y-3">{evals.map((x:any)=><div key={x.id} className="border rounded-lg p-3"><b>التقييم:</b> {x.performance_level||'—'} • الدرجة: {x.total_score??'—'} • التاريخ: {x.evaluation_date||'—'}<div className="mt-2">{x.strengths&&<div><b>نقاط القوة:</b> {x.strengths}</div>}{x.improvements&&<div><b>التحسين:</b> {x.improvements}</div>}{x.recommendations&&<div><b>التوصيات:</b> {x.recommendations}</div>}</div></div>)}</div>:<p className="mt-3 text-slate-500">لا توجد تقييمات مسجلة.</p>}</section>
 {e.notes&&<section className="mt-7"><h2 className="font-black text-xl border-r-4 border-[#b88618] pr-3">8. ملاحظات</h2><p className="mt-3 whitespace-pre-wrap">{e.notes}</p></section>}
 <footer className="mt-12 pt-4 border-t text-xs text-slate-500 flex justify-between"><span>شركة البنية الأساسية للمقاولات</span><span>تاريخ الطباعة: {new Date().toLocaleDateString('ar-SA')}</span></footer>
 </article></div><style jsx global>{`@media print{body{background:white!important}.no-print{display:none!important}article{box-shadow:none!important}section{break-inside:avoid}}`}</style></main>
}