import { NextResponse } from 'next/server'
import { GoogleGenAI } from '@google/genai'
import { getSuggestedRequirements, REQUEST_REQUIREMENTS } from '@/lib/request-requirements'

type Requirement = { name: string; category: string; required: boolean; source?: string }

function normalize(value: string) { return value.normalize('NFKC').replace(/[ًٌٍَُِّْـ]/g, '').replace(/[إأآ]/g, 'ا').replace(/ة/g, 'ه').replace(/\s+/g, ' ').trim().toLocaleLowerCase('ar') }
function unique(items: Requirement[]) { const seen=new Set<string>(); return items.filter(x=>{const key=normalize(x.name);if(!key||seen.has(key))return false;seen.add(key);return true}) }
function local(job:string):Requirement[]{ const direct=getSuggestedRequirements(job); if(direct.length)return direct.map(x=>({...x,required:Boolean(x.required),source:'مكتبة متطلبات الوظائف'})); const key=Object.keys(REQUEST_REQUIREMENTS).find(k=>normalize(k)===normalize(job)); return key?REQUEST_REQUIREMENTS[key].map(x=>({...x,required:Boolean(x.required),source:'مكتبة متطلبات الوظائف'})):[] }

function fallback(job:string):Requirement[]{
 const j=normalize(job)
 const common:Requirement[]=[{name:'المؤهل العلمي المناسب لطبيعة الوظيفة',category:'مؤهل',required:true},{name:'خبرة عملية مرتبطة مباشرة بالمسمى الوظيفي',category:'خبرة',required:true},{name:'إجادة مهام الوظيفة الأساسية وفق الوصف الوظيفي',category:'مهارة فنية',required:true},{name:'الالتزام بالأنظمة والتعليمات وإجراءات الشركة',category:'تشغيل',required:true},{name:'القدرة على إعداد التقارير والمتابعة والتنسيق',category:'إدارة',required:false},{name:'إجادة استخدام الحاسب والبرامج المكتبية ذات الصلة',category:'برنامج',required:false}]
 if(/مهندس|هندسي|مدني|معماري|كهرباء|ميكانيكا|تكييف|طرق|مياه|سلامة|جودة|مكتب فني|مساح|كميات/.test(j)) common.push({name:'قراءة وفهم المخططات والمواصفات الفنية المرتبطة بالتخصص',category:'مهارة فنية',required:true},{name:'AutoCAD وExcel أو البرامج الفنية المستخدمة في التخصص',category:'برنامج هندسي',required:false})
 if(/مشتريات|مورد|سلسلة امداد|لوجست/.test(j)) common.push({name:'إدارة طلبات الشراء وعروض الأسعار ومقارنة الموردين',category:'مشتريات',required:true},{name:'التفاوض ومتابعة التوريد والاستلام',category:'مشتريات',required:true})
 if(/محاسب|محاسبه|مالي|مالية|تكاليف/.test(j)) common.push({name:'إعداد القيود والتسويات والمطابقات والتقارير المالية',category:'محاسبة',required:true},{name:'إجادة Excel والأنظمة المحاسبية',category:'برنامج',required:true})
 if(/موارد بشرية|توظيف|رواتب|شؤون موظفين|hr/.test(j)) common.push({name:'معرفة أنظمة العمل واللوائح السعودية وإجراءات الموارد البشرية',category:'موارد بشرية',required:true},{name:'إدارة ملفات الموظفين والعقود والإجازات والحضور',category:'موارد بشرية',required:true})
 if(/مبيعات|تسويق|تطوير اعمال|علاقات عامة/.test(j)) common.push({name:'مهارات التواصل والتفاوض وإدارة العملاء',category:'مبيعات',required:true},{name:'تحقيق المستهدفات وإعداد تقارير المبيعات أو التسويق',category:'أداء',required:true})
 if(/سائق|مشغل|عامل|فني/.test(j)) common.push({name:'خبرة في بيئة العمل والموقع المرتبط بالوظيفة',category:'خبرة',required:true},{name:'رخصة أو تصريح تشغيل ساري عند اشتراطه للوظيفة',category:'اعتماد',required:false})
 return unique(common.map(x=>({...x,source:'مكتبة متطلبات مهنية احتياطية حسب عائلة المسمى'})))
}

async function aiRequirements(job:string,type:string):Promise<Requirement[]>{ const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return[];try{const ai=new GoogleGenAI({apiKey});const prompt=`أنت خبير موارد بشرية في شركة مقاولات سعودية. أعد متطلبات مهنية دقيقة للمسمى المحدد فقط: "${job}". لا تستبدل المسمى بمهنة قريبة. نوع الطلب: "${type}". أرجع 6-10 متطلبات عربية مهنية بصيغة JSON array فقط، منها المؤهل والخبرة والمهارات والبرامج الخاصة بالمهنة عند الحاجة، واجعل 2-4 متطلبات أساسية required=true.`;const response=await ai.models.generateContent({model:'gemini-3.6-flash',contents:prompt});const text=(response.text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'').trim();const parsed=JSON.parse(text);if(!Array.isArray(parsed))return[];return parsed.map((x:any)=>({name:String(x.name||'').trim(),category:String(x.category||'عام').trim(),required:Boolean(x.required),source:'محرك المعايير المهنية الذكي'})).filter(x=>x.name.length>2)}catch{return[]}}

export async function GET(req:Request){ const {searchParams}=new URL(req.url);const job=(searchParams.get('job')||'').trim();const type=(searchParams.get('type')||'توظيف').trim();const occupationCode=(searchParams.get('code')||'').trim();if(!job)return NextResponse.json({requirements:[],source:'none'});const exact=local(job);if(exact.length)return NextResponse.json({requirements:unique(exact),source:'exact-local-profile',searchedJob:job,occupationCode,searchedType:type,matchedOccupation:job});const generated=await aiRequirements(job,type);if(generated.length)return NextResponse.json({requirements:unique(generated),source:'ai-exact-occupation-profile',searchedJob:job,occupationCode,searchedType:type,matchedOccupation:job});const backup=fallback(job);return NextResponse.json({requirements:backup,source:'professional-family-fallback',searchedJob:job,occupationCode,searchedType:type,matchedOccupation:job,note:'تم تحميل متطلبات مهنية احتياطية مرتبطة بعائلة المسمى المحدد، دون استخدام متطلبات وظيفة أخرى.'}) }
