export type SuggestedRequirement = {
  name: string
  category: string
  required?: boolean
}

export const REQUEST_REQUIREMENTS: Record<string, SuggestedRequirement[]> = {
  'مهندس مشاريع': [
    { name: 'بكالوريوس هندسة مدنية أو تخصص مناسب', category: 'مؤهل', required: true },
    { name: 'خبرة في إدارة وتنفيذ مشاريع المقاولات', category: 'خبرة', required: true },
    { name: 'قراءة وفهم المخططات التنفيذية', category: 'مهارة فنية', required: true },
    { name: 'إدارة فرق العمل والمقاولين', category: 'إدارة', required: true },
    { name: 'إعداد ومراجعة المستخلصات وحصر الكميات', category: 'مهارة فنية' },
    { name: 'إعداد التقارير ومتابعة البرنامج الزمني', category: 'إدارة' },
    { name: 'AutoCAD وExcel', category: 'برنامج هندسي' },
    { name: 'السلامة والجودة في مواقع الإنشاء', category: 'تشغيل' },
  ],
  'مهندس مكتب فني': [
    { name: 'بكالوريوس هندسة مدنية أو معمارية حسب التخصص', category: 'مؤهل', required: true },
    { name: 'خبرة في أعمال المكتب الفني بالمقاولات', category: 'خبرة', required: true },
    { name: 'إعداد ومراجعة Shop Drawings', category: 'مهارة فنية', required: true },
    { name: 'حصر الكميات وQuantity Take-off', category: 'مهارة فنية', required: true },
    { name: 'إعداد ومراجعة BOQ والمستخلصات', category: 'مهارة فنية', required: true },
    { name: 'RFIs وMaterial Submittals وAs-Built', category: 'مهارة فنية' },
    { name: 'AutoCAD وExcel', category: 'برنامج هندسي', required: true },
    { name: 'Revit / BIM', category: 'برنامج هندسي' },
  ],
  'مهندس مشروع': [
    { name: 'بكالوريوس هندسة', category: 'مؤهل', required: true },
    { name: 'خبرة في تنفيذ وإدارة المشاريع', category: 'خبرة', required: true },
    { name: 'قراءة المخططات ومتابعة التنفيذ بالموقع', category: 'مهارة فنية', required: true },
    { name: 'حصر الكميات ومتابعة المواد', category: 'مهارة فنية' },
    { name: 'إدارة المقاولين والعمالة', category: 'إدارة' },
    { name: 'إعداد التقارير اليومية والأسبوعية', category: 'إدارة' },
    { name: 'AutoCAD وExcel', category: 'برنامج هندسي' },
  ],
  'مهندس مشتريات': [
    { name: 'بكالوريوس هندسة أو إدارة مشتريات مناسبة', category: 'مؤهل', required: true },
    { name: 'خبرة في مشتريات مواد ومعدات المقاولات', category: 'خبرة', required: true },
    { name: 'قراءة المواصفات والمخططات وحصر الاحتياج', category: 'مهارة فنية' },
    { name: 'طلب عروض الأسعار ومقارنة الموردين', category: 'مشتريات', required: true },
    { name: 'التفاوض ومتابعة التوريد والتسليم', category: 'مشتريات', required: true },
    { name: 'Excel وإعداد جداول المقارنة', category: 'برنامج' },
    { name: 'رخصة قيادة', category: 'متطلبات عامة' },
  ],
  'محاسب موقع': [
    { name: 'بكالوريوس محاسبة', category: 'مؤهل', required: true },
    { name: 'خبرة في محاسبة مواقع المقاولات', category: 'خبرة', required: true },
    { name: 'إدارة المصروفات والعهد والمستندات المالية', category: 'محاسبة', required: true },
    { name: 'مطابقة الفواتير والمستخلصات', category: 'محاسبة' },
    { name: 'إعداد التقارير والحركة النقدية للموقع', category: 'محاسبة' },
    { name: 'Excel والأنظمة المحاسبية', category: 'برنامج' },
  ],
  'مسؤول حركة': [
    { name: 'خبرة في إدارة حركة السيارات والمعدات', category: 'خبرة', required: true },
    { name: 'متابعة السائقين والمركبات والمعدات', category: 'تشغيل', required: true },
    { name: 'تنظيم الإيجارات والتشغيل والصيانة', category: 'تشغيل', required: true },
    { name: 'إعداد تقارير الحركة اليومية', category: 'إدارة' },
    { name: 'رخصة قيادة سارية', category: 'متطلبات عامة', required: true },
  ],
  'مدخل بيانات': [
    { name: 'إجادة إدخال البيانات بسرعة ودقة', category: 'مهارة', required: true },
    { name: 'إجادة Excel وWord', category: 'برنامج', required: true },
    { name: 'تنظيم الملفات والمستندات', category: 'إدارة' },
    { name: 'دقة ومراجعة البيانات', category: 'مهارة', required: true },
    { name: 'العمل على أنظمة الموارد البشرية أو ERP', category: 'برنامج' },
  ],
  'موارد بشرية': [
    { name: 'بكالوريوس موارد بشرية أو إدارة أعمال', category: 'مؤهل', required: true },
    { name: 'خبرة في إدارة شؤون الموظفين والتوظيف', category: 'خبرة', required: true },
    { name: 'إجادة أنظمة العمل واللوائح السعودية', category: 'أنظمة', required: true },
    { name: 'إدارة ملفات الموظفين والعقود والإجازات', category: 'موارد بشرية', required: true },
    { name: 'إجراء المقابلات وتقييم المرشحين', category: 'توظيف' },
    { name: 'Excel وأنظمة HR', category: 'برنامج' },
  ],
  'مدير مشاريع': [
    { name: 'بكالوريوس هندسة مدنية أو عمارة أو إدارة مشاريع', category: 'مؤهل', required: true },
    { name: 'شهادة احترافية PMP أو ما يعادلها', category: 'اعتماد' },
    { name: 'خبرة سابقة لا تقل عن 7 سنوات في إدارة مشاريع المقاولات', category: 'خبرة', required: true },
    { name: 'إدارة الموازنات وضبط التكاليف والجداول الزمنية', category: 'إدارة', required: true },
    { name: 'التعامل مع الاستشاري والمالك والجهات المعنية', category: 'إدارة', required: true },
    { name: 'القيادة وإدارة الفرق والمقاولين الباطن', category: 'إدارة' },
    { name: 'إجادة برامج إدارة المشاريع مثل Primavera P6 وMS Project', category: 'برنامج' },
  ],
  'مهندس مدني': [
    { name: 'بكالوريوس في الهندسة المدنية معتمد من الهيئة السعودية للمهندسين', category: 'مؤهل', required: true },
    { name: 'خبرة عملية في الإشراف على أعمال التنفيذ بالموقع والخرسانات', category: 'خبرة', required: true },
    { name: 'قراءة المخططات الإنشائية والمعمارية وحصر الكميات', category: 'مهارة فنية', required: true },
    { name: 'متابعة استلام الأعمال ومطابقة المواصفات وجودة التنفيذ', category: 'مهارة فنية', required: true },
    { name: 'إجادة برامج AutoCAD وتطبيقات الهندسة المدنية', category: 'برنامج هندسي' },
    { name: 'الالتزام بمعايير السلامة المهنية والصحة بالمواقع', category: 'سلامة' },
  ],
  'مهندس معماري': [
    { name: 'بكالوريوس هندسة معمارية معتمد من الهيئة السعودية للمهندسين', category: 'مؤهل', required: true },
    { name: 'خبرة في أعمال التشطيبات المعمارية والمخططات التنفيذية', category: 'خبرة', required: true },
    { name: 'إتقان برامج AutoCAD وRevit أو SketchUp', category: 'برنامج هندسي', required: true },
    { name: 'مراجعة المخططات المعمارية ومطابقتها مع الإنشائي والكهروميكانيك', category: 'مهارة فنية', required: true },
    { name: 'متابعة المواد المعتمدة والعينات في الموقع', category: 'مهارة فنية' },
  ],
  'مهندس كهرباء': [
    { name: 'بكالوريوس هندسة كهربائية معتمد من الهيئة السعودية للمهندسين', category: 'مؤهل', required: true },
    { name: 'خبرة في شبكات القوى والإنارة والتيار الخفيف بالمشاريع', category: 'خبرة', required: true },
    { name: 'قراءة المخططات الكهربائية وإعداد لوحات التوزيع Shop Drawings', category: 'مهارة فنية', required: true },
    { name: 'الإشراف على التمديدات والكابلات والفحص والاختبار', category: 'مهارة فنية', required: true },
    { name: 'إتقان برامج AutoCAD والحسابات الكهربائية', category: 'برنامج هندسي' },
  ],
  'مهندس ميكانيكا': [
    { name: 'بكالوريوس هندسة ميكانيكية معتمد من الهيئة السعودية للمهندسين', category: 'مؤهل', required: true },
    { name: 'خبرة في أنظمة التكييف HVAC ومكافحة الحريق والصحي', category: 'خبرة', required: true },
    { name: 'قراءة وتدقيق المخططات الميكانيكية وإعداد الرسومات التنفيذية', category: 'مهارة فنية', required: true },
    { name: 'الإشراف على التركيبات واختبارات الضغط والتشغيل', category: 'مهارة فنية', required: true },
    { name: 'إجادة برامج AutoCAD وحسابات الأحمال الحرارية HAP', category: 'برنامج هندسي' },
  ],
  'مهندس تخطيط': [
    { name: 'بكالوريوس هندسة مدنية أو صناعية أو إدارة تشييد', category: 'مؤهل', required: true },
    { name: 'إتقان تام لبرنامج Primavera P6 وإعداد الجداول الزمنية', category: 'برنامج هندسي', required: true },
    { name: 'خبرة في متابعة نسب الإنجاز والمسار الحرج وتحديث البرامج', category: 'مهارة فنية', required: true },
    { name: 'إعداد تقارير S-Curve وتحليل القيمة المكتسبة EVM والتأخيرات', category: 'إدارة', required: true },
    { name: 'إجادة متقدمة لبرنامج Excel', category: 'برنامج' },
  ],
  'مهندس جودة': [
    { name: 'بكالوريوس هندسة واعتماد الهيئة السعودية للمهندسين', category: 'مؤهل', required: true },
    { name: 'خبرة في مراقبة وتأكيد الجودة QA/QC لمشاريع البناء', category: 'خبرة', required: true },
    { name: 'إعداد ومتابعة خطة الجودة PQP ونماذج الفحص ITP وMIR وWIR', category: 'مهارة فنية', required: true },
    { name: 'متابعة تقارير عدم المطابقة NCR والإجراءات التصحيحية', category: 'مهارة فنية', required: true },
    { name: 'معرفة بمواصفات البناء والكود السعودي للمباني SBC', category: 'أنظمة' },
  ],
  'مهندس سلامة': [
    { name: 'بكالوريوس هندسة أو تخصص سلامة وصحة مهنية معتمد', category: 'مؤهل', required: true },
    { name: 'شهادات احترافية مثل OSHA أو NEBOSH IGC', category: 'اعتماد', required: true },
    { name: 'إعداد خطط السلامة وتقييم المخاطر وتصاريح العمل PTW', category: 'سلامة', required: true },
    { name: 'الإشراف الميداني اليومي والتحقيق في الحوادث وإعداد التقارير', category: 'سلامة', required: true },
    { name: 'تدريب العمالة على إجراءات الطوارئ والسلامة بمواقع الإنشاء', category: 'سلامة' },
  ],
  'مساح': [
    { name: 'دبلوم أو بكالوريوس في المساحة أو الهندسة المدنية', category: 'مؤهل', required: true },
    { name: 'إتقان استخدام أجهزة Total Station وGPS وميزان القامة', category: 'مهارة فنية', required: true },
    { name: 'الرفع والتوقيع المساحي لنقاط ومناسيب المشروع بدقة', category: 'مهارة فنية', required: true },
    { name: 'إجادة برامج AutoCAD Civil 3D وحساب الكميات الترابية', category: 'برنامج هندسي', required: true },
    { name: 'رخصة قيادة سارية', category: 'متطلبات عامة' },
  ],
  'حاسب كميات': [
    { name: 'بكالوريوس هندسة مدنية أو إدارة تشييد أو مساحة كميات', category: 'مؤهل', required: true },
    { name: 'خبرة في حصر الكميات للمشاريع الإنشائية والمعمارية', category: 'مهارة فنية', required: true },
    { name: 'إعداد ومراجعة جداول الكميات BOQ ومستخلصات المالك والمقاولين', category: 'مهارة فنية', required: true },
    { name: 'دراسة أوامر التغيير والتسعير والمطالبات المالية', category: 'مهارة فنية' },
    { name: 'إتقان برامج Excel وAutoCAD وبرامج الحصر', category: 'برنامج', required: true },
  ],
  'مشرف موقع': [
    { name: 'دبلوم فني أو خبرة عملية طويلة ومثبتة في تنفيذ المباني', category: 'مؤهل' },
    { name: 'خبرة في إدارة عمالة الموقع وتوزيع المهام اليومية', category: 'إدارة', required: true },
    { name: 'استلام الأعمال من العمالة ومطابقتها للمخططات وتعليمات المهندس', category: 'تشغيل', required: true },
    { name: 'متابعة توريد المواد والمعدات وحمايتها من الهدر', category: 'تشغيل' },
    { name: 'الالتزام الصارم بتعليمات السلامة في موقع المشروع', category: 'سلامة', required: true },
  ],
  'محاسب': [
    { name: 'بكالوريوس محاسبة أو مالية', category: 'مؤهل', required: true },
    { name: 'خبرة في القيود اليومية والحسابات والترحيل وميزان المراجعة', category: 'محاسبة', required: true },
    { name: 'إجادة العمل على البرامج المحاسبية ERP وأنظمة الفوترة الإلكترونية', category: 'برنامج', required: true },
    { name: 'معرفة بضريبة القيمة المضافة VAT ولوائح هيئة الزكاة والضريبة والجمارك ZATCA', category: 'أنظمة', required: true },
    { name: 'إتقان متقدم لبرنامج Excel ومطابقة كشوف الحسابات البنكية', category: 'برنامج', required: true },
  ],
  'أخصائي موارد بشرية': [
    { name: 'بكالوريوس موارد بشرية أو إدارة أعمال', category: 'مؤهل', required: true },
    { name: 'إلمام تام بنظام العمل والعمال السعودي واللوائح التنفيذية', category: 'أنظمة', required: true },
    { name: 'إتقان التعامل مع منصات قوى، مدد، مقيم، والتأمينات الاجتماعية', category: 'برنامج', required: true },
    { name: 'إدارة عمليات التوظيف والمسيرات والإجازات وملفات الموظفين', category: 'موارد بشرية', required: true },
    { name: 'إعداد التقارير ومتابعة نسب التوطين نطاقات', category: 'موارد بشرية' },
  ],
  'أخصائي مشتريات': [
    { name: 'بكالوريوس في الهندسة أو إدارة الأعمال أو سلاسل الإمداد', category: 'مؤهل', required: true },
    { name: 'خبرة في مشتريات مواد ومعدات المقاولات والإنشاءات', category: 'مشتريات', required: true },
    { name: 'إصدار أوامر الشراء ومقارنة عروض الأسعار والتفاوض مع الموردين', category: 'مشتريات', required: true },
    { name: 'متابعة سلاسل الإمداد والتوريد لمواقع المشاريع بدقة ومواعيدها', category: 'مشتريات', required: true },
    { name: 'إجادة برامج ERP وجداول المقارنة على Excel', category: 'برنامج' },
  ],
  'سائق': [
    { name: 'رخصة قيادة سارية ومناسبة لنوع المركبة', category: 'متطلبات عامة', required: true },
    { name: 'معرفة تامة بالطرق والأنظمة المرورية والسلامة على الطرق', category: 'تشغيل', required: true },
    { name: 'المحافظة على نظافة وصيانة المركبة والفحص الدوري', category: 'تشغيل', required: true },
    { name: 'الالتزام بمواعيد العمل والمسارات المحددة', category: 'سلوك', required: true },
  ],
  'فني كهرباء': [
    { name: 'دبلوم مهني أو شهادة تدريب فني في الكهرباء', category: 'مؤهل', required: true },
    { name: 'خبرة في التمديدات والتركيبات الكهربائية لمشاريع المباني', category: 'مهارة فنية', required: true },
    { name: 'قراءة المخططات الكهربائية وتمديد الأسلاك وتركيب اللوحات', category: 'مهارة فنية', required: true },
    { name: 'الالتزام بتعليمات السلامة والوقاية من المخاطر الكهربائية', category: 'سلامة', required: true },
  ],
  'فني ميكانيكا': [
    { name: 'دبلوم فني أو شهادة مهنية في التكييف أو الميكانيكا', category: 'مؤهل', required: true },
    { name: 'خبرة في أعمال تركيب وصيانة التكييف المركزي والدكت وأنظمة الصرف والمضخات', category: 'مهارة فنية', required: true },
    { name: 'القدرة على قراءة المخططات الميكانيكية والتنفيذ وفق التعليمات', category: 'مهارة فنية', required: true },
    { name: 'الالتزام بقواعد السلامة المهنية', category: 'سلامة', required: true },
  ],
  'مراقب مدني': [
    { name: 'دبلوم كلية تقنية تخصص مدني أو تشييد أو خبرة معادلة', category: 'مؤهل', required: true },
    { name: 'مراقبة أعمال الحفر والخرسانات والعزل والردم بالموقع', category: 'تشغيل', required: true },
    { name: 'التأكد من تنفيذ تعليمات المهندس المشرف واستلام مراحل العمل', category: 'تشغيل', required: true },
    { name: 'إعداد تقارير الحضور وسير الأعمال اليومية', category: 'إدارة' },
    { name: 'مراعاة شروط السلامة في مناطق العمل', category: 'سلامة', required: true },
  ],
  'مراقب معماري': [
    { name: 'دبلوم عمارة أو تشطيبات أو خبرة معادلة', category: 'مؤهل', required: true },
    { name: 'متابعة أعمال البلوك والمحارة والدهانات والجبس والأرضيات', category: 'تشغيل', required: true },
    { name: 'التأكد من مطابقة أعمال التشطيبات للعينات المعتمدة', category: 'تشغيل', required: true },
    { name: 'توجيه العمالة وضبط جودة الاستلام', category: 'تشغيل' },
  ],
  'سكرتير': [
    { name: 'دبلوم أو بكالوريوس في السكرتارية أو إدارة الأعمال', category: 'مؤهل', required: true },
    { name: 'إتقان استخدام برامج Microsoft Office (Word, Excel, Outlook)', category: 'برنامج', required: true },
    { name: 'تنظيم المواعيد والاجتماعات والأرشفة والمراسلات الرسمية', category: 'إدارة', required: true },
    { name: 'مهارات اتصال كتابية وشفهية ممتازة باللغة العربية والإنجليزية', category: 'مهارة', required: true },
  ],
  'تدريب تعاوني': [
    { name: 'خطاب تدريب تعاوني من الجهة التعليمية', category: 'مؤهل', required: true },
    { name: 'تخصص متوافق مع مجال التدريب', category: 'مؤهل', required: true },
    { name: 'الالتزام بالحضور والانضباط', category: 'سلوك', required: true },
    { name: 'القدرة على التعلم والعمل ضمن فريق', category: 'مهارة' },
  ],
  'تدريب صيفي': [
    { name: 'إثبات الدراسة أو خطاب التدريب', category: 'مؤهل', required: true },
    { name: 'تخصص مناسب للفرصة التدريبية', category: 'مؤهل', required: true },
    { name: 'الالتزام بالحضور والانضباط', category: 'سلوك', required: true },
  ],
  'تدريب مهني': [
    { name: 'مؤهل أو برنامج مهني مناسب', category: 'مؤهل', required: true },
    { name: 'مهارات أساسية مرتبطة بالتخصص', category: 'مهارة', required: true },
    { name: 'الالتزام بالتدريب والتعليمات', category: 'سلوك', required: true },
  ],
  'تجربة وظيفية': [
    { name: 'خبرة أو مؤهل مناسب للوظيفة', category: 'مؤهل' },
    { name: 'القدرة على تنفيذ مهام الوظيفة عمليًا', category: 'مهارة', required: true },
    { name: 'الالتزام والانضباط', category: 'سلوك', required: true },
    { name: 'التواصل والعمل ضمن فريق', category: 'مهارة' },
  ],
  'فترة تجربة': [
    { name: 'استيفاء متطلبات الوظيفة الأساسية', category: 'مؤهل', required: true },
    { name: 'القدرة على أداء المهام خلال فترة التجربة', category: 'مهارة', required: true },
    { name: 'الالتزام بالدوام والتعليمات', category: 'سلوك', required: true },
  ],
  'تجربة ميدانية': [
    { name: 'خبرة أو مؤهل مناسب للعمل الميداني', category: 'مؤهل' },
    { name: 'القدرة على العمل في موقع المشروع', category: 'تشغيل', required: true },
    { name: 'الالتزام بالسلامة والتعليمات', category: 'سلامة', required: true },
  ],
  'تقييم موظف': [
    { name: 'جودة أداء المهام الوظيفية', category: 'أداء', required: true },
    { name: 'الالتزام والانضباط', category: 'سلوك', required: true },
    { name: 'التعاون والعمل ضمن الفريق', category: 'سلوك' },
    { name: 'المبادرة وحل المشكلات', category: 'أداء' },
  ],
  'تقييم مرشح': [
    { name: 'مطابقة المؤهل والخبرة لمتطلبات الوظيفة', category: 'مؤهل', required: true },
    { name: 'المهارات الفنية المطلوبة', category: 'مهارة فنية', required: true },
    { name: 'القدرة على التواصل والعمل ضمن فريق', category: 'سلوك' },
    { name: 'نتيجة المقابلة والتقييم العملي', category: 'تقييم', required: true },
  ],
  'تقييم أداء': [
    { name: 'تحقيق أهداف ومؤشرات الأداء', category: 'أداء', required: true },
    { name: 'جودة العمل والإنتاجية', category: 'أداء', required: true },
    { name: 'الالتزام بالسياسات والإجراءات', category: 'سلوك' },
    { name: 'التطور وتحمل المسؤولية', category: 'أداء' },
  ],
}

export const getSuggestedRequirements = (exactType: string): SuggestedRequirement[] => REQUEST_REQUIREMENTS[exactType] || []
