'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {useParams,useRouter} from 'next/navigation'
import {ArrowRight,Save,Trash2,ArrowLeftRight} from 'lucide-react'
import {supabase} from '@/lib/supabase'

const fields=[
 ['full_name','اسم المرشح','text'],['phone','رقم الجوال','text'],['email','البريد الإلكتروني','email'],['city','المدينة','text'],['nationality','الجنسية','text'],['degree','المؤهل','text'],['specialization','التخصص','text'],['university','الجامعة','text'],['graduation_year','سنة التخرج','number'],['total_experience_years','إجمالي سنوات الخبرة','number'],['saudi_experience_years','سنوات الخبرة في السعودية','number'],['previous_experience','الخبرات السابقة','textarea'],['notes','ملاحظات','textarea']
] as const

export default function EditCandidate(){
 const{id,candidateId}=useParams<{id:string;candidateId:string}>();const router=useRouter()
 const[candidate,setCandidate]=useState<any>(null),[requests,setRequests]=useState<any[]>([]),[target,setTarget]=useState(id),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[moving,setMoving]=useState(false),[deleting,setDeleting]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{(async()=>{const[{data:c,error:ce},{data:rs,error:re}]=await Promise.all([supabase.from('candidates').select('*').eq('id',candidateId).single(),supabase.from('requests').select('id,exact_type,request_type,department,status,created_at').order('created_at',{ascending:false})]);if(ce)setError(ce.message);setCandidate(c);setRequests(rs||[]);setTarget(c?.request_id||id);setLoading(false)})()},[candidateId,id])
 const set=(key:string,value:any)=>setCandidate((x:any)=>({...x,[key]:value}))
 const save=async()=>{setSaving(true);setError('');setMessage('');const payload={...Object.fromEntries(fields.map(([k])=>[k,candidate?.[k]??null])),graduation_year:candidate?.graduation_year?Number(candidate.graduation_year):null,total_experience_years:candidate?.total_experience_years!==''&&candidate?.total_experience_years!=null?Number(candidate.total_experience_years):null,saudi_experience_years:candidate?.saudi_experience_years!==''&&candidate?.saudi_experience_years!=null?Number(candidate.saudi_experience_years):null,updated_at:new Date().toISOString()};const{error:e}=await supabase.from('candidates').update(payload).eq('id',candidateId);if(e)setError(e.message);else setMessage('تم حفظ بيانات المرشح بنجاح.');setSaving(false)}
 const move=async()=>{if(!target||target===candidate?.request_id){setMessage('المرشح موجود بالفعل في هذا الطلب.');return}const req=requests.find(r=>r.id===target);if(!req)return;if(!confirm(`سيتم نقل المرشح إلى: ${req.exact_type||req.request_type}. سيتم تصفير تقييم مطابقة المتطلبات ليتم تقييمه وفق متطلبات الوظيفة الجديدة، مع الاحتفاظ بسجل المقابلات. هل تريد المتابعة؟`))return;setMoving(true);setError('');const{error:e1}=await supabase.from('candidates').update({request_id:target,status:'جديد',updated_at:new Date().toISOString()}).eq('id',candidateId);if(e1){setError(e1.message);setMoving(false);return}const{error:e2}=await supabase.from('candidate_requirement_scores').delete().eq('candidate_id',candidateId);if(e2){setError(`تم النقل لكن تعذر تصفير تقييم المتطلبات: ${e2.message}`);setMoving(false);return}router.push(`/requests/${target}/candidates/${candidateId}`);router.refresh()}
 const remove=async()=>{if(!confirm('هل أنت متأكد من حذف المرشح نهائياً؟ سيتم حذف تقييمات المتطلبات وروابط التقييم واعتمادات التعيين المرتبطة به أيضاً. لا يمكن التراجع.'))return;setDeleting(true);setError('');const{error:e}=await supabase.from('candidates').delete().eq('id',candidateId);if(e){setError(e.message);setDeleting(false);return}router.push(`/requests/${id}`)}
 if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#f5f7fa]">جاري تحميل بيانات المرشح...</main>
 if(!candidate)return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#f5f7fa]"><div className="bg-white p-8 rounded-2xl text-red-700 font-bold">المرشح غير موجود.</div></main>
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-5xl mx-auto"><div className="flex flex-wrap justify-between gap-3 mb-5"><Link href={`/requests/${id}/candidates/${candidateId}`} className="bg-white border-2 border-slate-200 rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><ArrowRight size={17}/> العودة لملف المرشح</Link><Link href={`/requests/${id}`} className="bg-white border-2 border-slate-200 rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><ArrowRight size={17}/> الطلب</Link></div>
 <section className="bg-white rounded-2xl border-2 border-slate-200 shadow-sm p-6"><h1 className="text-2xl font-black text-[#09233f]">تعديل بيانات المرشح</h1><p className="text-sm text-slate-500 mt-1">يمكنك تعديل بيانات المرشح أو نقله إلى طلب وظيفي آخر.</p>{error&&<div className="mt-4 bg-red-50 text-red-700 p-3 rounded-xl">{error}</div>}{message&&<div className="mt-4 bg-green-50 text-green-700 p-3 rounded-xl">{message}</div>}
 <div className="grid md:grid-cols-2 gap-4 mt-6">{fields.map(([key,label,type])=><label key={key} className={type==='textarea'?'md:col-span-2':''}><span className="block text-sm font-bold text-slate-700 mb-1">{label}</span>{type==='textarea'?<textarea className="w-full border-2 border-slate-200 rounded-xl p-3 min-h-28" value={candidate[key]??''} onChange={e=>set(key,e.target.value)}/>:<input type={type} className="w-full border-2 border-slate-200 rounded-xl p-3" value={candidate[key]??''} onChange={e=>set(key,e.target.value)}/>}</label>)}</div>
 <div className="flex flex-wrap gap-3 mt-6"><button onClick={save} disabled={saving} className="bg-[#b88618] text-white rounded-xl px-6 py-3 font-bold inline-flex items-center gap-2"> <Save size={17}/> {saving?'جاري الحفظ...':'حفظ التعديلات'}</button></div></section>
 <section className="bg-white rounded-2xl border-2 border-amber-200 shadow-sm p-6 mt-5"><div className="flex items-center gap-2"><ArrowLeftRight className="text-[#b88618]"/><h2 className="text-xl font-black text-[#09233f]">نقل المرشح إلى طلب وظيفي آخر</h2></div><p className="text-sm text-slate-500 mt-1">مثال: مدير مشاريع ← مهندس موقع ← الحركة. عند النقل يتم بدء مطابقة متطلبات الوظيفة الجديدة من الصفر.</p><div className="grid md:grid-cols-[1fr_auto] gap-3 mt-5"><select className="w-full border-2 border-slate-200 rounded-xl p-3 bg-white" value={target} onChange={e=>setTarget(e.target.value)}>{requests.map(r=><option key={r.id} value={r.id}>{r.exact_type||r.request_type||'طلب وظيفي'}{r.department?` — ${r.department}`:''}{r.status?` — ${r.status}`:''}</option>)}</select><button onClick={move} disabled={moving||target===candidate.request_id} className="bg-[#09233f] text-white rounded-xl px-6 py-3 font-bold inline-flex items-center justify-center gap-2"><ArrowLeftRight size={17}/> {moving?'جاري النقل...':'نقل المرشح'}</button></div></section>
 <section className="bg-white rounded-2xl border-2 border-red-200 shadow-sm p-6 mt-5"><h2 className="text-xl font-black text-red-700">حذف المرشح</h2><p className="text-sm text-slate-500 mt-1">الحذف نهائي ولا يمكن التراجع عنه.</p><button onClick={remove} disabled={deleting} className="mt-4 bg-red-600 text-white rounded-xl px-6 py-3 font-bold inline-flex items-center gap-2"><Trash2 size={17}/> {deleting?'جاري الحذف...':'حذف المرشح نهائياً'}</button></section>
 </div></main>
}
