'use client'
import {useEffect,useMemo,useState} from 'react'
import PayrollShell from '../components/PayrollShell'
import {Upload,FileSpreadsheet,CheckCircle2,RefreshCw,Archive,Link2,AlertTriangle,Search} from 'lucide-react'

const fields=[['employee_number','الرقم الوظيفي'],['national_id','رقم الهوية / الإقامة'],['employee_name','اسم الموظف'],['date','التاريخ'],['check_in','وقت الدخول'],['check_out','وقت الخروج'],['status','حالة الحضور'],['late_minutes','دقائق التأخير'],['early_leave_minutes','دقائق الانصراف المبكر'],['overtime_hours','ساعات إضافية']]
const monthName=(m:number)=>new Intl.DateTimeFormat('ar-SA',{month:'long'}).format(new Date(2026,m-1,1))
export default function Attendance(){
 const now=new Date(),[month,setMonth]=useState(now.getMonth()+1),[year,setYear]=useState(now.getFullYear()),[file,setFile]=useState<File|null>(null),[sheet,setSheet]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[headers,setHeaders]=useState<string[]>([]),[mapping,setMapping]=useState<any>({}),[stats,setStats]=useState<any>(null),[archive,setArchive]=useState<any[]>([]),[monthly,setMonthly]=useState<any[]>([]),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[msg,setMsg]=useState('')

 const load=async()=>{const r=await fetch('/api/payroll/attendance-sheet',{cache:'no-store'});const b=await r.json();if(r.ok){setArchive(b.sheets||[])}}
 useEffect(()=>{load()},[])
 const upload=async()=>{if(!file)return;setBusy(true);setMsg('');try{const fd=new FormData();fd.append('month',String(month));fd.append('year',String(year));fd.append('file',file);const r=await fetch('/api/payroll/attendance-sheet',{method:'POST',body:fd});const b=await r.json();if(!r.ok)throw Error(b.error);setSheet(b.sheet);setHeaders(b.headers||[]);setMapping(b.mapping||{});setStats(b.stats);const rr=await fetch('/api/payroll/attendance-sheet?id='+b.sheet.id);const rb=await rr.json();setRows(rb.rows||[]);await load()}catch(e:any){setMsg(e.message||'تعذر رفع الشيت')}finally{setBusy(false)}}
 const saveMapping=async()=>{if(!sheet)return;setBusy(true);try{const r=await fetch('/api/payroll/attendance-sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_mapping',sheet_id:sheet.id,mapping})});const b=await r.json();if(!r.ok)throw Error(b.error);setSheet(b.sheet);setStats(b.stats);const rr=await fetch('/api/payroll/attendance-sheet?id='+sheet.id);const rb=await rr.json();setRows(rb.rows||[]);setMsg('تمت مطابقة الأعمدة وإعادة معالجة الشيت')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const approve=async()=>{if(!sheet)return;setBusy(true);try{const r=await fetch('/api/payroll/attendance-sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'approve',sheet_id:sheet.id})});const b=await r.json();if(!r.ok)throw Error(b.error);setSheet(b.sheet);setMsg('تم اعتماد شيت البصمة لهذا الشهر.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const openMonthly=async()=>{const r=await fetch('/api/payroll/attendance-sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'monthly',month,year})});const b=await r.json();if(!r.ok){setMsg(b.error);setMonthly([]);return}setMonthly(b.rows||[])}
 const filtered=useMemo(()=>rows.filter(x=>!q||[x.employee?.full_name,x.employee?.employee_number,x.employee_name,x.employee_number].some(v=>String(v||'').includes(q))),[rows,q])
 return <PayrollShell>
  <section className="card p-5 mb-5">
   <div className="flex flex-wrap justify-between gap-4 items-center"><div><h2 className="text-xl font-black text-[#09233f]">شيت البصمة الشهري</h2><p className="text-sm text-slate-500 mt-1">شيت البصمة المعتمد هو المصدر الأساسي للحضور عند إنشاء مسير الرواتب.</p></div><FileSpreadsheet className="text-[#b38a24]" size={30}/></div>
   <div className="grid md:grid-cols-4 gap-3 mt-5">
    <label>الشهر<select value={month} onChange={e=>setMonth(+e.target.value)} className="field w-full">{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{monthName(i+1)}</option>)}</select></label>
    <label>السنة<input type="number" value={year} onChange={e=>setYear(+e.target.value)} className="field w-full"/></label>
    <label className="md:col-span-2">ملف Excel<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files?.[0]||null)} className="field w-full"/></label>
   </div>
   <div className="flex flex-wrap gap-2 mt-4"><button onClick={upload} disabled={!file||busy} className="btn-primary rounded-xl px-5 py-3 font-bold"><Upload size={17} className="inline ml-2"/>{sheet?'استبدال شيت البصمة':'إرفاق شيت البصمة'}</button><button onClick={openMonthly} className="btn-gold rounded-xl px-5 py-3 font-bold">عرض حضور الشهر</button></div>
   {msg&&<div className="mt-4 rounded-xl bg-amber-50 border border-amber-200 p-3 text-sm font-bold">{msg}</div>}
  </section>

  {sheet&&<section className="card p-5 mb-5">
   <div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black text-[#09233f]">{sheet.file_name}</h3><p className="text-sm text-slate-500">{monthName(sheet.month)} {sheet.year} · رفع بواسطة {sheet.uploaded_by_name||'—'} · {sheet.uploaded_at?new Date(sheet.uploaded_at).toLocaleString('ar-SA'):'—'}</p></div><span className={sheet.status==='approved'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'} style={{padding:'6px 12px',borderRadius:999,fontWeight:800}}>{sheet.status==='approved'?'معتمد':'بانتظار المراجعة'}</span></div>
   <div className="grid md:grid-cols-5 gap-3 mt-5">{[['السجلات',stats?.imported_rows],['المطابقة',stats?.matched_rows],['غير مرتبطة',stats?.unmatched_rows],['الأخطاء',stats?.error_rows],['المكررة',stats?.duplicate_rows]].map(([a,b])=><div className="rounded-xl bg-slate-50 border p-4" key={String(a)}><div className="text-xs text-slate-500">{a}</div><div className="text-2xl font-black mt-1">{b??0}</div></div>)}</div>
   <div className="mt-6"><h4 className="font-black mb-3">مطابقة أعمدة Excel مع HR2</h4><div className="grid md:grid-cols-2 gap-3">{fields.map(([key,label])=><label key={key} className="text-sm font-bold">{label}<select value={mapping[key]||''} onChange={e=>setMapping((x:any)=>({...x,[key]:e.target.value||null}))} className="field w-full mt-1"><option value="">— غير مستخدم —</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div><div className="flex gap-2 mt-4"><button onClick={saveMapping} disabled={busy} className="btn-primary rounded-xl px-4 py-2 font-bold">حفظ المطابقة وإعادة المعالجة</button>{sheet.status!=='approved'&&<button onClick={approve} disabled={busy||!!(stats?.error_rows||stats?.unmatched_rows)} className="btn-gold rounded-xl px-4 py-2 font-bold"><CheckCircle2 size={16} className="inline ml-1"/> اعتماد شيت الشهر</button>}</div></div>
  </section>}

  {sheet&&<section className="card overflow-auto mb-5"><div className="p-4 flex justify-between items-center"><h3 className="font-black">معاينة البيانات قبل الاعتماد</h3><div className="relative"><Search className="absolute right-3 top-2.5 text-slate-400" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث عن موظف..." className="field pr-9"/></div></div><table className="w-full min-w-[1200px]"><thead className="bg-[#09233f] text-white"><tr>{['الموظف','الرقم الوظيفي','التاريخ','الدخول','الخروج','الحالة','التأخير','الانصراف المبكر','المطابقة','الخطأ'].map(x=><th className="p-3 text-right" key={x}>{x}</th>)}</tr></thead><tbody>{filtered.slice(0,300).map(x=><tr className="border-b" key={x.id}><td className="p-3">{x.employee?.full_name||x.employee_name||'—'}</td><td className="p-3">{x.employee?.employee_number||x.employee_number||'—'}</td><td className="p-3">{x.attendance_date||'—'}</td><td className="p-3">{x.check_in?new Date(x.check_in).toLocaleTimeString('ar-SA'):'—'}</td><td className="p-3">{x.check_out?new Date(x.check_out).toLocaleTimeString('ar-SA'):'—'}</td><td className="p-3">{x.attendance_status}</td><td className="p-3">{x.late_minutes||0}</td><td className="p-3">{x.early_leave_minutes||0}</td><td className="p-3">{x.match_status==='matched'?'مطابق':'غير مرتبط'}</td><td className="p-3 text-red-600">{x.error_message||'—'}</td></tr>)}</tbody></table></section>}

  <section className="card overflow-auto mb-5"><div className="p-5 flex items-center gap-2"><Archive size={20}/><h3 className="font-black">أرشيف شيتات البصمة</h3></div><table className="w-full min-w-[1000px]"><thead className="bg-[#09233f] text-white"><tr>{['الشهر','السنة','اسم الملف','تاريخ الرفع','رفع بواسطة','الحالة','المسير المرتبط'].map(x=><th className="p-3 text-right" key={x}>{x}</th>)}</tr></thead><tbody>{archive.map(x=>{const run=(undefined);return <tr className="border-b" key={x.id}><td className="p-3">{monthName(x.month)}</td><td className="p-3">{x.year}</td><td className="p-3">{x.file_name}</td><td className="p-3">{new Date(x.uploaded_at).toLocaleString('ar-SA')}</td><td className="p-3">{x.uploaded_by_name||'—'}</td><td className="p-3 font-bold">{x.status==='approved'?'معتمد':'مرفوع'}</td><td className="p-3">{x.linked_run||'—'}</td></tr>})}</tbody></table></section>

  {monthly.length>0&&<section className="card overflow-auto"><div className="p-5"><h3 className="font-black">الحضور والانصراف — {monthName(month)} {year}</h3><p className="text-sm text-slate-500">المصدر: شيت البصمة المعتمد للشهر.</p></div><table className="w-full min-w-[1100px]"><thead className="bg-[#09233f] text-white"><tr>{['الموظف','الرقم الوظيفي','التاريخ','الدخول','الخروج','الحالة','التأخير','الانصراف المبكر'].map(x=><th className="p-3 text-right" key={x}>{x}</th>)}</tr></thead><tbody>{monthly.map(x=><tr className="border-b" key={x.id}><td className="p-3">{x.employee?.full_name}</td><td className="p-3">{x.employee?.employee_number}</td><td className="p-3">{x.attendance_date}</td><td className="p-3">{x.check_in?new Date(x.check_in).toLocaleTimeString('ar-SA'):'—'}</td><td className="p-3">{x.check_out?new Date(x.check_out).toLocaleTimeString('ar-SA'):'—'}</td><td className="p-3">{x.attendance_status}</td><td className="p-3">{x.late_minutes}</td><td className="p-3">{x.early_leave_minutes}</td></tr>)}</tbody></table></section>}
 </PayrollShell>
}
