'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowRight,CheckCircle2,Clock3,RotateCcw,Printer,Save} from 'lucide-react'
import SignatureEditor from '@/app/components/signature/SignatureEditor'

const stages=[['employee','الموظف'],['finance','الإدارة المالية'],['hr','الموارد البشرية'],['project_manager','مدير المشاريع'],['general_manager','المدير العام']]
const labels:any={pending_employee:'بانتظار اعتماد الموظف',pending_finance:'بانتظار اعتماد المالية',pending_hr:'بانتظار اعتماد الموارد البشرية',pending_project_manager:'بانتظار اعتماد مدير المشاريع',pending_general_manager:'بانتظار اعتماد المدير العام',completed:'مكتملة ومعتمدة',returned:'مرتجعة للمراجعة'}
export default function FinancialClearancePage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''),[data,setData]=useState<any>(null),[role,setRole]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[signature,setSignature]=useState(''),[notes,setNotes]=useState(''),[decision,setDecision]=useState(''),[saving,setSaving]=useState(false),[financial,setFinancial]=useState<any>({}),[editItems,setEditItems]=useState<any[]>([])
 useEffect(()=>{void params.then(p=>setId(p.id))},[params])
 const load=async()=>{if(!id)return;setLoading(true);const [r,u]=await Promise.all([fetch('/api/financial-clearances/'+id,{cache:'no-store'}),fetch('/api/auth/me',{cache:'no-store'})]);const d=await r.json().catch(()=>({}));const ud=await u.json().catch(()=>({}));if(!r.ok)setError(d?.error||'تعذر تحميل المخالصة');else{setData(d.clearance);setFinancial(d.clearance?.financial_data||{});setEditItems(d.clearance?.items||[]);setRole(ud?.user?.role||'')}setLoading(false)}
 useEffect(()=>{void load()},[id])
 const items=data?.items||[]; const ent=items.filter((x:any)=>x.item_type==='entitlement');const obl=items.filter((x:any)=>x.item_type==='obligation');const entTotal=ent.reduce((s:number,x:any)=>s+Number(x.amount||0),0);const oblTotal=obl.reduce((s:number,x:any)=>s+Number(x.amount||0),0);const net=entTotal-oblTotal
 const currentIndex=Math.max(0,stages.findIndex(x=>x[0]===data?.current_stage))
 const canAct=role==='admin'||(data?.current_stage==='finance'&&role==='finance')||(data?.current_stage==='hr'&&role==='hr')||(data?.current_stage==='project_manager'&&role==='project_manager')||(data?.current_stage==='general_manager'&&role==='general_manager')
 const canEditFinancial=false
 const canEditItems=false
 const save=async()=>{setSaving(true);const r=await fetch('/api/financial-clearances/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({financial_data:financial})});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)setError(d?.error||'تعذر حفظ التعديلات');else await load()}
 const saveItems=async()=>{setSaving(true);const r=await fetch('/api/financial-clearances/'+id+'/items',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:editItems})});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)return setError(d?.error||'تعذر حفظ البنود المالية');await load()}
 const approve=async(action:string)=>{setSaving(true);const r=await fetch('/api/financial-clearances/'+id+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,signature,notes,decision})});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)return setError(d?.error||'تعذر تنفيذ الاعتماد');setSignature('');setNotes('');setDecision('');await load()}
 const reopen=async()=>{const reason=window.prompt('اكتب سبب إعادة فتح المخالصة');if(!reason)return;setSaving(true);const r=await fetch('/api/financial-clearances/'+id+'/reopen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)setError(d?.error||'تعذر إعادة الفتح');else await load()}
 if(loading)return <main dir="rtl" className="p-10 text-center">جارٍ تحميل المخالصة...</main>
 if(!data)return <main dir="rtl" className="p-10 text-center text-red-700">{error||'المخالصة غير موجودة'}</main>
 return <main dir="rtl" className="min-h-screen bg-slate-50 p-4 md:p-7"><div className="mx-auto max-w-[1400px]">
  <header className="no-print mb-5 flex flex-col gap-3 rounded-2xl border bg-white p-5 lg:flex-row lg:items-center lg:justify-between"><div><Link href="/financial-clearances" className="inline-flex items-center gap-1 text-sm font-black text-[#09233f]"><ArrowRight size={16}/> المخالصات المالية</Link><h1 className="mt-2 text-2xl font-black text-[#09233f]">مخالصة مالية وإدارية نهائية وإبراء ذمة</h1><div className="mt-1 text-sm font-bold text-slate-500">{data.clearance_number} · {labels[data.status]||data.status}</div></div><div className="flex flex-wrap gap-2">{data.status==='completed'&&<><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-xl bg-[#09233f] px-4 py-2.5 font-black text-white"><Printer size={16}/> طباعة المخالصة</button><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 font-black text-[#09233f]"><Printer size={16}/> تصدير PDF</button></>}{role==='admin'&&data.status==='completed'&&<button onClick={()=>void reopen()} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 font-black text-red-700"><RotateCcw size={16}/> إعادة فتح</button>}</div></header>
  {error&&<div className="no-print mb-4 rounded-xl border border-red-200 bg-red-50 p-3 font-bold text-red-700">{error}</div>}
  <section className="no-print mb-5 rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-black text-[#09233f]">مسار الاعتماد</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{labels[data.status]||data.status}</span></div><div className="grid grid-cols-1 gap-2 md:grid-cols-5">{stages.map(([k,l],i)=>{const a=data?.approvals?.find((x:any)=>x.stage===k);const active=i===currentIndex&&data.status!=="completed";return (<div key={k} className={"rounded-xl border p-3 "+(active?"border-[#b88618] bg-amber-50":"border-slate-200 bg-slate-50")}><div className="flex items-center gap-2">{a?.status==="approved"?<CheckCircle2 size={17} className="text-emerald-600"/>:<Clock3 size={17} className="text-slate-400"/>}<b>{l}</b></div><div className="mt-2 text-xs text-slate-500">{a?.status==="approved"?("اعتمد: "+(a.acted_at?new Date(a.acted_at).toLocaleString("ar-SA"):"—")):active?"المطلوب الآن":"بانتظار المرحلة"}</div></div>);})}</div></section>
  <section className="print-area rounded-2xl border bg-white p-5 shadow-sm md:p-8">
   <div className="border-b-2 border-[#09233f] pb-4 text-center"><div className="font-black text-[#09233f]">شركة البنية الأساسية للمقاولات</div><h2 className="mt-2 text-2xl font-black">مخالصة مالية وإدارية نهائية وإبراء ذمة</h2><div className="text-sm font-bold text-slate-500">FINAL FINANCIAL & ADMINISTRATIVE SETTLEMENT AND RELEASE</div><div className="mt-2 text-sm font-black">{data.clearance_number}</div></div>
   <div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[['اسم الموظف',data.employee?.full_name],['الرقم الوظيفي',data.employee?.employee_number],['الجنسية',data.employee?.nationality],['الهوية/الإقامة',data.employee?.national_id],['المسمى الوظيفي',data.employee?.job_title],['القسم',data.employee?.department],['الشركة',data.employee?.company?.name],['تاريخ المباشرة',data.employee?.hire_date],['آخر يوم عمل',data.source_snapshot?.clearance?.last_work_date],['نوع إنهاء العلاقة',data.source_snapshot?.clearance?.termination_type],['IBAN',data.employee?.iban],['البنك',data.employee?.bank_name]].map(([k,v])=><div key={String(k)} className="rounded-lg border p-3"><div className="text-[11px] font-bold text-slate-500">{k}</div><div className="mt-1 font-black text-[#09233f]">{v||'—'}</div></div>)}</div>
   <div className="mt-6"><h3 className="font-black text-[#09233f]">البيانات الوظيفية والمالية</h3><div className="mt-2 grid grid-cols-2 gap-3 md:grid-cols-4">{[['بداية العلاقة التعاقدية',financial.contract_start_date],['بداية الإجازة',financial.leave_start],['نهاية الإجازة',financial.leave_end],['الأيام المحتسبة',financial.days_counted],['الراتب الأساسي',financial.basic_salary],['بدل السكن',financial.housing_allowance],['بدل النقل',financial.transportation_allowance],['بدلات أخرى',financial.other_allowances]].map(([k,v])=><div key={String(k)} className="border p-3"><div className="text-xs text-slate-500">{k}</div><div className="font-black">{v||'—'}</div></div>)}</div></div>
   <div className="mt-6 grid grid-cols-1 gap-5 md:grid-cols-2"><div><h3 className="font-black">بيان المستحقات</h3><table className="mt-2 w-full text-sm border"><tbody>{ent.map((x:any)=><tr key={x.id}><td className="border p-2">{x.label}</td><td className="border p-2 text-left font-black">{Number(x.amount||0).toFixed(2)} ر.س</td></tr>)}<tr className="bg-slate-50 font-black"><td className="border p-2">إجمالي المستحقات</td><td className="border p-2 text-left">{entTotal.toFixed(2)} ر.س</td></tr></tbody></table></div><div><h3 className="font-black">بيان الالتزامات</h3><table className="mt-2 w-full text-sm border"><tbody>{obl.map((x:any)=><tr key={x.id}><td className="border p-2">{x.label}</td><td className="border p-2 text-left font-black">{Number(x.amount||0).toFixed(2)} ر.س</td></tr>)}<tr className="bg-slate-50 font-black"><td className="border p-2">إجمالي الالتزامات</td><td className="border p-2 text-left">{oblTotal.toFixed(2)} ر.س</td></tr></tbody></table></div></div>
   <div className="no-print mt-6 rounded-2xl border bg-slate-50 p-4"><h3 className="font-black text-[#09233f]">البيانات الوظيفية والمالية — إدخال الموارد البشرية</h3><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4">
<label className="text-xs font-bold">تاريخ المباشرة<input type="date" value={financial.contract_start_date||''} onChange={e=>setFinancial((v:any)=>({...v,contract_start_date:e.target.value||null}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">آخر يوم عمل<input type="date" value={financial.last_work_date||''} onChange={e=>setFinancial((v:any)=>({...v,last_work_date:e.target.value||null}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">بداية الإجازة<input type="date" value={financial.leave_start||''} onChange={e=>setFinancial((v:any)=>({...v,leave_start:e.target.value||null}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">نهاية الإجازة<input type="date" value={financial.leave_end||''} onChange={e=>setFinancial((v:any)=>({...v,leave_end:e.target.value||null}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">رصيد الإجازات المستحق (أيام)<input type="number" min="0" step="0.01" value={financial.leave_balance_days??0} onChange={e=>setFinancial((v:any)=>({...v,leave_balance_days:e.target.value,days_counted:e.target.value}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">الراتب الأساسي<input type="number" min="0" step="0.01" value={financial.basic_salary??''} onChange={e=>setFinancial((v:any)=>({...v,basic_salary:e.target.value}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">بدل السكن<input type="number" min="0" step="0.01" value={financial.housing_allowance??''} onChange={e=>setFinancial((v:any)=>({...v,housing_allowance:e.target.value}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">بدل النقل<input type="number" min="0" step="0.01" value={financial.transportation_allowance??''} onChange={e=>setFinancial((v:any)=>({...v,transportation_allowance:e.target.value}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">بدلات أخرى<input type="number" min="0" step="0.01" value={financial.other_allowances??''} onChange={e=>setFinancial((v:any)=>({...v,other_allowances:e.target.value}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">الأجر اليومي (يحسب تلقائيًا)<input readOnly value={financial.daily_wage?Number(financial.daily_wage).toFixed(2):'—'} className="mt-1 w-full rounded-lg border bg-slate-100 p-2"/></label>
<label className="text-xs font-bold">البنك<input value={financial.bank_name||''} onChange={e=>setFinancial((v:any)=>({...v,bank_name:e.target.value}))} className="mt-1 w-full rounded-lg border p-2"/></label>
<label className="text-xs font-bold">IBAN<input value={financial.iban||''} onChange={e=>setFinancial((v:any)=>({...v,iban:e.target.value}))} className="mt-1 w-full rounded-lg border p-2"/></label>
</div>{canEditFinancial&&<button disabled={saving||data.status==='completed'} onClick={()=>void save()} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[#09233f] px-4 py-2 font-black text-white"><Save size={15}/> حفظ بيانات HR وحساب المستحقات</button>}<div className="mt-3 rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-800">قيمة الإجازة = عدد الأيام × الأجر اليومي، والأجر اليومي = الراتب الأساسي ÷ 30.</div></div>{canEditItems&&<div className="no-print mt-6 rounded-2xl border bg-slate-50 p-4"><div className="flex items-center justify-between"><h3 className="font-black text-[#09233f]">بيان المستحقات والالتزامات — الإدارة المالية</h3><button onClick={()=>setEditItems(v=>[...v,{item_type:'entitlement',label:'',amount:0,notes:'',editable:true,code:'manual'}])} className="rounded-lg bg-[#09233f] px-3 py-2 text-xs font-black text-white">+ إضافة مستحق</button></div><div className="mt-3 space-y-2">{editItems.map((x:any,i:number)=><div key={x.id||i} className="grid gap-2 rounded-xl border bg-white p-3 md:grid-cols-[120px_1fr_140px_1fr_40px]"><select value={x.item_type||'entitlement'} onChange={e=>setEditItems(v=>v.map((it,j)=>j===i?{...it,item_type:e.target.value}:it))} className="rounded-lg border p-2 text-sm"><option value="entitlement">مستحق</option><option value="obligation">التزام</option></select><input value={x.label||''} onChange={e=>setEditItems(v=>v.map((it,j)=>j===i?{...it,label:e.target.value}:it))} placeholder="النوع / البيان" className="rounded-lg border p-2"/><input disabled={x.editable===false} type="number" min="0" step="0.01" value={x.amount??0} onChange={e=>setEditItems(v=>v.map((it,j)=>j===i?{...it,amount:e.target.value}:it))} className="rounded-lg border p-2 text-left"/><input value={x.notes||''} onChange={e=>setEditItems(v=>v.map((it,j)=>j===i?{...it,notes:e.target.value}:it))} placeholder="ملاحظات" className="rounded-lg border p-2"/><button disabled={x.editable===false} onClick={()=>setEditItems(v=>v.filter((_,j)=>j!==i))} className="rounded-lg border text-red-700">×</button></div>)}</div><button disabled={saving||data.status==='completed'} onClick={()=>void saveItems()} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[#09233f] px-4 py-2 font-black text-white"><Save size={15}/> حفظ بيان المالية</button></div>}{data.source_snapshot?.clearance?.finance_notes&&<div className="mt-5 rounded-xl border bg-amber-50 p-4"><h3 className="font-black text-[#09233f]">ملاحظات الإدارة المالية الواردة من إخلاء الطرف</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{data.source_snapshot.clearance.finance_notes}</p></div>}<div className="mt-5 rounded-xl border-2 border-[#09233f] bg-slate-50 p-4 text-center"><div className="text-sm font-bold">صافي المستحق للموظف</div><div className="mt-1 text-2xl font-black text-[#09233f]">{net.toFixed(2)} ر.س</div><div className="mt-1 text-xs text-slate-500">إجمالي المستحقات − إجمالي الالتزامات</div></div>
   <div className="mt-6 text-sm leading-8"><h3 className="font-black text-[#09233f]">التسوية الإدارية وأصول الشركة</h3><p>يقر الموظف بأنه قام بتسليم جميع العهد المالية والعينية والأجهزة والوثائق والبطاقات التعريفية وأي متعلقات أو بيانات تخص الشركة، ويلتزم بالمحافظة على سرية بيانات ووثائق الشركة وعدم استخدامها أو إفشائها بعد انتهاء العلاقة التعاقدية.</p><h3 className="mt-4 font-black text-[#09233f]">إبراء الذمة</h3><p>يقر الموظف بعد مراجعته للمستحقات والالتزامات الواردة في هذه المخالصة بأنه استلم/سيستلم مستحقاته المبينة أعلاه، ويقر بإبراء ذمة الشركة من أي مطالبات مالية أخرى عن فترة خدمته حتى تاريخ آخر يوم عمل، وذلك في حدود ما تم إثباته واعتماده في هذه المخالصة.</p><h3 className="mt-4 font-black text-[#09233f]">الأحكام العامة</h3><p>تعتبر هذه المخالصة نهائية وتسري من تاريخ التوقيع والاعتماد عليها، ولا يجوز تعديلها بعد الاعتماد النهائي إلا بإجراء إداري موثق وإعادة فتح مع بيان السبب.</p></div>
   <div className="mt-7"><h3 className="font-black text-[#09233f]">الاعتمادات والتوقيعات</h3><div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-5">{stages.map(([k,l])=>{const a=data.approvals?.find((x:any)=>x.stage===k);return <div key={k} className="min-h-[150px] rounded-xl border p-3"><b>{l}</b><div className="mt-2 text-xs text-slate-500">{a?.approver_name||'—'}</div><div className="text-xs text-slate-500">{a?.approver_title||'—'}</div><div className="signature-print-box mt-3 flex h-14 items-center justify-center border">{a?.signature?<img src={a.signature} alt="signature" className="max-h-10 max-w-full"/>:<span className="text-xs text-slate-400">لم يعتمد بعد</span>}</div><div className="mt-2 text-xs font-black text-[#09233f]">الاسم: {a?.approver_name||'—'}</div><div className="mt-1 text-[11px] text-slate-500">التاريخ: {a?.acted_at?new Date(a.acted_at).toLocaleDateString('ar-SA'):'—'}</div>{a?.notes&&<div className="mt-1 text-xs">ملاحظات: {a.notes}</div>}</div>})}</div></div>

   {data.status==='completed'&&<div className="final-one-page">
    <div className="final-letterhead"><div className="company-ar">شركة البنية الأساسية للمقاولات ذ.م.م</div><div className="company-en">AL-BENYAH AL-ASASEYAH CONTRACTING CO. L.L.C</div><div className="gold-line"/></div>
    <div className="final-title">مخالصة مالية وإدارية نهائية وإبراء ذمة</div><div className="final-subtitle">FINAL FINANCIAL & ADMINISTRATIVE SETTLEMENT AND RELEASE</div>
    <div className="final-meta"><span>رقم المخالصة: <b>{data.clearance_number}</b></span><span>تاريخ الاعتماد النهائي: <b>{data.final_approved_at?new Date(data.final_approved_at).toLocaleDateString('ar-SA'):'—'}</b></span></div>
    <div className="final-info"><div><b>اسم الموظف</b><span>{data.employee?.full_name||'—'}</span></div><div><b>الرقم الوظيفي</b><span>{data.employee?.employee_number||'—'}</span></div><div><b>الهوية/الإقامة</b><span>{data.employee?.national_id||'—'}</span></div><div><b>المسمى الوظيفي</b><span>{data.employee?.job_title||'—'}</span></div><div><b>القسم</b><span>{data.employee?.department||'—'}</span></div><div><b>الشركة</b><span>{data.employee?.company?.name||'—'}</span></div><div><b>آخر يوم عمل</b><span>{data.source_snapshot?.clearance?.last_work_date||'—'}</span></div><div><b>صافي المستحق</b><span>{net.toFixed(2)} ر.س</span></div></div>
    <div className="final-finance"><div><b>إجمالي المستحقات</b><strong>{entTotal.toFixed(2)} ر.س</strong></div><div><b>إجمالي الالتزامات</b><strong>{oblTotal.toFixed(2)} ر.س</strong></div><div><b>صافي التسوية</b><strong>{net.toFixed(2)} ر.س</strong></div></div>
    <p className="final-declaration">يقر الموظف باستكمال إجراءات إخلاء الطرف وتسوية المستحقات والالتزامات الموضحة أعلاه، وبعد استكمال الاعتمادات والتوقيعات تعتبر هذه المخالصة نهائية وفق البيانات المثبتة بها.</p>
    <div className="final-signatures">{stages.map(([k,l])=>{const a=data.approvals?.find((x:any)=>x.stage===k);return <div className="final-sign" key={k}><b>{l}</b>{k==='project_manager'&&a?.decision&&<span className="decision">{a.decision==='applies'?'ينطبق':'لا ينطبق'}</span>}<div className="sig-img">{a?.signature?<img src={a.signature} alt="signature"/>:<span>—</span>}</div><div className="sig-name">{a?.approver_name||'—'}</div><div className="sig-date">التاريخ: {a?.acted_at?new Date(a.acted_at).toLocaleDateString('ar-SA'):'—'}</div></div>})}</div>
    <div className="final-footer">هذه الوثيقة صادرة إلكترونيًا من نظام الموارد البشرية وتتضمن جميع الاعتمادات والتوقيعات المسجلة على المخالصة.</div>
   </div>}
  </section>
  {canAct&&data.status!=='completed'&&data.current_stage!=='employee'&&<section className="no-print mt-5 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black text-[#09233f]">إجراء الاعتماد — {stages.find(x=>x[0]===data.current_stage)?.[1]}</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><div><label className="mb-1 block text-sm font-bold">التوقيع</label><SignatureEditor value={signature} onChange={setSignature}/></div><div><label className="mb-1 block text-sm font-bold">ملاحظات</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} className="h-40 w-full rounded-xl border p-3" placeholder="ملاحظات الاعتماد أو الإرجاع"/></div></div><div className="mt-4 flex flex-wrap gap-2">{data.current_stage==='project_manager'&&<><button disabled={saving} onClick={()=>setDecision('applies')} className={"rounded-xl border px-4 py-2 font-black "+(decision==='applies'?'bg-emerald-100 border-emerald-400':'bg-white')}>ينطبق</button><button disabled={saving} onClick={()=>setDecision('not_applies')} className={"rounded-xl border px-4 py-2 font-black "+(decision==='not_applies'?'bg-slate-200 border-slate-400':'bg-white')}>لا ينطبق</button></>}<button disabled={saving||(data.current_stage==='project_manager'&&!decision)} onClick={()=>void approve('approve')} className="inline-flex items-center gap-2 rounded-xl bg-[#09233f] px-5 py-3 font-black text-white"><CheckCircle2 size={17}/> اعتماد والانتقال للمرحلة التالية</button><button disabled={saving} onClick={()=>void approve('return')} className="inline-flex items-center gap-2 rounded-xl border border-amber-300 bg-amber-50 px-5 py-3 font-black text-amber-800"><RotateCcw size={17}/> إرجاع للمراجعة</button></div></section>}
  {data.status!=='completed'&&data.current_stage==='employee'&&<section className="no-print mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm font-bold text-blue-800">المخالصة بانتظار اعتماد الموظف. رابط الاعتماد موجود في بيانات المخالصة ويمكن إرساله للموظف.</section>}
  <section className="no-print mt-5 rounded-2xl border bg-white p-5"><h2 className="font-black text-[#09233f]">روابط الاعتماد المستقلة</h2><div className="mt-3 space-y-2">{(data.links||[]).sort((a:any,b:any)=>String(a.stage).localeCompare(String(b.stage))).map((l:any)=><div key={l.id} className="flex flex-col gap-2 rounded-xl border bg-slate-50 p-3 md:flex-row md:items-center"><div className="flex-1"><b>{stages.find(x=>x[0]===l.stage)?.[1]||l.stage}</b><div className="text-xs text-slate-500">{l.status==='active'?'نشط':'مستخدم'}</div></div><code className="break-all text-xs">{typeof window!=='undefined'?window.location.origin:''}/financial-clearances/public/{l.token}</code><button onClick={()=>navigator.clipboard?.writeText((typeof window!=='undefined'?window.location.origin:'')+'/financial-clearances/public/'+l.token)} className="rounded-lg border bg-white px-3 py-2 text-xs font-black">نسخ الرابط</button></div>)}</div></section><section className="no-print mt-5 rounded-2xl border bg-white p-5"><h2 className="font-black text-[#09233f]">سجل الإجراءات</h2><div className="mt-3 space-y-2">{(data.audit_logs||[]).sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at))).map((a:any)=><div key={a.id} className="flex gap-3 rounded-xl bg-slate-50 p-3 text-sm"><Clock3 size={16} className="mt-0.5 text-[#b88618]"/><div><b>{a.action}</b><div className="text-xs text-slate-500">{a.actor_name||'النظام'} · {a.actor_role||'—'} · {new Date(a.created_at).toLocaleString('ar-SA')}</div></div></div>)}</div></section>
 </div><style>{'@media print{.no-print{display:none!important}.print-area{box-shadow:none!important;border:0!important;padding:0!important}.hr-sidebar,.hr-topbar{display:none!important}.hr-main{margin:0!important}@page{size:A4;margin:10mm}body{background:#fff!important}}'}</style></main>
}
