'use client'
import {useEffect,useState} from 'react'
import SignatureEditor from '@/app/components/signature/SignatureEditor'
import {Save,Printer} from 'lucide-react'

const labels:any={replacement:'البديل',hr:'الموارد البشرية',general_manager:'المدير العام'}
export default function LeaveApprovalPublic({token}:{token:string}){
 const [data,setData]=useState<any>(),[form,setForm]=useState<any>({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
 const load=async()=>{const r=await fetch('/api/forms/public/'+token,{cache:'no-store'});const x=await r.json();if(r.ok){setData(x);const s=String(x.link?.link_scope||'').replace('leave:','');setForm(x.record?.form_data?.leave_approvals?.[s]||{})}else setMsg(x.error||'تعذر فتح الرابط');setLoading(false)}
 useEffect(()=>{void load()},[token])
 if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center">جارٍ تحميل طلب الإجازة...</main>
 const scope=String(data?.link?.link_scope||'').replace('leave:',''),e=data?.data?.employee||{},f=data?.record?.form_data||{},a=f.leave_approvals||{}
 const prior=scope==='replacement'?!!f.employee_signature:scope==='hr'?(f.replacement?!!a.replacement?.approval_signature:!!f.employee_signature):scope==='general_manager'?!!a.hr?.approval_signature:false
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}))
 const skipReplacement=async()=>{setBusy(true);const r=await fetch('/api/forms/public/'+token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({skip_replacement:true,device_name:navigator.userAgent})});const x=await r.json();setBusy(false);setMsg(r.ok?'تم تخطي اعتماد البديل والانتقال إلى اعتماد المدير العام.':x.error||'تعذر تخطي البديل');if(r.ok)load()}; const save=async()=>{if(!form.approval_name||!form.approval_date||!form.approval_signature){setMsg('لا يمكن الحفظ إلا بإدخال الاسم والتاريخ والتوقيع.');return}setBusy(true);const r=await fetch('/api/forms/public/'+token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form,device_name:navigator.userAgent})});const x=await r.json();setBusy(false);setMsg(r.ok?'تم حفظ الاعتماد بنجاح ولا يمكن تعديل الرابط مرة أخرى.':x.error||'تعذر الحفظ');if(r.ok)load()}
 const rows=[['اسم الموظف',e.full_name],['الرقم الوظيفي',e.employee_number],['القسم',e.department],['المسمى الوظيفي',e.job_title],['نوع الإجازة',f.leave_type],['من تاريخ',f.from_date],['إلى تاريخ',f.to_date],['عدد الأيام',f.days],['البديل',f.replacement],['ملاحظات',f.notes]]
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5"><section className="max-w-[210mm] min-h-[297mm] mx-auto bg-white p-[10mm] shadow"><header className="text-center border-b-2 border-[#b88618] pb-4"><h1 className="text-2xl font-black text-[#09233f]">اعتماد طلب إجازة</h1><b className="text-[#b88618]">رابط اعتماد: {labels[scope]}</b></header><h3 className="mt-5 border-y border-[#b88618] py-2 font-black">بيانات طلب الإجازة</h3><div className="grid grid-cols-2 gap-2">{rows.map(([k,v])=><div className="border-b p-2" key={String(k)}><small className="text-slate-500 block">{k}</small><b>{v||'—'}</b></div>)}</div><h3 className="mt-5 border-y border-[#b88618] py-2 font-black">الاعتماد</h3><fieldset disabled={!!data?.link?.locked||!prior}><div className="grid grid-cols-2 gap-4 mt-4"><label className="font-bold">الاسم *<input className="w-full border-b p-2" value={form.approval_name||''} onChange={e=>set('approval_name',e.target.value)}/></label><label className="font-bold">التاريخ *<input type="date" className="w-full border-b p-2" value={form.approval_date||''} onChange={e=>set('approval_date',e.target.value)}/></label></div><div className="mt-4 font-bold">التوقيع *<SignatureEditor value={form.approval_signature||''} onChange={v=>set('approval_signature',v)} autoUseSaved={false}/></div></fieldset>{!prior&&<div className="mt-4 bg-amber-50 text-amber-800 p-3 rounded-lg font-bold">الرابط في انتظار الاعتماد السابق.</div>}{data?.link?.locked&&<div className="mt-4 bg-slate-100 p-3 rounded-lg font-bold text-center">تم اعتماد هذا الرابط ولا يمكن تعديله.</div>}{msg&&<div className="mt-4 bg-emerald-50 text-emerald-800 p-3 rounded-lg font-bold text-center">{msg}</div>}<div className="mt-5 print:hidden">{!data?.link?.locked&&prior&&<button disabled={busy} onClick={save} className="bg-[#09233f] text-white rounded-xl px-6 py-2 font-bold"><Save size={17} className="inline ml-1"/>حفظ الاعتماد</button>}{scope==='hr'&&!!f.replacement&&!a.replacement?.approval_signature&&!a.replacement?.skipped&&!data?.link?.locked&&<button disabled={busy} onClick={skipReplacement} className="bg-amber-600 text-white rounded-xl px-6 py-2 font-bold mr-2">تخطي اعتماد البديل</button>}<button onClick={()=>window.print()} className="bg-[#b88618] text-white rounded-xl px-6 py-2 font-bold mr-2"><Printer size={17} className="inline ml-1"/>طباعة</button></div></section></main>
}