'use client'
import {useEffect,useState} from 'react'
import SignatureEditor from '@/app/components/signature/SignatureEditor'
import {Save,Printer} from 'lucide-react'

export default function LeaveEmployeePublic({token}:{token:string}){
 const [data,setData]=useState<any>(null),[form,setForm]=useState<any>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const load=async()=>{setLoading(true);const r=await fetch('/api/forms/public/'+token,{cache:'no-store'});const x=await r.json();if(r.ok){setData(x);setForm(x.record?.form_data||{})}else setMsg(x.error||'تعذر فتح الرابط');setLoading(false)}
 useEffect(()=>{void load()},[token])
 const e=data?.data?.employee||{}; const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}))
 const save=async()=>{if(!form.employee_name||!form.from_date||!form.to_date||!form.days||!form.employee_signature){setMsg('يجب استكمال بيانات الإجازة والتاريخ وعدد الأيام والتوقيع.');return}setBusy(true);const r=await fetch('/api/forms/public/'+token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form,device_name:navigator.userAgent})});const x=await r.json();setBusy(false);setMsg(r.ok?'تم إرسال طلب الإجازة بنجاح.':x.error||'تعذر الحفظ');if(r.ok)await load()}
 if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center">جارٍ تحميل طلب الإجازة...</main>
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5"><section className="max-w-[210mm] min-h-[297mm] mx-auto bg-white p-[10mm] shadow-sm"><header className="text-center border-b-2 border-[#b88618] pb-4"><h1 className="text-2xl font-black text-[#09233f]">طلب إجازة</h1><div className="font-bold text-[#b88618]">LEAVE REQUEST</div><div className="text-xs text-slate-500 mt-2">رابط الموظف — تعبئة طلب الإجازة والتوقيع</div></header>
 <h3 className="mt-5 border-y border-[#b88618] py-2 font-black">بيانات الموظف</h3><div className="grid grid-cols-2 gap-3 mt-3">{[['اسم الموظف',e.full_name],['الرقم الوظيفي',e.employee_number],['القسم',e.department],['المسمى الوظيفي',e.job_title],['رقم الجوال',e.phone]].map(([k,v])=><div key={String(k)} className="border-b p-2"><span className="text-xs text-slate-500 block">{k}</span><b>{v||'—'}</b></div>)}</div>
 <fieldset disabled={!!data?.link?.locked} className="mt-5"><h3 className="border-y border-[#b88618] py-2 font-black">بيانات الإجازة</h3><div className="grid grid-cols-2 gap-4 mt-4"><label className="font-bold">نوع الإجازة *<select className="w-full border-b p-2" value={form.leave_type||''} onChange={x=>set('leave_type',x.target.value)}><option value="">اختر...</option><option>سنوية</option><option>مرضية</option><option>اضطرارية</option><option>بدون راتب</option><option>أخرى</option></select></label><label className="font-bold">عدد الأيام *<input type="number" min="1" className="w-full border-b p-2" value={form.days||''} onChange={x=>set('days',x.target.value)}/></label><label className="font-bold">من تاريخ *<input type="date" className="w-full border-b p-2" value={form.from_date||''} onChange={x=>set('from_date',x.target.value)}/></label><label className="font-bold">إلى تاريخ *<input type="date" className="w-full border-b p-2" value={form.to_date||''} onChange={x=>set('to_date',x.target.value)}/></label></div><label className="font-bold block mt-4">البديل أثناء الإجازة <input className="w-full border-b p-2" value={form.replacement||''} onChange={x=>set('replacement',x.target.value)} placeholder="اتركه فارغًا إذا لا يوجد بديل"/></label><label className="font-bold block mt-3">ملاحظات<textarea className="w-full border rounded-lg p-2 mt-1 min-h-20" value={form.notes||''} onChange={x=>set('notes',x.target.value)}/></label><div className="grid grid-cols-2 gap-4 mt-4"><label className="font-bold">اسم الموظف *<input className="w-full border-b p-2" value={form.employee_name||e.full_name||''} onChange={x=>set('employee_name',x.target.value)}/></label><label className="font-bold">التاريخ *<input type="date" className="w-full border-b p-2" value={form.employee_date||''} onChange={x=>set('employee_date',x.target.value)}/></label></div><div className="mt-4"><b>توقيع الموظف *</b><SignatureEditor employeeId={data?.record?.employee_id||data?.link?.employee_id||e.id} publicToken={token} value={form.employee_signature||''} onChange={v=>set('employee_signature',v)}/></div></fieldset>
 {data?.link?.locked&&<div className="mt-5 bg-slate-100 p-3 rounded-lg font-bold text-center">تم إرسال الطلب ولا يمكن تعديله.</div>}{msg&&<div className="mt-4 bg-emerald-50 text-emerald-800 p-3 rounded-lg font-bold text-center">{msg}</div>}<div className="mt-5 flex gap-2 print:hidden">{!data?.link?.locked&&<button disabled={busy} onClick={save} className="bg-[#09233f] text-white rounded-xl px-6 py-2 font-bold"><Save size={17} className="inline ml-1"/>حفظ وإرسال الطلب</button>}<button onClick={()=>window.print()} className="bg-[#b88618] text-white rounded-xl px-6 py-2 font-bold"><Printer size={17} className="inline ml-1"/>طباعة</button></div></section></main>
}