import { NextRequest, NextResponse } from 'next/server'
import { getServerAuth, supabaseAdminHeaders, SUPABASE_URL } from '@/lib/server-auth'
const ALLOWED=['admin','hr','manager','general_manager']
async function adminAction(auth:any,payload:any){const r=await fetch(`${SUPABASE_URL}/functions/v1/attendance-admin`,{method:'POST',headers:{'Authorization':`Bearer ${auth.token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({error:'تعذر تنفيذ العملية'}));return {r,b}}
export async function GET(req:NextRequest){const auth=await getServerAuth(req,ALLOWED);if(!auth)return NextResponse.json({error:'Unauthorized'},{status:401});const [e,m,l,el]=await Promise.all([
 fetch(`${SUPABASE_URL}/rest/v1/employee_records?select=id,employee_number,full_name,email,job_title,department,employment_status&order=full_name.asc&limit=5000`,{headers:supabaseAdminHeaders(auth),cache:'no-store'}),
 fetch(`${SUPABASE_URL}/rest/v1/attendance_employee_users?select=id,user_id,employee_id,app_username,is_active,created_at,updated_at&order=created_at.desc`,{headers:supabaseAdminHeaders(auth),cache:'no-store'}),
 fetch(`${SUPABASE_URL}/rest/v1/attendance_locations?select=id,name,latitude,longitude,radius_meters,is_active&order=name.asc`,{headers:supabaseAdminHeaders(auth),cache:'no-store'}),
 fetch(`${SUPABASE_URL}/rest/v1/attendance_employee_locations?select=id,employee_id,location_id,is_active&is_active=eq.true`,{headers:supabaseAdminHeaders(auth),cache:'no-store'})]);if(!e.ok||!m.ok||!l.ok||!el.ok)return NextResponse.json({error:'تعذر تحميل بيانات الحسابات والمواقع'},{status:500});return NextResponse.json({employees:await e.json(),mappings:await m.json(),locations:await l.json(),employeeLocations:await el.json()})}
export async function POST(req:NextRequest){const auth=await getServerAuth(req,ALLOWED);if(!auth)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json().catch(()=>({}));const action=String(b.action||'create_account');let payload:any={action,employee_id:b.employee_id};if(action==='create_account')payload={action,employee_id:b.employee_id,username:b.username,password:b.password,location:b.location};if(action==='update_location')payload={action,employee_id:b.employee_id,latitude:b.latitude,longitude:b.longitude,radius_meters:b.radius_meters,name:b.name};if(action==='set_status')payload={action,employee_id:b.employee_id,is_active:Boolean(b.is_active)};if(action==='change_password')payload={action,employee_id:b.employee_id,password:b.password};if(action==='delete_account')payload={action,employee_id:b.employee_id};if(action==='set_locations')payload={action,employee_id:b.employee_id,location_ids:Array.isArray(b.location_ids)?b.location_ids:[]};const {r,b:out}=await adminAction(auth,payload);if(!r.ok)return NextResponse.json(out,{status:r.status});return NextResponse.json(out)}
