'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, Printer } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Data={c:any;o:any;r:any}
const v=(x:any)=>x||'—'
export default function OnboardingReport({params}:{params:Promise<{candidateId:string}>}){
 const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true)
 useEffect(()=>{params.then(async({candidateId})=>{const {data:c}=await supabase.from('candidates').select('*').eq('id',candidateId).maybeSingle();if(!c){setLoading(false);return}const [{data:o},{data:r}]=await Promise.all([supabase.from('employee_onboarding').select('*').eq('candidate_id',candidateId).maybeSingle(),supabase.from('requests').select('*').eq('id',c.request_id).maybeSingle()]);setData(o?{c,o,r}:null);setLoading(false)})},[params])
 if(loading)return <main className="p-10 text-center" dir="rtl">جاري تجهيز النموذج...</main>
 if(!data)return <main className="p-10 text-center" dir="rtl">تعذر العثور على نموذج مباشرة العمل.</main>
 const {c,o,r}=data;const newAppointment=o.appointment_type==='تعيين جديد'
 const check=(condition:boolean)=>condition?'✓':' '
 return <main dir="rtl" className="min-h-screen bg-slate-100 p-3 print:bg-white"><style>{`@page{size:A4;margin:6mm}*{box-sizing:border-box}@media print{.no-print{display:none!important}.sheet{box-shadow:none!important;border:0!important;margin:0!important;width:100%!important;padding:0!important}.keep{break-inside:avoid}}`}</style><div className="no-print flex justify-between max-w-[780px] mx-auto mb-3"><Link href="/onboarding" className="font-bold text-[#09233f] inline-flex items-center gap-2"><ArrowLeft size={17}/> العودة</Link><button onClick={()=>window.print()} className="btn-primary rounded-lg px-4 py-2 font-bold inline-flex items-center gap-2"><Printer size={17}/> طباعة</button></div><div className="sheet mx-auto w-full max-w-[780px] bg-white border shadow-sm p-4 text-[10px] leading-[1.25] text-slate-900">
 <header className="text-center mb-1"><h1 className="text-xl font-black text-[#09233f]">مباشــرة عمـــــل</h1><div className="font-bold tracking-[0.35em] text-[#09233f]">N e w  S t a f f  J o i n i n g  F o r m</div><div className="flex justify-between mt-1 border-b border-slate-800 pb-1"><span>رقم المباشرة - {v(o.direct_work_number)}</span><span>التاريخ {v(o.direct_start_date)}</span></div></header>
 <div className="border border-slate-700 grid grid-cols-2 font-bold keep"><div className="p-1 text-right">عودة من إجازة ( {check(o.appointment_type==='عودة للعمل')} ) – تعيين مؤقت ( {check(o.appointment_type==='مؤقت')} ) تحت التجربة – تعيين جديد ( {check(newAppointment)} )</div><div className="p-1 text-left" dir="ltr">Return from leave ( {check(o.appointment_type==='عودة للعمل')} ) – Temporary appointment ( {check(o.appointment_type==='مؤقت')} ) under probation – New appointment ( {check(newAppointment)} )</div></div>
 <table className="w-full border-collapse mt-1"><tbody>{[['الاسم',c.full_name,'Name'],['الجنسية',c.nationality||o.nationality,'Nationality'],['رقم الهوية / الإقامة',c.national_id||o.national_id,'ID Number'],['البريد الالكتروني',c.email||o.email,'Email ID'],['رقم الهاتف',c.phone,'Contact Number'],['تاريخ المباشرة',o.direct_start_date,'Start working Date']].map(x=><tr key={x[0]}><td className="border border-slate-700 p-1 font-bold w-[27%]">{x[0]}</td><td className="border border-slate-700 p-1 w-[46%]">{v(x[1])}</td><td className="border border-slate-700 p-1 text-left" dir="ltr">{x[2]}</td></tr>)}</tbody></table>
 <table className="w-full border-collapse mt-1 keep"><tbody><tr><td colSpan={3} className="border border-slate-700 p-1 font-black">في حال الطوارئ يجب الاتصال بـ <span dir="ltr" className="float-left">Emergency Contact Information</span></td></tr><tr><td className="border border-slate-700 p-1 font-bold w-[27%]">الاسم</td><td className="border border-slate-700 p-1">{v(o.emergency_contact_name)}</td><td className="border border-slate-700 p-1 text-left" dir="ltr">Name</td></tr><tr><td className="border border-slate-700 p-1 font-bold">رقم الهاتف</td><td className="border border-slate-700 p-1">{v(o.emergency_contact_phone)}</td><td className="border border-slate-700 p-1 text-left" dir="ltr">Primary Phone:</td></tr><tr><td className="border border-slate-700 p-1 font-bold">صلة القرابـة :-</td><td className="border border-slate-700 p-1">{v(o.emergency_contact_relationship)}</td><td className="border border-slate-700 p-1 text-left" dir="ltr">Relationship:</td></tr></tbody></table>
 {newAppointment&&<><div className="grid grid-cols-2 border border-slate-700 mt-1 font-black"><div className="p-1">الحزمة المالية الشهرية</div><div className="p-1 text-left" dir="ltr">COMPENSATION MONTHLY</div></div><table className="w-full border-collapse"><tbody>{[['الراتب الأساسي','Basic Salary',o.basic_salary||o.salary],['بدل السكن (25% من الراتب الأساسي)','Housing Allowance',o.housing_allowance||'مؤمن من قبل الشركة'],['بدل النقل','Transportation Allowance',o.transportation_allowance||'مؤمن من قبل الشركة'],['إجمالي الأجر الشهري','Total Monthly Salary',o.salary]].map(x=><tr key={x[0]}><td className="border border-slate-700 p-1 font-bold w-[35%]">{x[0]}</td><td className="border border-slate-700 p-1 w-[35%] text-left" dir="ltr">{x[1]}</td><td className="border border-slate-700 p-1 font-bold">{v(x[2])}</td></tr>)}<tr><td className="border border-slate-700 p-1 font-bold">ملاحظة :-</td><td colSpan={2} className="border border-slate-700 p-1 text-left" dir="ltr">Note</td></tr><tr><td colSpan={3} className="border border-slate-700 p-1.5 text-justify">الأجر الشهري أعلاه شامل ومقابل ساعات العمل اليومية المتفق عليها والبالغة (10) ساعات شاملة فترات الراحة، ولا تستحق عنها أي مقابل إضافي.<br/>ويُصرف الأجر شهرياً عن طريق التحويل البنكي وفق نظام حماية الأجور.<br/><span dir="ltr">All-inclusive package covering the agreed ten (10) daily working hours, breaks included; paid monthly by bank transfer under the Wage Protection System.</span></td></tr></tbody></table></>}
 <div className="grid grid-cols-2 border border-slate-700 mt-1 font-black"><div className="p-1">الحزمة المالية الشهرية</div><div className="p-1 text-left" dir="ltr">COMPENSATION MONTHLY</div></div><table className="w-full border-collapse"><tbody>{[['القسم',o.department,'Department'],['الموقع',o.work_location,'Location'],['المسمى الوظيفي',o.job_title||r?.exact_type,'Position'],['هل يوجد لديك اي أقارب / معارف',o.related_work,'Any related work at Al-alami Medical Group'],['سبب التعيين',o.appointment_reason||'احتياج العمل','Reason for appointment']].map(x=><tr key={x[0]}><td className="border border-slate-700 p-1 font-bold w-[32%]">{x[0]}</td><td className="border border-slate-700 p-1 w-[36%]">{v(x[1])}</td><td className="border border-slate-700 p-1 text-left" dir="ltr">{x[2]}</td></tr>)}</tbody></table>
 <div className="grid grid-cols-4 border border-slate-700 mt-1 text-center keep"><div className="border-l border-slate-700"><div className="font-bold p-1">الموظف</div><div className="p-1 min-h-[34px]">الاسم / Name<br/>{v(c.full_name)}</div><div className="p-1 min-h-[54px]">{o.employee_signature?<img src={o.employee_signature} alt="توقيع الموظف" className="max-h-[45px] w-full object-contain"/>:'التوقيع / Signature ........'}<br/>التاريخ / Date {v(o.employee_signature_date)}</div></div><div className="border-l border-slate-700"><div className="font-bold p-1">مدير المشروع / Project Manager</div><div className="p-1 min-h-[34px]">الاسم / Name {v(o.manager_name)}</div><div className="p-1 min-h-[54px]">{o.project_manager_signature?<img src={o.project_manager_signature} alt="توقيع مدير المشروع" className="max-h-[45px] w-full object-contain"/>:'التوقيع / Signature ........'}<br/>التاريخ / Date {v(o.project_manager_signature_date)}</div></div><div className="border-l border-slate-700"><div className="font-bold p-1">إدارة الموارد البشرية / Human Resources Management</div><div className="p-1 min-h-[34px]">الاسم / Name {v(o.hr_name)}</div><div className="p-1 min-h-[54px]">{o.hr_signature?<img src={o.hr_signature} alt="توقيع الموارد البشرية" className="max-h-[45px] w-full object-contain"/>:'التوقيع / Signature ........'}<br/>التاريخ / Date {v(o.hr_signature_date)}</div></div><div><div className="font-bold p-1">المدير العام / نائب المدير العام</div><div className="p-1 min-h-[34px]">General Manager - Deputy Director General<br/>{v(o.gm_name||o.general_manager_name)}</div><div className="p-1 min-h-[54px]">{o.gm_signature?<img src={o.gm_signature} alt="توقيع المدير العام" className="max-h-[45px] w-full object-contain"/>:'التوقيع / Signature ........'}<br/>التاريخ / Date {v(o.gm_signature_date)}</div></div></div>
 <div className="mt-1 text-[8px] text-slate-500">نموذج مباشرة العمل وفق النموذج المرفوع من الإدارة — تظهر الحزمة المالية فقط عند اختيار «تعيين جديد».</div>
 </div></main>
}
