'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,Copy,ExternalLink,RefreshCw,CheckCircle2,Clock3,RotateCcw} from 'lucide-react'
type Row={id:string;employee_name:string|null;employee_number:string|null;department:string|null;status:string;updated_at:string;last_ip_address:string|null;last_device_name:string|null;submitted_via_link:boolean}
export default function Records(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[employees,setEmployees]=useState<any[]>([]),[employeeId,setEmployeeId]=useState(''),[selected,setSelected]=useState<Row|null>(null),[links,setLinks]=useState<any[]>([]),[copied,setCopied]=useState('')
 const load=async()=>{setLoading(true);const [r,l,e]=await Promise.all([fetch('/api/forms/records?form_type=leave',{cache:'no-store'}),fetch('/api/forms/links',{cache:'no-store'}),fetch('/api/employees/data',{cache:'no-store'})]);const d=await r.json().catch(()=>({})),ld=await l.json().catch(()=>({})),ed=await e.json().catch(()=>({}));setRows(d.records||[]);setLinks(ld.links||[]);setEmployees(ed.employees||ed.records||[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 const make=async()=>{if(!employeeId)return;const r=await fetch('/api/forms/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({form_type:'leave',employee_id:employeeId})});if(r.ok){setEmployeeId('');await load()}}
 const label=(s:string)=>s==='leave:employee'?'الموظف':s==='leave:replacement'?'البديل':s==='leave:hr'?'الموارد البشرية':'المدير العام'
 const copy=async(url:string)=>{await navigator.clipboard.writeText(url);setCopied(url);window.setTimeout(()=>setCopied(''),1800)}
 const reopen=async(linkId:string)=>{if(!confirm('هل تريد إعادة فتح هذا الرابط للسماح بالتعديل وإعادة الإرسال؟'))return;const r=await fetch('/api/forms/links',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({link_id:linkId})});if(r.ok){await load()}else{const d=await r.json().catch(()=>({}));alert(d.error||'تعذر إعادة فتح الرابط.')}}
 const selectedLinks=selected?links.filter((x:any)=>x.form_type==='leave'&&x.record_id===selected.id&&x.link_scope?.startsWith('leave:')):[]
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-6xl mx-auto"><header className="flex flex-col lg:flex-row lg:justify-between lg:items-center gap-4 mb-6"><div><div className="text-[#b88618] font-bold">مركز النماذج / طلبات الإجازة</div><h1 className="text-3xl font-black text-[#09233f]">طلبات الإجازة</h1><p className="text-slate-500 mt-1">كل طلب له روابط مستقلة للموظف والبديل عند وجوده والموارد البشرية والمدير العام.</p></div><div className="flex gap-2"><Link href="/forms" className="border bg-white rounded-xl px-4 py-2 font-bold inline-flex gap-2 items-center"><ArrowLeft size={16}/> مركز النماذج</Link><button onClick={load} className="bg-[#09233f] text-white rounded-xl px-4 py-2 font-bold inline-flex gap-2"><RefreshCw size={16}/> تحديث</button></div></header>
 <section className="bg-[#09233f] text-white rounded-2xl p-5 mb-6"><h2 className="font-black text-lg">إنشاء طلب إجازة</h2><p className="text-slate-300 text-sm mt-1">اختر الموظف لإنشاء طلب جديد ورابط الموظف الخاص به. بعد إرسال الطلب تُنشأ روابط الاعتماد التالية تلقائيًا.</p><div className="mt-4 flex flex-col sm:flex-row gap-2"><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="flex-1 rounded-lg px-3 py-2 text-slate-800"><option value="">اختر الموظف</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_number||'بدون رقم'} — {e.full_name||'بدون اسم'}</option>)}</select><button disabled={!employeeId} onClick={make} className="bg-[#b88618] rounded-lg px-5 py-2 font-bold disabled:opacity-50">إنشاء طلب الإجازة</button></div></section>
 <section className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 border-b font-black">سجل طلبات الإجازة</div>{loading?<div className="p-10 text-center">جارٍ التحميل...</div>:<div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-100"><tr><th className="p-3 text-right">الموظف</th><th className="p-3 text-right">القسم</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">التاريخ</th><th className="p-3 text-right">الإجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-bold">{r.employee_name||'—'}<div className="text-xs text-slate-500">{r.employee_number||''}</div></td><td className="p-3">{r.department||'—'}</td><td className="p-3">{r.status}</td><td className="p-3">{new Date(r.updated_at).toLocaleString('ar-SA')}</td><td className="p-3 flex gap-2"><button onClick={()=>setSelected(r)} className="bg-emerald-700 text-white rounded-lg px-3 py-2 font-bold inline-flex gap-1"><ExternalLink size={15}/> روابط الطلب</button><Link href={`/forms/records/${r.id}`} className="bg-[#09233f] text-white rounded-lg px-3 py-2 font-bold">عرض / تعديل</Link></td></tr>)}</tbody></table>{!rows.length&&<div className="p-8 text-center text-slate-500">لا توجد نماذج مسجلة.</div>}</div>}</section>
 {selected&&<section className="mt-6 bg-white border rounded-2xl p-5"><div className="flex justify-between items-center mb-4"><div><h2 className="text-xl font-black text-[#09233f]">روابط طلب الإجازة</h2><p className="text-sm text-slate-500">{selected.employee_name||'—'} — الروابط خاصة بهذا الطلب فقط.</p></div><button onClick={()=>setSelected(null)} className="border rounded-lg px-3 py-2 font-bold">إغلاق</button></div>{selectedLinks.length?<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{selectedLinks.map((x:any)=><div key={x.id} className="border rounded-xl p-4"><div className="font-black text-[#09233f]">{label(x.link_scope)}</div><div className={`mt-2 text-sm font-bold ${x.last_submitted_at?'text-emerald-700':'text-amber-700'}`}>{x.last_submitted_at?<><CheckCircle2 size={15} className="inline ml-1"/>تم الاعتماد</>:<><Clock3 size={15} className="inline ml-1"/>قيد الانتظار</>}</div><div className="flex flex-wrap gap-2 mt-3"><button onClick={()=>reopen(x.id)} className="border border-amber-300 bg-amber-50 text-amber-800 rounded-lg px-3 py-2 font-bold text-xs inline-flex items-center gap-1"><RotateCcw size={14}/>إعادة فتح</button><a target="_blank" rel="noreferrer" href={x.public_url} className="flex-1 min-w-[80px] bg-[#09233f] text-white rounded-lg px-3 py-2 font-bold text-xs text-center"><ExternalLink size={14} className="inline ml-1"/>فتح الرابط</a><button onClick={()=>copy(x.public_url)} className="border rounded-lg px-3 py-2 font-bold text-xs inline-flex items-center gap-1"><Copy size={14}/>نسخ الرابط</button></div></div>)}</div>:<div className="p-6 rounded-xl bg-slate-50 text-center text-slate-500">لم يتم إرسال طلب الموظف بعد، لذلك لم تُنشأ روابط الاعتماد التالية.</div>}</section>}{copied&&<div className="form-copy-toast">تم نسخ الرابط بنجاح</div>}
 </div></main>
}