import {NextRequest,NextResponse} from 'next/server'
import * as XLSX from 'xlsx'
import {getServerAuth,supabaseAdminHeaders,SUPABASE_URL} from '@/lib/server-auth'

const ALLOWED=['admin','hr','manager','finance','general_manager']
const SERVICE=()=>({Authorization:'Bearer '+(process.env.SUPABASE_SERVICE_ROLE_KEY||''),'apikey':process.env.SUPABASE_SERVICE_ROLE_KEY||'','Content-Type':'application/json'})
async function rest(path:string,init?:RequestInit){return fetch(SUPABASE_URL+'/rest/v1/'+path,{...init,headers:{...SERVICE(),...(init?.headers||{})},cache:'no-store'})}
async function json(path:string,init?:RequestInit){const r=await rest(path,init);const t=await r.text();let b:any=[];try{b=t?JSON.parse(t):[]}catch{b={raw:t}};if(!r.ok)throw new Error(b?.message||b?.error||t||'تعذر تنفيذ العملية');return b}
function norm(v:any){return String(v??'').trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[\s\-_\.\/]+/g,'')}
function cleanId(v:any){return String(v??'').replace(/\s/g,'').replace(/^0+/,'')||''}
function excelDate(v:any){if(v==null||v==='')return null;if(v instanceof Date)return v;if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);if(!d)return null;return new Date(Date.UTC(d.y,d.m-1,d.d,d.H||0,d.M||0,d.S||0))}const s=String(v).trim();const m=s.match(/^(\d{1,4})[\/-](\d{1,2})[\/-](\d{1,4})/);if(m){let a=+m[1],b=+m[2],c=+m[3];let y=a>31?a:c>31?c:a;let mo=a>31?b:b>31?a:b;let da=a>31?c:c>31?a:c;return new Date(Date.UTC(y,mo-1,da))}const d=new Date(s);return Number.isNaN(d.getTime())?null:d}
function excelTime(v:any){if(v==null||v==='')return null;if(typeof v==='number'){const mins=Math.round(v*24*60);return {h:Math.floor(mins/60)%24,m:mins%60}}const s=String(v).trim();const m=s.match(/(\d{1,2})[:.](\d{2})(?:[:.](\d{2}))?/);if(!m)return null;let h=+m[1],mi=+m[2];if(/pm/i.test(s)&&h<12)h+=12;if(/am/i.test(s)&&h===12)h=0;return {h,m:mi}}
function combine(date:any,time:any){const d=excelDate(date),t=excelTime(time);if(!d||!t)return null;d.setUTCHours(t.h,t.m,0,0);return d.toISOString()}
function guess(headers:string[],aliases:string[]){const hs=headers.map(norm);for(const a of aliases){const n=norm(a);const i=hs.findIndex(h=>h===n||h.includes(n)||n.includes(h));if(i>=0)return headers[i]}return null}
function autoMapping(headers:string[]){return {
 employee_number:guess(headers,['Employee ID','Employee No','Employee Number','الرقم الوظيفي','رقم الموظف','Emp ID']),
 national_id:guess(headers,['National ID','Iqama','Iqama No','Identity','رقم الهوية','رقم الاقامة','رقم الإقامة','الهوية','الإقامة']),
 employee_name:guess(headers,['Employee Name','Name','Full Name','اسم الموظف','الاسم']),
 date:guess(headers,['Date','Attendance Date','Work Date','التاريخ','تاريخ']),
 check_in:guess(headers,['Check In','In Time','Entry','وقت الدخول','الدخول','بصمة الدخول']),
 check_out:guess(headers,['Check Out','Out Time','Exit','وقت الخروج','الخروج','بصمة الخروج']),
 status:guess(headers,['Status','Attendance Status','الحالة','حالة الحضور']),
 late_minutes:guess(headers,['Late Minutes','Late','التأخير','دقائق التأخير']),
 early_leave_minutes:guess(headers,['Early Leave','Early Minutes','الانصراف المبكر']),
 overtime_hours:guess(headers,['Overtime','OT Hours','الإضافي','ساعات إضافية'])
}}
function parseRows(data:any[],headers:string[],mapping:any,employees:any[]){const byEmp=new Map<string,any>(),byNat=new Map<string,any>(),byName=new Map<string,any>();for(const e of employees){if(e.employee_number)byEmp.set(cleanId(e.employee_number),e);if(e.national_id)byNat.set(cleanId(e.national_id),e);byName.set(norm(e.full_name),e)}
let matched=0,unmatched=0,errors=0,duplicates=0;const seen=new Set<string>();const rows:any[]=[]
for(let i=0;i<data.length;i++){const raw=data[i]||{};const empNo=cleanId(mapping.employee_number?raw[mapping.employee_number]:'');const nat=cleanId(mapping.national_id?raw[mapping.national_id]:'');const name=String(mapping.employee_name?raw[mapping.employee_name]||'':'').trim();let emp=empNo?byEmp.get(empNo):null,method=emp?'employee_number':'';if(!emp&&nat){emp=byNat.get(nat);method=emp?'national_id':''}if(!emp&&name){emp=byName.get(norm(name));method=emp?'name':''}
const date=excelDate(mapping.date?raw[mapping.date]:null);const cin=combine(date,mapping.check_in?raw[mapping.check_in]:null);const cout=combine(date,mapping.check_out?raw[mapping.check_out]:null);const status=String(mapping.status?raw[mapping.status]||'':'').trim();const key=(emp?.id||empNo||nat||norm(name))+'|'+(date?date.toISOString().slice(0,10):'')+'|'+(cin||'')+'|'+(cout||'');let err='';if(!date)err='التاريخ غير صالح أو غير موجود';if(seen.has(key)&&key!=='|')duplicates++;seen.add(key);if(!emp){unmatched++;if(!err)err='الموظف غير موجود في قاعدة بيانات HR2'}else matched++;if(err)errors++;rows.push({row_number:i+2,raw_data:raw,employee_id:emp?.id||null,employee_number:empNo||emp?.employee_number||null,national_id:nat||emp?.national_id||null,employee_name:name||emp?.full_name||null,attendance_date:date?date.toISOString().slice(0,10):null,check_in:cin,check_out:cout,attendance_status:status||((cin||cout)?'present':'absent'),late_minutes:Number(mapping.late_minutes?raw[mapping.late_minutes]||0:0)||0,early_leave_minutes:Number(mapping.early_leave_minutes?raw[mapping.early_leave_minutes]||0:0)||0,overtime_hours:Number(mapping.overtime_hours?raw[mapping.overtime_hours]||0:0)||0,match_method:method,match_status:emp?'matched':'unmatched',error_message:err||null})}
return {rows,stats:{imported_rows:rows.length,matched_rows:matched,unmatched_rows:unmatched,error_rows:errors,duplicate_rows:duplicates}}}
async function uploadStorage(path:string,file:File){const r=await fetch(SUPABASE_URL+'/storage/v1/object/payroll-attendance/'+path,{method:'POST',headers:{Authorization:'Bearer '+(process.env.SUPABASE_SERVICE_ROLE_KEY||''),apikey:process.env.SUPABASE_SERVICE_ROLE_KEY||'', 'x-upsert':'true','Content-Type':file.type||'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'},body:Buffer.from(await file.arrayBuffer())});if(!r.ok)throw new Error('تعذر حفظ ملف شيت البصمة في الأرشيف.');return path}
async function getSheet(id:string){const a=await json('payroll_attendance_sheets?id=eq.'+encodeURIComponent(id)+'&limit=1');return a[0]||null}

export async function GET(req:NextRequest){const auth=await getServerAuth(req,ALLOWED);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});try{const p=new URL(req.url).searchParams,month=p.get('month'),year=p.get('year'),id=p.get('id');if(id){const sheet=await getSheet(id);if(!sheet)return NextResponse.json({error:'الشيت غير موجود'},{status:404});const rows=await json('payroll_attendance_sheet_rows?select=*,employee:employee_records(employee_number,full_name,national_id,job_title,department,project_name)&sheet_id=eq.'+id+'&order=row_number');return NextResponse.json({sheet,rows})}const filters=month&&year?'&month=eq.'+month+'&year=eq.'+year:'';const sheets=await json('payroll_attendance_sheets?select=*&order=year.desc,month.desc'+filters);const runs=await json('payroll_runs?select=id,month,year,status,attendance_sheet_id&order=year.desc,month.desc');const enriched=sheets.map((s:any)=>({...s,linked_run:runs.find((r:any)=>r.attendance_sheet_id===s.id)?.id||null}));return NextResponse.json({sheets:enriched,runs})}catch(e:any){return NextResponse.json({error:e.message||'تعذر تحميل شيتات البصمة'},{status:500})}}

export async function POST(req:NextRequest){const auth=await getServerAuth(req,ALLOWED);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});try{
 const ct=req.headers.get('content-type')||''
 if(ct.includes('multipart/form-data')){
  const form=await req.formData(),month=Number(form.get('month')),year=Number(form.get('year')),file=form.get('file');if(!month||month<1||month>12||!year||!(file instanceof File))return NextResponse.json({error:'اختر الشهر والسنة وملف Excel.'},{status:400});
  const buf=Buffer.from(await file.arrayBuffer());const wb=XLSX.read(buf,{type:'buffer',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];if(!ws)return NextResponse.json({error:'الملف لا يحتوي على ورقة بيانات.'},{status:400});const data=XLSX.utils.sheet_to_json(ws,{defval:''});const headers=Object.keys(data[0]||{});if(!headers.length)return NextResponse.json({error:'لم يتم العثور على أعمدة في الشيت.'},{status:400});
  const employees=await json('employee_records?select=id,employee_number,full_name,national_id');
  const mapping=autoMapping(headers);const parsed=parseRows(data,headers,mapping,employees);const existing=(await json('payroll_attendance_sheets?select=*&month=eq.'+month+'&year=eq.'+year+'&limit=1'))[0];
  if(existing&&existing.status==='approved')return NextResponse.json({error:'تم اعتماد شيت هذا الشهر، لا يمكن استبداله إلا بعد إعادة فتح الشهر/المسير.'},{status:409});
  const path=year+'/'+String(month).padStart(2,'0')+'/'+Date.now()+'-'+String(file.name).replace(/[^a-zA-Z0-9._-]/g,'_');await uploadStorage(path,file);
  let sheet:any;
  if(existing){await json('payroll_attendance_sheet_rows?sheet_id=eq.'+existing.id,{method:'DELETE'});sheet=(await json('payroll_attendance_sheets?id=eq.'+existing.id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({file_name:file.name,storage_path:path,uploaded_by:auth.user.id,uploaded_by_name:auth.user.email,uploaded_at:new Date().toISOString(),status:'uploaded',mapping,headers,preview_stats:parsed.stats,replaced_at:new Date().toISOString(),replaced_by:auth.user.id,approved_at:null,approved_by:null,approved_by_name:null,updated_at:new Date().toISOString()})}))[0]}else sheet=(await json('payroll_attendance_sheets',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({month,year,file_name:file.name,storage_path:path,uploaded_by:auth.user.id,uploaded_by_name:auth.user.email,mapping,headers,preview_stats:parsed.stats})}))[0];
  const rows=parsed.rows.map((x:any)=>({...x,sheet_id:sheet.id}));for(let i=0;i<rows.length;i+=500)await json('payroll_attendance_sheet_rows',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(rows.slice(i,i+500))});
  await json('payroll_attendance_imports',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({file_name:file.name,imported_rows:parsed.stats.imported_rows,matched_rows:parsed.stats.matched_rows,skipped_rows:parsed.stats.unmatched_rows,errors:parsed.rows.filter((x:any)=>x.error_message).slice(0,200),created_by:auth.user.id,sheet_id:sheet.id,month,year})});
  return NextResponse.json({sheet,headers,mapping,stats:parsed.stats})
 }
 const b=await req.json(),action=b.action;if(action==='save_mapping'){const sheet=await getSheet(b.sheet_id);if(!sheet)return NextResponse.json({error:'الشيت غير موجود'},{status:404});const rows=await json('payroll_attendance_sheet_rows?select=raw_data,row_number&sheet_id=eq.'+sheet.id+'&order=row_number');const employees=await json('employee_records?select=id,employee_number,full_name,national_id');const parsed=parseRows(rows.map((x:any)=>x.raw_data),sheet.headers||[],b.mapping||{},employees);await json('payroll_attendance_sheet_rows?sheet_id=eq.'+sheet.id,{method:'DELETE'});const fresh=parsed.rows.map((x:any)=>({...x,sheet_id:sheet.id}));for(let i=0;i<fresh.length;i+=500)await json('payroll_attendance_sheet_rows',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(fresh.slice(i,i+500))});const updated=(await json('payroll_attendance_sheets?id=eq.'+sheet.id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({mapping:b.mapping,preview_stats:parsed.stats,updated_at:new Date().toISOString()})}))[0];return NextResponse.json({sheet:updated,stats:parsed.stats})}
 if(action==='approve'){const sheet=await getSheet(b.sheet_id);if(!sheet)return NextResponse.json({error:'الشيت غير موجود'},{status:404});if(sheet.status==='approved')return NextResponse.json({sheet});const stats=sheet.preview_stats||{};if(stats.error_rows>0||stats.unmatched_rows>0)return NextResponse.json({error:'لا يمكن اعتماد الشيت قبل معالجة السجلات غير المرتبطة والأخطاء.'},{status:409});const updated=(await json('payroll_attendance_sheets?id=eq.'+sheet.id,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'approved',approved_at:new Date().toISOString(),approved_by:auth.user.id,approved_by_name:auth.user.email,updated_at:new Date().toISOString()})}))[0];return NextResponse.json({sheet:updated})}
 if(action==='save_column_template'){const key=String(b.key||'default');const row=(await json('payroll_attendance_column_mappings?mapping_key=eq.'+encodeURIComponent(key)+'&limit=1'))[0];const body={mapping_key:key,mapping:b.mapping||{},updated_by:auth.user.id,updated_by_name:auth.user.email,updated_at:new Date().toISOString()};const out=(await json(row?'payroll_attendance_column_mappings?id=eq.'+row.id:'payroll_attendance_column_mappings',{method:row?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)}))[0];return NextResponse.json({mapping:out})}
 if(action==='monthly'){const month=Number(b.month),year=Number(b.year);const sheet=(await json('payroll_attendance_sheets?select=*&month=eq.'+month+'&year=eq.'+year+'&status=eq.approved&limit=1'))[0];if(!sheet)return NextResponse.json({error:'لم يتم اعتماد شيت البصمة لهذا الشهر.'},{status:404});const rows=await json('payroll_attendance_sheet_rows?select=*,employee:employee_records(employee_number,full_name,national_id,job_title,department,project_name,work_location)&sheet_id=eq.'+sheet.id+'&order=attendance_date,row_number');return NextResponse.json({sheet,rows})}
 return NextResponse.json({error:'عملية غير معروفة'},{status:400})
 }catch(e:any){return NextResponse.json({error:e.message||'تعذر تنفيذ عملية شيت البصمة'},{status:500})}}
