'use client'
import {useEffect,useMemo,useState} from 'react'
import {Search,Plus,Edit3,Trash2,Printer,X,RefreshCw,BriefcaseBusiness} from 'lucide-react'

type Job={id:string;name:string;department:string;manager?:string|null;purpose?:string|null;responsibilities?:string[];routine?:string[];authorities?:string[];qualifications?:string[];experience?:string[];skills?:string[];kpi?:string[];compliance?:string[]}
const arr=(v:any)=>Array.isArray(v)?v:[]
const blank:Partial<Job>={name:'',department:'',manager:'',purpose:'',responsibilities:[],routine:[],authorities:[],qualifications:[],experience:[],skills:[],kpi:[],compliance:[]}
const sections:[keyof Job,string][]=[['purpose','الهدف العام من الوظيفة'],['responsibilities','المهام والمسؤوليات الرئيسية'],['routine','المهام اليومية / الدورية'],['authorities','الصلاحيات والمسؤوليات'],['qualifications','المؤهلات'],['experience','الخبرات'],['skills','المهارات'],['kpi','مؤشرات الأداء KPI'],['compliance','متطلبات الالتزام والانضباط']]

export default function JobDescriptions(){
 const[jobs,setJobs]=useState<Job[]>([]),[q,setQ]=useState(''),[dept,setDept]=useState('الكل'),[sort,setSort]=useState('name'),[selected,setSelected]=useState<Job|null>(null),[editing,setEditing]=useState<Job|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/job-descriptions',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'تعذر تحميل الأوصاف');setJobs(b.jobs||[])}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الأوصاف')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const departments=useMemo(()=>['الكل',...Array.from(new Set(jobs.map(j=>j.department).filter(Boolean)))],[jobs])
 const filtered=useMemo(()=>{const x=jobs.filter(j=>(dept==='الكل'||j.department===dept)&&[j.name,j.department,j.manager,j.purpose].join(' ').toLowerCase().includes(q.trim().toLowerCase()));return x.sort((a,b)=>sort==='dept'?a.department.localeCompare(b.department,'ar')||a.name.localeCompare(b.name,'ar'):a.name.localeCompare(b.name,'ar'))},[jobs,q,dept,sort])
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;const method=editing.id?'PATCH':'POST';const r=await fetch('/api/job-descriptions',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});const b=await r.json();if(!r.ok){alert(b.error||'تعذر الحفظ');return}setJobs(x=>editing.id?x.map(j=>j.id===editing.id?b.job:j):[b.job,...x]);setEditing(null)}
 const remove=async(j:Job)=>{if(!confirm('هل أنت متأكد من حذف وصف «'+j.name+'»؟'))return;const r=await fetch('/api/job-descriptions?id='+encodeURIComponent(j.id),{method:'DELETE'});if(!r.ok){alert('تعذر حذف الوصف الوظيفي');return}setJobs(x=>x.filter(a=>a.id!==j.id));if(selected?.id===j.id)setSelected(null)}
 const listValue=(v:any)=>arr(v).join('\n')
 const update=(key:keyof Job,v:any)=>setEditing(x=>x?({...x,[key]:key==='purpose'?v:v.split('\n').map((s:string)=>s.trim()).filter(Boolean)}):x)
 return <main dir="rtl" className="min-h-screen bg-[#f6f0e5] text-[#24313b]">
  <header className="bg-[#12304a] text-white px-5 md:px-8 py-4 shadow-lg"><div className="max-w-[1500px] mx-auto flex flex-col lg:flex-row lg:items-center justify-between gap-4">
   <div className="flex items-center gap-3"><div className="h-12 w-12 rounded-xl border border-white/30 grid place-items-center font-black text-[#d1aa56]">HR</div><div><h1 className="text-xl font-black">مكتبة الأوصاف الوظيفية</h1><p className="text-xs text-slate-300 mt-1">مرجع داخلي للموظفين والإدارة والموارد البشرية • {jobs.length} وظيفة / {Math.max(0,departments.length-1)} قسم</p></div></div>
   <div className="flex gap-2 flex-wrap"><button onClick={()=>setEditing({...blank} as Job)} className="rounded-lg px-4 py-2 bg-[#d1aa56] text-[#0c2438] font-black inline-flex items-center gap-2"><Plus size={17}/> إضافة وظيفة</button><button onClick={load} className="rounded-lg px-3 py-2 bg-white/10 border border-white/20"><RefreshCw size={17}/></button></div>
  </div></header>
  <div className="max-w-[1500px] mx-auto grid lg:grid-cols-[250px_1fr] gap-6 p-5 md:p-7">
   <aside className="bg-[#fffdf9] border border-[#e5ddd0] rounded-2xl p-4 h-max lg:sticky lg:top-4"><div className="font-black text-[#12304a] mb-3">التنقل الرئيسي</div><button className="w-full text-right rounded-xl px-3 py-3 bg-[#f1e8d7] text-[#12304a] font-black flex justify-between"><span className="flex gap-2"><BriefcaseBusiness size={19}/>الوصف الوظيفي</span><span>⌄</span></button><div className="mt-2 space-y-1">{departments.slice(1).map(d=><button key={d} onClick={()=>setDept(d)} className={'w-full text-right px-3 py-2 rounded-lg text-sm flex justify-between '+(dept===d?'bg-[#f1e8d7] font-black':'hover:bg-[#faf5ec]')}><span>{d}</span><b className="text-[10px] bg-[#eee4d2] rounded-full px-2 py-0.5">{jobs.filter(j=>j.department===d).length}</b></button>)}</div><div className="mt-5 border-t border-[#e5ddd0] pt-4 text-xs leading-7 text-[#6e7880]"><b className="text-[#b18425]">مكتبة داخلية</b><br/>الأوصاف مخصصة للوظائف الحالية داخل الشركة وليست لإعلانات التوظيف.</div></aside>
   <section><div className="bg-[#12304a] text-white rounded-2xl p-6 flex flex-col md:flex-row md:items-center justify-between gap-5 shadow-[0_14px_40px_rgba(18,48,74,.10)]"><div><span className="text-[11px] font-black tracking-widest text-[#d1aa56]">HR • JOB DESCRIPTION</span><h2 className="text-2xl font-black mt-1">مكتبة الوصف الوظيفي</h2><p className="text-sm text-slate-300 mt-2 max-w-3xl leading-7">ابحث عن الوظيفة، راجع مسؤولياتها ومؤشرات الأداء، ثم اطبع الوصف أو احفظه بصيغة PDF.</p></div><div className="flex gap-2"><div className="bg-white/10 border border-white/10 rounded-xl px-5 py-3 text-center"><b className="block text-2xl text-[#d1aa56]">{jobs.length}</b><span className="text-[11px]">وظيفة</span></div><div className="bg-white/10 border border-white/10 rounded-xl px-5 py-3 text-center"><b className="block text-2xl text-[#d1aa56]">{Math.max(0,departments.length-1)}</b><span className="text-[11px]">قسم</span></div></div></div>
    <div className="flex gap-2 my-4"><div className="flex-1 bg-white border border-[#e5ddd0] rounded-xl flex items-center px-3"><Search size={20} className="text-[#b18425]"/><input value={q} onChange={e=>setQ(e.target.value)} className="border-0 outline-none w-full p-3 bg-transparent" placeholder="ابحث باسم الوظيفة أو القسم أو المسؤول المباشر..."/></div><select value={sort} onChange={e=>setSort(e.target.value)} className="bg-white border border-[#e5ddd0] rounded-xl px-3"><option value="name">ترتيب: اسم الوظيفة</option><option value="dept">ترتيب: القسم</option></select></div>
    {error&&<div className="mb-4 p-4 rounded-xl bg-red-50 text-red-700">{error}</div>}{loading?<div className="bg-white rounded-2xl p-12 text-center">جاري تحميل مكتبة الأوصاف...</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(j=><article key={j.id} className="bg-[#fffdf9] border border-[#e5ddd0] rounded-[17px] p-5 shadow-sm hover:-translate-y-1 transition flex flex-col min-h-[220px]"><span className="inline-flex self-start bg-[#f0e6d4] text-[#765719] px-2 py-1 rounded-md text-[11px] font-black">{j.department}</span><h3 className="text-lg font-black text-[#12304a] mt-3">{j.name}</h3><div className="text-xs text-[#6e7880]">الرئيس المباشر: {j.manager||'—'}</div><p className="text-sm leading-7 text-[#4e5961] mt-3 line-clamp-3">{j.purpose||'لا يوجد هدف عام مسجل.'}</p><div className="mt-auto flex justify-between items-center gap-2"><button onClick={()=>setSelected(j)} className="bg-[#12304a] text-white rounded-lg px-3 py-2 text-xs font-black">فتح الوصف</button><div className="flex gap-1"><button onClick={()=>setEditing(j)} className="text-[#b18425] p-2" title="تعديل"><Edit3 size={16}/></button><button onClick={()=>remove(j)} className="text-red-600 p-2" title="حذف"><Trash2 size={16}/></button></div></div></article>)}</div>}{!loading&&!filtered.length&&<div className="text-center py-12 text-[#6e7880]">لا توجد وظائف مطابقة للبحث الحالي.</div>}</section>
  </div>
  {selected&&<div className="fixed inset-0 z-50 bg-[#05121d]/70 grid place-items-center p-4"><div className="bg-[#fffdf9] rounded-2xl w-full max-w-5xl max-h-[92vh] overflow-auto p-6 relative shadow-2xl"><button onClick={()=>setSelected(null)} className="absolute top-4 left-4 h-9 w-9 rounded-full bg-[#f0e9dd] grid place-items-center"><X size={20}/></button><div className="border-b border-[#e5ddd0] pb-4 mb-4"><span className="text-[11px] font-black text-[#b18425]">{selected.department}</span><h2 className="text-3xl font-black text-[#12304a] mt-1">{selected.name}</h2><p className="text-xs text-[#6e7880] mt-1">الرئيس المباشر: {selected.manager||'—'}</p><div className="flex gap-2 mt-4 print:hidden"><button onClick={()=>window.print()} className="bg-[#d1aa56] text-[#0c2438] rounded-lg px-4 py-2 font-black inline-flex gap-2"><Printer size={16}/> طباعة / PDF</button><button onClick={()=>{setEditing(selected);setSelected(null)}} className="border border-[#e5ddd0] rounded-lg px-4 py-2 font-black">تعديل</button></div></div><div className="grid md:grid-cols-2 gap-3">{sections.map(([key,title])=>{const v=selected[key];if(!v||(Array.isArray(v)&&!v.length))return null;return <div key={String(key)} className={'border border-[#e5ddd0] rounded-xl p-4 bg-white '+(key==='purpose'?'md:col-span-2':'')}><h3 className="font-black text-[#12304a] border-r-4 border-[#b18425] pr-2 mb-2">{title}</h3>{key==='purpose'?<p className="text-sm leading-7">{String(v)}</p>:<ul className="list-disc pr-5 text-sm leading-7">{arr(v).map((x,i)=><li key={i}>{x}</li>)}</ul>}</div>})}</div></div></div>}
  {editing&&<div className="fixed inset-0 z-[60] bg-[#05121d]/70 grid place-items-center p-4"><div className="bg-[#fffdf9] rounded-2xl w-full max-w-4xl max-h-[94vh] overflow-auto p-6 relative"><button onClick={()=>setEditing(null)} className="absolute top-4 left-4 h-9 w-9 rounded-full bg-[#f0e9dd] grid place-items-center"><X size={20}/></button><h2 className="text-2xl font-black text-[#12304a] mb-5">{editing.id?'تعديل الوصف الوظيفي':'إضافة وصف وظيفي'}</h2><form onSubmit={save} className="space-y-3"><div className="grid md:grid-cols-2 gap-3"><label className="font-bold text-xs">المسمى الوظيفي<input required value={editing.name||''} onChange={e=>setEditing({...editing,name:e.target.value})} className="mt-1 w-full"/></label><label className="font-bold text-xs">الإدارة / القسم<input required value={editing.department||''} onChange={e=>setEditing({...editing,department:e.target.value})} className="mt-1 w-full"/></label><label className="font-bold text-xs">الرئيس المباشر<input value={editing.manager||''} onChange={e=>setEditing({...editing,manager:e.target.value})} className="mt-1 w-full"/></label></div>{sections.map(([key,title])=><label key={String(key)} className="block font-bold text-xs">{title}<textarea rows={key==='purpose'?3:5} value={key==='purpose'?String(editing[key]||''):listValue(editing[key])} onChange={e=>update(key,e.target.value)} className="mt-1 w-full"/></label>)}<div className="flex gap-2 pt-3"><button type="submit" className="bg-[#d1aa56] text-[#0c2438] rounded-lg px-5 py-2 font-black">حفظ في قاعدة البيانات</button><button type="button" onClick={()=>setEditing(null)} className="border border-[#e5ddd0] rounded-lg px-5 py-2">إلغاء</button></div></form></div></div>}
 </main>
}
