import {NextRequest,NextResponse} from 'next/server'
import {getServerAuth,supabaseHeaders} from '@/lib/server-auth'
const ROLES=['admin','hr','manager']
const URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://pdkdvaisggntdrvpxuur.supabase.co'
async function rest(path:string,auth:any,init?:RequestInit){return fetch(URL+'/rest/v1/'+path,{...init,headers:{...supabaseHeaders(auth),...(init?.headers||{})},cache:'no-store'})}
async function json(path:string,auth:any,init?:RequestInit){const r=await rest(path,auth,init);const t=await r.text();let b:any={};try{b=t?JSON.parse(t):{}}catch{b={raw:t}};if(!r.ok)throw new Error(b.message||b.error||t||'تعذر تنفيذ العملية');return b}
function money(v:any){const n=Number(v);return Number.isFinite(n)?Math.round(n*100)/100:0}
async function audit(auth:any,action:string,entity:string,id:string|undefined,before:any,after:any){await rest('payroll_audit_log',{...auth,},{}) .catch(()=>{}); await rest('payroll_audit_log',auth,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:auth.user.id,user_name:auth.user.email,action,entity_type:entity,entity_id:id||null,before_data:before||null,after_data:after||null})})}
function can(role:string,p:string){return role==='admin'||(role==='hr'&&['view','create_run','edit_payroll','approve_hr','manage_advances','manage_deductions','manage_overtime','reports'].includes(p))||(role==='manager'&&['view','reports','approve_overtime'].includes(p))}
export async function GET(req:NextRequest){
 try{const auth=await getServerAuth(req,ROLES);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});const p=new URL(req.url).searchParams;const action=p.get('action')||'dashboard';if(!can(auth.role,'view')&&!can(auth.role,'reports'))return NextResponse.json({error:'لا تملك صلاحية الرواتب'},{status:403})
  if(action==='dashboard'){const now=new Date(),month=Number(p.get('month')||now.getMonth()+1),year=Number(p.get('year')||now.getFullYear());const [runs,emps]=await Promise.all([json('payroll_runs?select=*&month=eq.'+month+'&year=eq.'+year+'&order=created_at.desc',auth),json('employee_records?select=id,employee_number,full_name,nationality,job_title,department,project_name,basic_salary,housing_allowance,transportation_allowance,other_allowances,total_salary_with_allowances,bank_name,iban,gosi_status&order=full_name',auth)]);let current:any=null;if(runs[0]){current=runs[0];current.items=await json('payroll_items?select=*&run_id=eq.'+current.id,auth)}const items=current?.items||[];return NextResponse.json({month,year,current,employees:emps,stats:{employees:items.length,total_basic:items.reduce((s:any,x:any)=>s+money(x.basic_salary),0),allowances:items.reduce((s:any,x:any)=>s+money(x.housing_allowance)+money(x.transportation_allowance)+money(x.other_allowances),0),overtime:items.reduce((s:any,x:any)=>s+money(x.overtime),0),bonuses:items.reduce((s:any,x:any)=>s+money(x.bonuses),0),deductions:items.reduce((s:any,x:any)=>s+money(x.total_deductions),0),net:items.reduce((s:any,x:any)=>s+money(x.net_salary),0)},missing:emps.filter((e:any)=>!e.basic_salary||!e.iban).map((e:any)=>({id:e.id,name:e.full_name,reason:!e.basic_salary?'راتب أساسي ناقص':'IBAN ناقص'}))})}
  if(action==='employees')return NextResponse.json({employees:await json('employee_records?select=id,employee_number,full_name,nationality,job_title,department,project_name,basic_salary,housing_allowance,transportation_allowance,other_allowances,total_salary_with_allowances,bank_name,bank_account_number,iban,iban_verified,gosi_status,gosi_subscriber_wage,gosi_employee_share,gosi_employer_share,payroll_cost_center,payroll_cost_allocation&order=full_name',auth)})
  if(action==='runs')return NextResponse.json({runs:await json('payroll_runs?select=*&order=year.desc,month.desc,created_at.desc',auth)})
  if(action==='run'){const id=p.get('id');if(!id)return NextResponse.json({error:'رقم المسير مطلوب'},{status:400});const [run,items,approvals]=await Promise.all([json('payroll_runs?select=*&id=eq.'+id+'&limit=1',auth),json('payroll_items?select=*,employee:employee_records(employee_number,full_name,nationality,job_title,department,project_name)&run_id=eq.'+id+'&order=created_at',auth),json('payroll_approvals?select=*&run_id=eq.'+id+'&order=approved_at',auth)]);return NextResponse.json({run:run[0]||null,items,approvals})}
  if(action==='overtime')return NextResponse.json({rows:await json('payroll_overtime?select=*,employee:employee_records(employee_number,full_name),project:payroll_projects(name)&order=work_date.desc',auth)})
  if(action==='deductions')return NextResponse.json({rows:await json('payroll_deductions?select=*,employee:employee_records(employee_number,full_name)&order=deduction_date.desc',auth)})
  if(action==='advances')return NextResponse.json({rows:await json('payroll_advances?select=*,employee:employee_records(employee_number,full_name)&order=advance_date.desc',auth)})
  if(action==='bonuses')return NextResponse.json({rows:await json('payroll_bonuses?select=*,employee:employee_records(employee_number,full_name)&order=award_date.desc',auth)})
  if(action==='attendance')return NextResponse.json({rows:await json('payroll_attendance?select=*,employee:employee_records(employee_number,full_name)&order=work_date.desc',auth)})
  if(action==='projects')return NextResponse.json({projects:await json('payroll_projects?select=*&order=name')})
  if(action==='project-costs'){const runs=await json('payroll_runs?select=*&order=year.desc,month.desc',auth);const ids=runs.map((x:any)=>x.id);let items:any[]=[];if(ids.length)items=await json('payroll_items?select=*,employee:employee_records(project_name)&run_id=in.('+ids.map((x:string)=>x).join(',')+')',auth);const map:any={};for(const i of items){const k=i.employee?.project_name||'غير محدد';map[k]??={project:k,employees:new Set(),basic:0,allowances:0,overtime:0,bonuses:0,deductions:0,total:0};map[k].employees.add(i.employee_id);map[k].basic+=money(i.basic_salary);map[k].allowances+=money(i.housing_allowance)+money(i.transportation_allowance)+money(i.other_allowances);map[k].overtime+=money(i.overtime);map[k].bonuses+=money(i.bonuses);map[k].deductions+=money(i.total_deductions);map[k].total+=money(i.total_earnings);};return NextResponse.json({rows:Object.values(map).map((x:any)=>({...x,employees:x.employees.size}))})}
  if(action==='settings')return NextResponse.json({settings:await json('payroll_settings?select=*&order=key',auth),permissions:await json('payroll_permissions?select=*&order=role,permission',auth)})
  if(action==='gosi'){return NextResponse.json({rows:await json('payroll_gosi?select=*,employee:employee_records(employee_number,full_name)&order=year.desc,month.desc',auth)})}
  return NextResponse.json({error:'طلب غير معروف'},{status:400})
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'تعذر تحميل بيانات الرواتب'},{status:500})}
}
export async function POST(req:NextRequest){
 try{const auth=await getServerAuth(req,ROLES);if(!auth)return NextResponse.json({error:'غير مصرح'},{status:401});const b=await req.json();const action=b.action
  const perm=action==='create_run'?'create_run':action==='save_item'||action==='update_employee_finance'?'edit_payroll':action==='overtime'?'manage_overtime':action==='deduction'?'manage_deductions':action==='advance'?'manage_advances':action==='bonus'?'edit_payroll':action==='approve'?'approve_hr':action==='setting'?'settings':action==='wps'?'export_wps':'view'
  if(!can(auth.role,perm))return NextResponse.json({error:'لا تملك الصلاحية لتنفيذ هذه العملية'},{status:403})
  if(action==='create_run'){const month=Number(b.month),year=Number(b.year);const existing=await json('payroll_runs?select=*&month=eq.'+month+'&year=eq.'+year+'&limit=1',auth);if(existing[0])return NextResponse.json({run:existing[0],existing:true});const emps=await json('employee_records?select=id,basic_salary,housing_allowance,transportation_allowance,other_allowances&employment_status=neq.منتهي',auth);const run=(await json('payroll_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({month,year,branch:b.branch||null,project_id:b.project_id||null,cost_center:b.cost_center||null,created_by:auth.user.id})}))[0];for(const e of emps){const basic=money(e.basic_salary),h=money(e.housing_allowance),t=money(e.transportation_allowance),o=money(e.other_allowances),earn=basic+h+t+o;await rest('payroll_items',auth,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({run_id:run.id,employee_id:e.id,basic_salary:basic,housing_allowance:h,transportation_allowance:t,other_allowances:o,total_earnings:earn,net_salary:earn,source_snapshot:e})})}await audit(auth,'create','payroll_run',run.id,null,run);return NextResponse.json({run})}
  if(action==='save_item'){const rows=await json('payroll_items?id=eq.'+b.id+'&limit=1',auth);if(!rows[0])return NextResponse.json({error:'بند المسير غير موجود'},{status:404});const run=(await json('payroll_runs?id=eq.'+rows[0].run_id+'&limit=1',auth))[0];if(['gm_approved','ready_to_pay','paid','closed'].includes(run.status))return NextResponse.json({error:'لا يمكن تعديل مسير معتمد/مغلق'},{status:409});const before=rows[0];const fields=['basic_salary','housing_allowance','transportation_allowance','other_allowances','overtime','bonuses','absence','lateness','advances','penalties','insurance_employee','other_deductions'];const patch:any={};for(const f of fields)if(b[f]!==undefined)patch[f]=money(b[f]);patch.total_earnings=fields.slice(0,6).reduce((s,f)=>s+money(b[f]??before[f]),0);patch.total_deductions=['absence','lateness','advances','penalties','insurance_employee','other_deductions'].reduce((s,f)=>s+money(b[f]??before[f]),0);patch.net_salary=money(patch.total_earnings-patch.total_deductions);patch.manual_overrides={...(before.manual_overrides||{}),...Object.fromEntries(fields.filter(f=>b[f]!==undefined).map(f=>[f,{previous:before[f],value:money(b[f]),user:auth.user.email,at:new Date().toISOString(),reason:b.reason||'تعديل يدوي'}]))};const after=(await json('payroll_items?id=eq.'+b.id,auth,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)}))[0];await audit(auth,'update','payroll_item',b.id,before,after);return NextResponse.json({item:after})}
  if(action==='update_employee_finance'){const before=(await json('employee_records?id=eq.'+b.employee_id+'&limit=1',auth))[0];if(!before)return NextResponse.json({error:'الموظف غير موجود'},{status:404});const allowed=['bank_name','bank_account_number','iban','iban_verified','gosi_status','gosi_subscriber_wage','payroll_cost_center','payroll_cost_allocation'];const patch:any={};for(const f of allowed)if(b[f]!==undefined)patch[f]=b[f];const after=(await json('employee_records?id=eq.'+b.employee_id,auth,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)}))[0];await audit(auth,'update','employee_finance',b.employee_id,before,after);return NextResponse.json({employee:after})}
  if(['overtime','deduction','advance','bonus'].includes(action)){const table={overtime:'payroll_overtime',deduction:'payroll_deductions',advance:'payroll_advances',bonus:'payroll_bonuses'}[action];const row={...b};delete row.action;row.created_by=auth.user.id;if(action==='advance'){row.remaining_amount=money(row.amount);row.installment_amount=money(row.amount)/Math.max(1,Number(row.installments||1));row.status='active'}const out=(await json(table,auth,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)}))[0];if(action==='advance'){const start=new Date(row.deduction_start_date);for(let i=1;i<=Number(row.installments);i++){const d=new Date(start);d.setMonth(d.getMonth()+i-1);await rest('payroll_advance_installments',auth,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({advance_id:out.id,installment_no:i,due_date:d.toISOString().slice(0,10),amount:out.installment_amount})})}}await audit(auth,'create',table,out.id,null,out);return NextResponse.json({row:out})}
  if(action==='approve'){const run=(await json('payroll_runs?id=eq.'+b.run_id+'&limit=1',auth))[0];if(!run)return NextResponse.json({error:'المسير غير موجود'},{status:404});const stage=b.stage;const map:any={hr:{from:['draft'],to:'hr_review',perm:'approve_hr'},finance:{from:['hr_review'],to:'finance_approved',perm:'approve_finance'},general_manager:{from:['finance_approved'],to:'gm_approved',perm:'approve_gm'},ready_to_pay:{from:['gm_approved'],to:'ready_to_pay',perm:'approve_gm'},paid:{from:['ready_to_pay'],to:'paid',perm:'approve_gm'},closed:{from:['paid'],to:'closed',perm:'approve_gm'}};const cfg=map[stage];if(!cfg||!cfg.from.includes(run.status)||!can(auth.role,cfg.perm))return NextResponse.json({error:'تسلسل الاعتماد أو الصلاحية غير صحيح'},{status:403});const after=(await json('payroll_runs?id=eq.'+run.id,auth,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:cfg.to,updated_at:new Date().toISOString()})}))[0];await json('payroll_approvals',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({run_id:run.id,stage,status:'approved',user_id:auth.user.id,user_name:auth.user.email,approved_at:new Date().toISOString(),notes:b.notes||null,signature:b.signature||null})});await audit(auth,'approve','payroll_run',run.id,run,after);return NextResponse.json({run:after})}
  if(action==='setting'){const row=(await json('payroll_settings?key=eq.'+encodeURIComponent(b.key)+'&limit=1',auth))[0];const after=(await json(row?'payroll_settings?id=eq.'+row.id:'payroll_settings',{method:row?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({key:b.key,value:b.value,description:b.description||null,updated_by:auth.user.id,updated_at:new Date().toISOString()})}))[0];await audit(auth,'update','payroll_setting',after.id,row,after);return NextResponse.json({setting:after})}
  if(action==='wps'){const run=(await json('payroll_runs?id=eq.'+b.run_id+'&limit=1',auth))[0];const items=await json('payroll_items?select=*,employee:employee_records(employee_number,full_name,iban)&run_id=eq.'+b.run_id,auth);const errors=items.flatMap((x:any)=>[!x.employee?.iban&&'IBAN ناقص',!x.employee?.employee_number&&'رقم موظف ناقص',x.net_salary==null&&'صافي الراتب ناقص'].filter(Boolean).map((e:string)=>({employee:x.employee?.full_name,error:e})));const payload={run_id:run.id,month:run.month,year:run.year,rows:items.map((x:any)=>({employee_number:x.employee?.employee_number,name:x.employee?.full_name,iban:x.employee?.iban,net_salary:x.net_salary}))};const out=(await json('payroll_wps_exports',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({run_id:b.run_id,format_version:b.format_version||null,file_format:b.file_format||null,validation_status:errors.length?'errors':'valid',validation_errors:errors,payload,exported_by:auth.user.id})}))[0];await audit(auth,'export','wps',out.id,null,out);return NextResponse.json({export:out,errors,payload})}
  return NextResponse.json({error:'عملية غير معروفة'},{status:400})
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'تعذر تنفيذ العملية'},{status:500})}
}
