'use client'
import {useEffect,useMemo,useState} from 'react'
import {BarChart3,CheckCircle2,ClipboardCheck,RefreshCw,Search,UserRound} from 'lucide-react'

type Employee={id:string;employee_number?:string|null;full_name:string;job_title?:string|null;department?:string|null;employment_status?:string|null}
type Job={id:string;name:string;department:string;kpi?:string[]}
type Kpi={id:string;indicator_name:string;question:string;category?:string|null;weight:number}
type Evaluation={id:string;employee_id:string;job_description_id?:string|null;evaluator_name?:string|null;evaluation_date:string;total_score?:number|null;performance_level?:string|null}

export default function KpiEvaluationPage(){
 const[employees,setEmployees]=useState<Employee[]>([]),[jobs,setJobs]=useState<Job[]>([]),[evaluations,setEvaluations]=useState<Evaluation[]>([])
 const[employeeId,setEmployeeId]=useState(''),[jobId,setJobId]=useState(''),[evaluator,setEvaluator]=useState(''),[scores,setScores]=useState<Record<string,number>>({})
 const[kpis,setKpis]=useState<Kpi[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/kpi',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'تعذر تحميل قسم KPI');setEmployees(b.employees||[]);setJobs(b.jobs||[]);setEvaluations(b.evaluations||[])}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل البيانات')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const employee=employees.find(e=>e.id===employeeId)
 const matchingJobs=useMemo(()=>{if(!employee?.job_title)return jobs;const exact=jobs.filter(j=>j.name.trim()===String(employee.job_title).trim());return exact.length?exact:jobs},[employee,jobs])
 useEffect(()=>{if(employee?.job_title){const exact=jobs.find(j=>j.name.trim()===String(employee.job_title).trim());if(exact)setJobId(exact.id)}},[employeeId,jobs])
 const filteredEmployees=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return employees;return employees.filter(e=>[e.full_name,e.employee_number,e.job_title,e.department].filter(Boolean).join(' ').toLowerCase().includes(q))},[employees,search])
 const loadKpis=async()=>{if(!jobId){setKpis([]);return}const r=await fetch('/api/kpi?job_description_id='+encodeURIComponent(jobId),{cache:'no-store'}),b=await r.json();if(r.ok){setKpis(b.kpis||[]);setScores({})}else setKpis([])}
 useEffect(()=>{loadKpis()},[jobId])
 const totalWeight=kpis.reduce((s,k)=>s+Number(k.weight||0),0),completed=kpis.filter(k=>scores[k.id]>0).length
 const preview=totalWeight?Math.round((kpis.reduce((s,k)=>s+(Number(scores[k.id]||0)/5)*Number(k.weight||0),0)/totalWeight)*100):0
 const save=async()=>{if(!employeeId||!jobId||!kpis.length){alert('اختر الموظف والوصف الوظيفي وتأكد من وجود مؤشرات KPI.');return}if(completed!==kpis.length){alert('يجب تقييم جميع مؤشرات الأداء قبل الحفظ.');return}setSaving(true);try{const r=await fetch('/api/kpi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({employee_id:employeeId,job_description_id:jobId,evaluator_name:evaluator,scores:kpis.map(k=>({kpi_id:k.id,score:Number(scores[k.id]||0)}))})}),b=await r.json();if(!r.ok)throw Error(b.error||'تعذر حفظ التقييم');setEvaluations(x=>[b.evaluation,...x]);setScores({});alert('تم حفظ تقييم KPI للموظف بنجاح')}catch(e){alert(e instanceof Error?e.message:'تعذر حفظ التقييم')}finally{setSaving(false)}}
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] text-[#24313b]">
  <header className="bg-[#09233f] text-white px-5 md:px-8 py-5 shadow-lg"><div className="max-w-[1500px] mx-auto flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="h-12 w-12 rounded-xl bg-[#b88618] grid place-items-center"><BarChart3 size={25}/></div><div><div className="text-xs text-[#d4a72c] font-black tracking-wider">HR • KPI</div><h1 className="text-2xl font-black">تقييم مؤشرات الأداء KPI</h1><p className="text-sm text-slate-300 mt-1">اختر الموظف، ثم قيّم مؤشرات وظيفته واحفظ النتيجة في سجل التقييمات.</p></div></div><button onClick={load} className="rounded-xl bg-white/10 border border-white/15 px-4 py-2 inline-flex items-center gap-2 font-bold"><RefreshCw size={17}/> تحديث</button></div></header>
  <div className="max-w-[1500px] mx-auto p-5 md:p-7 space-y-5">
   {error&&<div className="rounded-xl bg-red-50 text-red-700 border border-red-100 p-4">{error}</div>}
   <section className="grid lg:grid-cols-[360px_1fr] gap-5">
    <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm"><div className="flex items-center gap-2 mb-4 text-[#09233f] font-black"><UserRound size={19}/> اختيار الموظف</div><div className="relative mb-3"><Search size={17} className="absolute right-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث باسم الموظف أو الرقم أو المسمى" className="w-full border rounded-xl pr-9 pl-3 py-2.5"/></div><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="w-full border rounded-xl px-3 py-3 bg-white"><option value="">اختر الموظف المراد تقييمه</option>{filteredEmployees.map(e=><option key={e.id} value={e.id}>{e.full_name}{e.employee_number?' — '+e.employee_number:''}</option>)}</select>{employee&&<div className="mt-4 rounded-xl bg-[#f7f1e5] border border-[#eadbbf] p-4 text-sm leading-7"><b className="text-[#09233f] block text-base">{employee.full_name}</b><span>المسمى: {employee.job_title||'—'}</span><br/><span>الإدارة: {employee.department||'—'}</span></div>}<label className="block text-xs font-black mt-4">اسم المقيم<input value={evaluator} onChange={e=>setEvaluator(e.target.value)} placeholder="اسم المدير / المسؤول المقيم" className="mt-1 w-full border rounded-xl px-3 py-2.5"/></label><label className="block text-xs font-black mt-4">الوصف الوظيفي المستخدم في التقييم<select value={jobId} onChange={e=>setJobId(e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-2.5 bg-white"><option value="">اختر الوصف الوظيفي</option>{matchingJobs.map(j=><option key={j.id} value={j.id}>{j.name} — {j.department}</option>)}</select></label></div>
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div className="bg-[#fffaf0] border-b border-[#eadbbf] p-5 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="text-xs text-[#b88618] font-black">KPI EVALUATION</div><h2 className="text-xl font-black text-[#09233f] mt-1">مؤشرات الأداء للموظف المحدد</h2><p className="text-sm text-slate-500 mt-1">التقييم من 1 إلى 5 لكل مؤشر، والوزن يحسب النتيجة النهائية.</p></div><div className="flex gap-2"><div className="rounded-xl bg-white border px-4 py-2 text-center"><b className="block text-xl text-[#09233f]">{completed}/{kpis.length}</b><span className="text-[10px] text-slate-500">مؤشرات مكتملة</span></div><div className="rounded-xl bg-white border px-4 py-2 text-center"><b className="block text-xl text-[#b88618]">{preview}%</b><span className="text-[10px] text-slate-500">النتيجة الحالية</span></div></div></div>
     {!employeeId?<div className="p-14 text-center text-slate-500">اختر الموظف أولاً لبدء تقييم KPI.</div>:!jobId?<div className="p-14 text-center text-slate-500">اختر الوصف الوظيفي المرتبط بالموظف.</div>:!kpis.length?<div className="p-14 text-center text-slate-500">لا توجد مؤشرات KPI مسجلة لهذا الوصف الوظيفي. أضف المؤشرات من صفحة الوصف الوظيفي ثم عد إلى هنا.</div>:<div className="p-5 space-y-3">{kpis.map((k,i)=><div key={k.id} className="border rounded-xl p-4 bg-white"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex-1"><div className="flex gap-2 items-center flex-wrap"><span className="text-[11px] font-black bg-[#09233f] text-white rounded-full px-2.5 py-1">KPI {i+1}</span>{k.category&&<span className="text-[11px] font-bold bg-slate-100 rounded-full px-2.5 py-1">{k.category}</span>}<span className="text-[11px] font-bold text-[#b88618]">الوزن {k.weight}%</span></div><h3 className="font-black text-[#09233f] mt-2">{k.indicator_name}</h3><p className="text-sm text-slate-600 mt-1 leading-7">{k.question}</p></div><div className="shrink-0"><div className="text-[11px] font-black mb-2">التقييم</div><div className="flex gap-1">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setScores(s=>({...s,[k.id]:n}))} className={'h-10 w-10 rounded-lg border font-black '+(scores[k.id]===n?'bg-[#b88618] text-white border-[#b88618]':'bg-white hover:bg-[#fff7e7]')}>{n}</button>)}</div><div className="text-[10px] text-slate-400 mt-1 text-center">1 ضعيف • 5 ممتاز</div></div></div></div>)}<div className="flex flex-col sm:flex-row justify-between items-center gap-3 border-t pt-4"><span className="text-sm text-slate-600">النتيجة النهائية المتوقعة: <b className="text-[#09233f]">{preview}%</b></span><button disabled={saving||completed!==kpis.length} onClick={save} className="rounded-xl bg-[#09233f] text-white px-5 py-3 font-black inline-flex items-center gap-2 disabled:opacity-40"><ClipboardCheck size={18}/>{saving?'جاري الحفظ...':'حفظ تقييم الموظف'}</button></div></div>}
    </div>
   </section>
   <section className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-5 border-b flex items-center gap-2"><CheckCircle2 size={19} className="text-[#b88618]"/><h2 className="font-black text-[#09233f]">سجل تقييمات KPI السابقة</h2></div>{loading?<div className="p-8 text-center text-slate-500">جاري تحميل البيانات...</div>:evaluations.length===0?<div className="p-8 text-center text-slate-500">لا توجد تقييمات محفوظة حتى الآن.</div>:<div className="overflow-auto"><table className="w-full min-w-[900px]"><thead className="bg-[#09233f] text-white"><tr><th className="p-3 text-right">الموظف</th><th className="p-3 text-right">التقييم بواسطة</th><th className="p-3 text-right">التاريخ</th><th className="p-3 text-right">النتيجة</th><th className="p-3 text-right">المستوى</th></tr></thead><tbody>{evaluations.map(e=><tr key={e.id} className="border-b"><td className="p-3 font-bold">{employees.find(x=>x.id===e.employee_id)?.full_name||e.employee_id}</td><td className="p-3">{e.evaluator_name||'—'}</td><td className="p-3">{e.evaluation_date}</td><td className="p-3 font-black">{Number(e.total_score||0).toFixed(1)}%</td><td className="p-3">{e.performance_level||'—'}</td></tr>)}</tbody></table></div>}</section>
  </div>
 </main>
}
