'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Search, Users, Upload } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Employee = { id:string; employee_number:string|null; full_name:string; nationality:string|null; national_id:string|null; residency_status:string|null; job_title:string|null; department:string|null; basic_salary:number|null; housing_allowance:number|null; transportation_allowance:number|null; other_allowances:number|null; total_salary_with_allowances:number|null; employment_status:string|null; hire_date:string|null }

export default function EmployeesPage(){
 const [employees,setEmployees]=useState<Employee[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const {data}=await supabase.from('employee_records').select('id,employee_number,full_name,nationality,national_id,residency_status,job_title,department,basic_salary,housing_allowance,transportation_allowance,other_allowances,total_salary_with_allowances,employment_status,hire_date').order('created_at',{ascending:false}); setEmployees((data||[]) as Employee[]); setLoading(false)})()},[])
 const rows=useMemo(()=>employees.filter(e=>`${e.employee_number||''} ${e.full_name} ${e.job_title||''} ${e.department||''} ${e.national_id||''}`.toLowerCase().includes(search.toLowerCase())),[employees,search])
 return <main className="min-h-screen bg-[#f5f7fa]" dir="rtl"><div className="max-w-7xl mx-auto p-5 md:p-8">
  <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-7"><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-2xl bg-[#09233f] text-[#d4a72c] grid place-items-center"><Users size={28}/></div><div><div className="text-sm text-[#b88618] font-bold">قسم رئيسي</div><h1 className="text-3xl font-black text-[#09233f]">ملفات الموظفين</h1><p className="text-slate-500 mt-1">السجل الفعلي للموظفين مع الرواتب والبدلات.</p></div></div><div className="flex gap-2"><Link href="/employees/import" className="rounded-xl bg-[#09233f] text-white px-4 py-2 font-bold inline-flex gap-2 items-center"><Upload size={17}/> استيراد Excel</Link><Link href="/" className="flex items-center gap-2 text-[#09233f] font-bold"><ArrowLeft size={18}/> الرئيسية</Link></div></header>
  <section className="card overflow-hidden"><div className="p-4 border-b"><div className="relative"><Search className="absolute right-3 top-3 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="البحث بالاسم أو الرقم أو الوظيفة أو الإقامة" className="w-full border rounded-xl pr-10 pl-3 py-2.5"/></div></div>
  {loading?<div className="p-10 text-center text-slate-500">جاري التحميل...</div>:rows.length===0?<div className="p-10 text-center text-slate-500">لا توجد ملفات موظفين حتى الآن.</div>:<div className="overflow-auto"><table className="w-full min-w-[1500px]"><thead className="bg-[#09233f] text-white"><tr>{['الرقم الوظيفي','الاسم','الجنسية','رقم الإقامة','تاريخ التعيين','حالة العامل','الراتب الأساسي','بدل النقل','بدل السكن','البدلات الأخرى','الإجمالي'].map(h=><th key={h} className="p-3 text-right">{h}</th>)}</tr></thead><tbody>{rows.map(e=><tr key={e.id} className="border-b hover:bg-slate-50"><td className="p-3 font-bold">{e.employee_number||'—'}</td><td className="p-3"><Link href={`/employees/${e.id}`} className="font-bold text-[#09233f] hover:underline">{e.full_name}</Link></td><td className="p-3">{e.nationality||'—'}</td><td className="p-3">{e.national_id||'—'}</td><td className="p-3">{e.hire_date||'—'}</td><td className="p-3">{e.residency_status||e.employment_status||'—'}</td><td className="p-3">{e.basic_salary??'—'}</td><td className="p-3">{e.transportation_allowance??'—'}</td><td className="p-3">{e.housing_allowance??'—'}</td><td className="p-3">{e.other_allowances??'—'}</td><td className="p-3 font-bold">{e.total_salary_with_allowances??'—'}</td></tr>)}</tbody></table></div>}</section>
 </div></main>
}
