'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {Search,RefreshCw,Pencil,Trash2,FileText,X,Save} from 'lucide-react'
type C=any
export default function CandidatesPage(){
 const[rows,setRows]=useState<C[]>([]),[requests,setRequests]=useState<C[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[edit,setEdit]=useState<C|null>(null),[saving,setSaving]=useState(false)
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/candidates/manage',{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error||'تعذر تحميل المرشحين');setRows(b.candidates||[]);setRequests(b.requests||[])}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل المرشحين')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const req=(id:string)=>requests.find(r=>r.id===id)
 const remove=async(id:string)=>{if(!confirm('هل تريد حذف المرشح نهائياً؟'))return;const r=await fetch('/api/candidates/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',candidateId:id})});const b=await r.json();if(!r.ok){setError(b.error||'تعذر حذف المرشح');return}setRows(x=>x.filter(c=>c.id!==id))}
 const save=async()=>{if(!edit)return;setSaving(true);setError('');try{const r=await fetch('/api/candidates/manage',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidateId:edit.id,fullName:edit.full_name,phone:edit.phone,email:edit.email,specialization:edit.specialization})});const b=await r.json();if(!r.ok)throw new Error(b.error||'تعذر تعديل المرشح');setRows(x=>x.map(c=>c.id===edit.id?{...c,...b.candidate}:c));setEdit(null)}catch(e){setError(e instanceof Error?e.message:'تعذر تعديل المرشح')}finally{setSaving(false)}}
 const activeRows=rows.filter(c=>c.status!=='مرفوض'); const filtered=activeRows.filter(c=>String(c.full_name||'').toLowerCase().includes(q.trim().toLowerCase()))
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa]"><header className="bg-[#09233f] text-white px-6 py-5"><div className="max-w-7xl mx-auto flex justify-between items-center"><div><div className="text-[#d4a72c] font-bold">البنية الاساسية للمقاولات</div><h1 className="text-2xl font-black">المرشحون</h1><p className="text-slate-300 text-sm mt-1">جميع المرشحين المسجلين في النظام</p></div><button onClick={load} className="border border-white/20 rounded-xl p-3"><RefreshCw size={18}/></button></div></header>
 <div className="max-w-7xl mx-auto p-5 md:p-8">{error&&<div className="mb-5 bg-red-50 text-red-700 p-4 rounded-xl">{error}</div>}
 <div className="relative mb-6"><Search className="absolute right-4 top-3.5 text-slate-400" size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث باسم المرشح..." className="input pr-12 w-full"/></div>
 {loading?<div className="card p-12 text-center">جاري تحميل المرشحين...</div>:<div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-right"><thead className="bg-slate-50 border-b"><tr><th className="p-4">المرشح</th><th className="p-4">الوظيفة</th><th className="p-4">الجوال</th><th className="p-4">الحالة</th><th className="p-4">الإجراءات</th></tr></thead><tbody>{filtered.map(c=>{const r=req(c.request_id);const href=r?'/requests/'+r.id+'/candidates/'+c.id:'/candidate/'+c.share_token;return <tr key={c.id} className="border-b hover:bg-slate-50"><td className="p-4 font-black text-[#09233f]">{c.full_name||'—'}</td><td className="p-4">{r?.exact_type||'—'}</td><td className="p-4">{c.phone||'—'}</td><td className="p-4"><span className="px-3 py-1 rounded-full bg-slate-100 text-xs font-bold">{c.status||'جديد'}</span></td><td className="p-4"><div className="flex flex-wrap gap-2"><Link href={href} className="bg-[#09233f] text-white rounded-xl px-3 py-2 font-bold inline-flex items-center gap-1"><FileText size={15}/> فتح ملف المرشح</Link><button onClick={()=>setEdit({...c})} className="border border-[#b88618] text-[#8a6410] rounded-xl px-3 py-2 font-bold inline-flex items-center gap-1"><Pencil size={15}/> تعديل</button><button onClick={()=>remove(c.id)} className="border border-red-200 text-red-600 rounded-xl px-3 py-2 font-bold inline-flex items-center gap-1"><Trash2 size={15}/> حذف</button></div></td></tr>})}</tbody></table></div>{!filtered.length&&<div className="p-12 text-center text-slate-500">لا توجد نتائج مطابقة.</div>}</div>}
 <div className="mt-5 text-sm text-slate-500">إجمالي المرشحين: <b>{activeRows.length}</b> • نتائج البحث: <b>{filtered.length}</b></div>
 </div>
 {edit&&<div className="fixed inset-0 z-50 bg-black/40 grid place-items-center p-5"><div className="bg-white rounded-2xl w-full max-w-xl p-6 shadow-2xl"><div className="flex justify-between items-center mb-5"><h2 className="text-xl font-black text-[#09233f]">تعديل بيانات المرشح</h2><button onClick={()=>setEdit(null)}><X/></button></div><div className="grid md:grid-cols-2 gap-4"><label className="font-bold">الاسم<input className="input mt-2 w-full" value={edit.full_name||''} onChange={e=>setEdit({...edit,full_name:e.target.value})}/></label><label className="font-bold">الجوال<input className="input mt-2 w-full" value={edit.phone||''} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label><label className="font-bold">البريد<input className="input mt-2 w-full" value={edit.email||''} onChange={e=>setEdit({...edit,email:e.target.value})}/></label><label className="font-bold">التخصص<input className="input mt-2 w-full" value={edit.specialization||''} onChange={e=>setEdit({...edit,specialization:e.target.value})}/></label></div><div className="flex justify-end gap-2 mt-6"><button onClick={()=>setEdit(null)} className="border rounded-xl px-5 py-2 font-bold">إلغاء</button><button onClick={save} disabled={saving} className="bg-[#b88618] text-white rounded-xl px-5 py-2 font-bold inline-flex gap-2 items-center"><Save size={17}/>{saving?'جاري الحفظ...':'حفظ التعديل'}</button></div></div></div>}
 </main>
}