-- Nitaqat module schema and 2026 rules snapshot for HR2
create table if not exists public.nitaqat_company_settings (id boolean primary key default true check(id),company_name text,entity_number text,entity_name text,main_activity text,sub_activity text,active_statuses jsonb not null default '["خارج الكفالة فعال","على الكفالة"]'::jsonb,current_year integer not null default 2026,updated_by uuid,updated_at timestamptz not null default now());
create table if not exists public.nitaqat_rules (id uuid primary key default gen_random_uuid(),activity_group text not null,sub_activity text,m_value numeric not null,targets jsonb not null default '{}'::jsonb,effective_from date not null default '2026-01-01',effective_to date,source_title text not null,source_url text not null,decision_no text,active boolean not null default true,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(activity_group,sub_activity,effective_from));
create table if not exists public.nitaqat_special_cases (id uuid primary key default gen_random_uuid(),code text unique not null,name text not null,description text,rule_type text not null,parameters jsonb not null default '{}'::jsonb,effective_from date not null default '2026-01-01',effective_to date,source_title text,source_url text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.nitaqat_scenarios (id uuid primary key default gen_random_uuid(),name text not null,activity_group text,sub_activity text,base_saudi numeric not null default 0,base_non_saudi numeric not null default 0,simulated_saudi numeric not null default 0,simulated_non_saudi numeric not null default 0,result jsonb not null default '{}'::jsonb,created_by uuid,created_at timestamptz not null default now());
create table if not exists public.nitaqat_history (id uuid primary key default gen_random_uuid(),snapshot_date date not null default current_date,saudi_count numeric not null default 0,non_saudi_count numeric not null default 0,total_count numeric not null default 0,localization_rate numeric,activity_group text,sub_activity text,estimated_band text,official_band text,notes text,source text not null default 'بيانات HR2 + قواعد نطاقات المحفوظة بالنظام',created_by uuid,created_at timestamptz not null default now());
create table if not exists public.nitaqat_official_snapshots (id uuid primary key default gen_random_uuid(),official_band text not null,checked_at date not null default current_date,source text not null default 'قوى',notes text,created_by uuid,created_at timestamptz not null default now());
create table if not exists public.nitaqat_audit_log (id uuid primary key default gen_random_uuid(),action text not null,entity_type text not null,entity_id uuid,before_data jsonb,after_data jsonb,user_id uuid,created_at timestamptz not null default now());
create table if not exists public.nitaqat_permissions (id uuid primary key default gen_random_uuid(),role text not null,permission text not null,enabled boolean not null default true,unique(role,permission));
alter table public.nitaqat_company_settings enable row level security; alter table public.nitaqat_rules enable row level security; alter table public.nitaqat_special_cases enable row level security; alter table public.nitaqat_scenarios enable row level security; alter table public.nitaqat_history enable row level security; alter table public.nitaqat_official_snapshots enable row level security; alter table public.nitaqat_audit_log enable row level security; alter table public.nitaqat_permissions enable row level security;
insert into public.nitaqat_company_settings(id,company_name,current_year) values(true,'شركة البنية الأساسية للمقاولات',2026) on conflict(id) do nothing;
insert into public.nitaqat_special_cases(code,name,description,rule_type,parameters,source_title,source_url) values('small_establishment','منشأة 5 عمال فأقل','المنشأة التي لديها عدد العاملين 5 فأقل يتطلب إضافة عامل سعودي واحد فقط.','threshold','{"max_total_workers":5,"required_saudi":1}'::jsonb,'حاسبة نطاقات المطور - المرحلة الجديدة','https://es.hrsd.gov.sa/Services/Inquiry/NitaqatCalculatorMotawar2026.aspx') on conflict(code) do nothing;
insert into public.nitaqat_rules(activity_group,sub_activity,m_value,targets,effective_from,effective_to,source_title,source_url,decision_no) values

on conflict(activity_group,sub_activity,effective_from) do update set m_value=excluded.m_value,targets=excluded.targets,source_title=excluded.source_title,source_url=excluded.source_url,decision_no=excluded.decision_no,updated_at=now();