'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, RefreshCw, Search, UserCheck, MessageCircle, ExternalLink, FileText } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Candidate={id:string;request_id:string;full_name:string;phone:string|null;specialization:string|null;status:string|null}
type Request={id:string;exact_type:string;request_type:string}
type Approval={candidate_id:string;request_id:string;approval_status:string;final_approval_status:string;evaluation_status:string;evaluation_final_score:number;evaluation_hr_score:number;evaluation_specialized_score:number;evaluation_executive_score:number;gm_decision:string|null;gm_notes:string|null;gm_salary_override:string|null;salary:string|null;contract_type:string|null;offer_token:string|null;offer_status:string|null;offer_sent_at:string|null;start_date:string|null;notes:string|null}

function whatsappPhone(phone:string|null){if(!phone)return '';let p=phone.replace(/\D/g,'');if(p.startsWith('00'))p=p.slice(2);if(p.startsWith('05'))p=`966${p.slice(1)}`;else if(p.startsWith('5'))p=`966${p}`;return p}
const accepted=(a:Approval)=>a.gm_decision==='قبول'||a.gm_decision==='قبول بعرض مالي مختلف'

export default function HiringApprovalsPage(){
 const[candidates,setCandidates]=useState<Candidate[]>([]);const[requests,setRequests]=useState<Request[]>([]);const[approvals,setApprovals]=useState<Record<string,Approval>>({});const[selected,setSelected]=useState('');const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('')
 const load=async()=>{setLoading(true);const[{data:cs},{data:rs},{data:aps}]=await Promise.all([supabase.from('candidates').select('id,request_id,full_name,phone,specialization,status').order('created_at',{ascending:false}),supabase.from('requests').select('id,exact_type,request_type'),supabase.from('candidate_hiring_approvals').select('*').order('updated_at',{ascending:false})]);setCandidates((cs||[])as Candidate[]);setRequests((rs||[])as Request[]);const map:Record<string,Approval>={};(aps||[]).forEach((a:any)=>map[a.candidate_id]=a);setApprovals(map);if(!selected){const first=(aps||[])[0]?.candidate_id;if(first)setSelected(first)}setLoading(false)}
 useEffect(()=>{load()},[])
 const requestMap=useMemo(()=>Object.fromEntries(requests.map(r=>[r.id,r])),[requests]);const rows=useMemo(()=>candidates.filter(c=>approvals[c.id]&&`${c.full_name} ${c.phone||''} ${c.specialization||''}`.toLowerCase().includes(search.toLowerCase())),[candidates,approvals,search]);const candidate=candidates.find(c=>c.id===selected)||rows[0];const current=candidate?approvals[candidate.id]:null
 const sendOffer=async()=>{if(!candidate||!current||!accepted(current))return;setSaving(true);setMessage('');const payload={candidate_id:candidate.id,request_id:candidate.request_id,approval_status:'معتمد',final_approval_status:'معتمد',salary:current.gm_decision==='قبول بعرض مالي مختلف'?(current.gm_salary_override||current.salary):current.salary,contract_type:current.contract_type||'دوام كامل',start_date:current.start_date||null,notes:current.notes||''};const{data,error}=await supabase.from('candidate_hiring_approvals').upsert(payload,{onConflict:'candidate_id'}).select('*').single();if(error){setMessage(`تعذر تجهيز العرض: ${error.message}`);setSaving(false);return}const token=data.offer_token;if(!token){setMessage('تم الاعتماد لكن لم يتم إنشاء رابط العرض.');setSaving(false);return}const sentAt=new Date().toISOString();const{error:markError}=await supabase.from('candidate_hiring_approvals').update({offer_sent_at:sentAt,offer_status:'بانتظار الرد'}).eq('candidate_id',candidate.id);if(markError){setMessage(`تم إنشاء العرض لكن تعذر تسجيل إرساله: ${markError.message}`);setSaving(false);return}setApprovals(p=>({...p,[candidate.id]:{...current,...data,offer_sent_at:sentAt,offer_status:'بانتظار الرد'}}));const url=`${window.location.origin}/offer/${token}`;const phone=whatsappPhone(candidate.phone);const text=`السلام عليكم ${candidate.full_name}،\nتم اعتماد العرض الوظيفي الخاص بك لدى شركة البنية الاساسية للمقاولات.\nيمكنك الاطلاع على العرض والرد من خلال الرابط التالي:\n${url}`;window.open(phone?`https://wa.me/${phone}?text=${encodeURIComponent(text)}`:url,'_blank','noopener,noreferrer');setMessage(phone?'تم تجهيز العرض وفتح WhatsApp برسالة جاهزة.':'تم تجهيز العرض وفتح رابط العرض.');setSaving(false)}
 const statusText=(a:Approval)=>accepted(a)?'معتمد للتعيين':a.gm_decision==='رفض'?'مرفوض':a.evaluation_status==='مكتمل'?'بانتظار اعتماد المدير العام':'التقييم غير مكتمل'
 return <main className="min-h-screen bg-[#f5f7fa]" dir="rtl"><div className="max-w-7xl mx-auto p-5 md:p-8"><header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-7"><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-2xl bg-[#09233f] text-[#d4a72c] grid place-items-center"><UserCheck size={28}/></div><div><div className="text-sm text-[#b88618] font-bold">المرحلة التالية بعد التقييم</div><h1 className="text-3xl font-black text-[#09233f]">اعتماد التعيين</h1><p className="text-slate-500 mt-1">هذه الصفحة مرتبطة مباشرة بنتائج التقييم المرحلي واعتماد المدير العام ثم العرض الوظيفي.</p></div></div><Link href="/" className="flex items-center gap-2 text-[#09233f] font-bold"><ArrowLeft size={18}/> الرئيسية</Link></header>
 <div className="grid lg:grid-cols-[340px_1fr] gap-5"><section className="card overflow-hidden"><div className="p-4 border-b"><label className="relative block"><Search className="absolute right-3 top-3 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث عن مرشح" className="w-full border rounded-xl pr-10 pl-3 py-2.5"/></label></div>{loading?<div className="p-8 text-center">جاري التحميل...</div>:rows.length===0?<div className="p-8 text-center text-slate-500">لا توجد تقييمات مرتبطة باعتماد التعيين حتى الآن.</div>:<div className="max-h-[700px] overflow-auto">{rows.map(c=>{const a=approvals[c.id];return <button key={c.id} onClick={()=>setSelected(c.id)} className={`w-full text-right p-4 border-b ${c.id===candidate?.id?'bg-[#fff9e8]':'hover:bg-slate-50'}`}><div className="font-bold text-[#09233f]">{c.full_name}</div><div className="text-xs text-slate-500 mt-1">{requestMap[c.request_id]?.exact_type||'—'}</div><div className={`text-xs mt-2 font-bold ${accepted(a)?'text-green-700':a.gm_decision==='رفض'?'text-red-600':'text-amber-700'}`}>{statusText(a)}</div><div className="text-xs text-slate-500 mt-1">النتيجة: {Number(a.evaluation_final_score||0).toFixed(0)}%</div></button>})}</div>}</section>
 <section className="card p-6 md:p-8">{candidate&&current?<><div className="flex flex-col md:flex-row md:justify-between gap-4 border-b pb-5"><div><div className="text-[#b88618] font-bold">ملف اعتماد مرتبط بالتقييم</div><h2 className="text-2xl font-black text-[#09233f]">{candidate.full_name}</h2><p className="text-slate-500 mt-1">{requestMap[candidate.request_id]?.exact_type||'—'} {candidate.specialization?`• ${candidate.specialization}`:''}</p></div><div className="text-center"><div className="text-4xl font-black text-green-600">{Number(current.evaluation_final_score||0).toFixed(0)}%</div><div className="text-xs text-slate-500">النتيجة الموزونة</div><div className="mt-2 font-bold">{statusText(current)}</div></div></div>
 <div className="grid md:grid-cols-3 gap-4 mt-6"><div className="border rounded-xl p-4"><div className="font-bold">الموارد البشرية</div><div className="text-3xl font-black mt-2">{Number(current.evaluation_hr_score||0)}%</div></div><div className="border rounded-xl p-4"><div className="font-bold">الإدارة المختصة</div><div className="text-3xl font-black mt-2">{Number(current.evaluation_specialized_score||0)}%</div></div><div className="border rounded-xl p-4"><div className="font-bold">الإدارة التنفيذية</div><div className="text-3xl font-black mt-2">{Number(current.evaluation_executive_score||0)}%</div></div></div>
 <div className="mt-6 p-5 rounded-2xl bg-slate-50 border"><div className="font-black text-lg mb-3">حالة التقييم والاعتماد</div><div className="grid md:grid-cols-2 gap-3 text-sm"><div><b>حالة التقييم:</b> {current.evaluation_status||'—'}</div><div><b>قرار المدير العام:</b> {current.gm_decision||'لم يتم اتخاذ القرار'}</div><div className="md:col-span-2"><b>ملاحظات المدير العام:</b> {current.gm_notes||'—'}</div><div><b>التعديل المالي:</b> {current.gm_salary_override||'—'}</div></div></div>
 <div className="mt-6 flex flex-wrap gap-3">{accepted(current)&&<><Link href={`/forms/offer/${candidate.id}`} className="rounded-xl bg-[#b88618] text-white px-6 py-3 font-bold inline-flex items-center gap-2"><FileText size={18}/> استكمال العرض الوظيفي</Link><button disabled={saving} onClick={sendOffer} className="rounded-xl bg-[#25D366] text-white px-6 py-3 font-bold inline-flex items-center gap-2 disabled:opacity-40"><MessageCircle size={18}/> إرسال العرض عبر WhatsApp</button>{current.offer_token&&<Link href={`/offer/${current.offer_token}`} target="_blank" className="rounded-xl border px-5 py-3 font-bold inline-flex items-center gap-2"><ExternalLink size={17}/> فتح العرض</Link>}</>}{current.gm_decision==='رفض'&&<div className="rounded-xl bg-red-50 border border-red-200 text-red-700 px-5 py-3 font-bold">تم رفض المرشح من المدير العام، لذلك لا يتم تشغيل مسار العرض الوظيفي.</div>}{!accepted(current)&&current.gm_decision!=='رفض'&&<Link href="/interviews/links" className="rounded-xl border px-5 py-3 font-bold">روابط التقييم المرحلي</Link>}<button onClick={load} className="rounded-xl border px-5 py-3 font-bold inline-flex items-center gap-2"><RefreshCw size={17}/> تحديث</button></div>
 {current.offer_status&&<div className="mt-4 p-4 rounded-xl bg-[#fff9e8] border border-[#ead9a4]"><div className="font-bold">حالة العرض: {current.offer_status}</div>{current.offer_sent_at&&<div className="text-sm text-slate-500 mt-1">تم الإرسال: {new Date(current.offer_sent_at).toLocaleString('ar-SA')}</div>}</div>}{message&&<div className="mt-4 p-4 rounded-xl bg-slate-50">{message}</div>}</>:<div className="py-20 text-center text-slate-500">اختر مرشحًا لديه تقييم مرحلي.</div>}</section></div></div></main>
}