'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,RefreshCw,ExternalLink,Copy,CheckCircle2} from 'lucide-react'
type Row={id:string;employee_name:string|null;employee_number:string|null;department:string|null;job_title:string|null;status:string;updated_at:string;last_ip_address:string|null;last_device_name:string|null;submitted_via_link:boolean;employee_id?:string|null;company?:any;links?:any[]}
const stageLabels:Record<string,string>={employee:'الموظف',managers:'المدير المباشر / مدير المشروع / مدير المشاريع',it:'إدارة الحاسب الآلي',transport:'إدارة الحركة',warehouse:'إدارة المستودعات',admin:'إدارة الشؤون الإدارية',finance:'الإدارة المالية',hr:'إدارة الموارد البشرية',senior:'الإدارة العليا — الاعتماد النهائي'}
export default function Records(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Row|null>(null),[copied,setCopied]=useState('')
 const load=async()=>{setLoading(true);const r=await fetch('/api/forms/records?form_type=clearance',{cache:'no-store'});const d=await r.json().catch(()=>({}));setRows(d.records||[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 const copy=async(url:string)=>{await navigator.clipboard.writeText(url);setCopied(url);window.setTimeout(()=>setCopied(''),1800)}
 const links=(selected?.links||[]).filter((x:any)=>x.link_scope?.startsWith('clearance:'))
 return <main dir="rtl" className="forms-records-page"><div className="forms-records-shell">
  <header className="forms-records-header"><div><span className="hr-page-kicker">FORMS / CLEARANCE</span><h1>سجل إخلاء الطرف</h1><p>كل سجل مرتبط مباشرة بملف الموظف وروابط الإدارات المحفوظة.</p></div><div className="forms-records-actions"><Link href="/forms" className="btn-secondary"><ArrowLeft size={16}/> مركز النماذج</Link><button onClick={load} className="btn-primary"><RefreshCw size={16}/> تحديث</button></div></header>
  <section className="forms-records-table"><div className="forms-records-table-head">طلبات إخلاء الطرف</div>{loading?<div className="empty-state">جارٍ تحميل السجلات...</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr><th>الموظف</th><th>الرقم الوظيفي</th><th>الشركة</th><th>المسمى</th><th>القسم</th><th>الحالة</th><th>التاريخ</th><th>الإجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.employee_name||'—'}</b></td><td>{r.employee_number||'—'}</td><td>{r.company?.name||'—'}</td><td>{r.job_title||'—'}</td><td>{r.department||'—'}</td><td><span className="status-badge">{r.status}</span></td><td>{new Date(r.updated_at).toLocaleString('ar-SA')}</td><td><div className="record-actions"><button onClick={()=>setSelected(r)} className="record-action primary"><ExternalLink size={15}/> روابط الإدارات</button><Link href={'/forms/clearance/records/'+r.id} className="record-action secondary">فتح الملف</Link></div></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-state"><strong>لا توجد سجلات إخلاء طرف</strong><span>أنشئ إخلاء طرف من مسار الإخلاء لبدء المتابعة.</span></div>}</div>}</section>
  {selected&&<section className="forms-link-panel"><header><div><span className="hr-page-kicker">PERSISTED DEPARTMENT LINKS</span><h2>{selected.employee_name||'—'}</h2><p>{selected.employee_number||'—'} · {selected.job_title||'المسمى غير محدد'} · {selected.department||'الإدارة غير محددة'}</p></div><button onClick={()=>setSelected(null)} className="btn-secondary">إغلاق</button></header><div className="forms-link-list">{links.map((x:any)=><div key={x.id} className="forms-link-row"><div><b>{stageLabels[String(x.link_scope).replace('clearance:','')]||x.link_scope}</b><small>{x.last_submitted_at?'تم الإرسال':'قيد الانتظار'}</small></div><div className="forms-link-actions"><a href={x.public_url} target="_blank" rel="noreferrer" title="فتح الرابط" className="icon-action"><ExternalLink size={16}/></a><button onClick={()=>copy(x.public_url)} title="نسخ الرابط" className="icon-action">{copied===x.public_url?<CheckCircle2 size={16}/>:<Copy size={16}/>}</button></div></div>)}</div>{!links.length&&<div className="empty-state">لا توجد روابط محفوظة لهذا السجل.</div>}</section>}
  {copied&&<div className="form-copy-toast">تم نسخ الرابط بنجاح</div>}
 </div></main>
}