'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,RefreshCw} from 'lucide-react'
type Row={id:string;employee_name:string|null;employee_number:string|null;department:string|null;status:string;updated_at:string;last_ip_address:string|null;last_device_name:string|null;submitted_via_link:boolean}
export default function Records(){const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);const r=await fetch('/api/forms/records?form_type=clearance',{cache:'no-store'});const d=await r.json().catch(()=>({}));setRows(d.records||[]);setLoading(false)};useEffect(()=>{void load()},[])
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-6xl mx-auto"><header className="flex justify-between items-center mb-6"><div><div className="text-[#b88618] font-bold">مركز النماذج / طلبات إخلاء الطرف</div><h1 className="text-3xl font-black text-[#09233f]">طلبات إخلاء الطرف</h1><p className="text-slate-500 mt-1">جميع النماذج المرسلة وحالات الوصول وبيانات الجهاز وIP.</p></div><div className="flex gap-2"><Link href="/forms" className="border bg-white rounded-xl px-4 py-2 font-bold inline-flex gap-2 items-center"><ArrowLeft size={16}/> مركز النماذج</Link><button onClick={load} className="bg-[#09233f] text-white rounded-xl px-4 py-2 font-bold inline-flex gap-2"><RefreshCw size={16}/> تحديث</button></div></header>
 <section className="bg-[#09233f] text-white rounded-2xl p-5 mb-6"><h2 className="font-black text-lg">مسار إخلاء الطرف</h2><p className="text-slate-300 text-sm mt-1">إنشاء وإدارة الروابط التسعة الخاصة بكل موظف.</p><Link href="/forms/clearance" className="mt-4 inline-flex bg-[#b88618] rounded-lg px-4 py-2 font-bold">فتح مسار إخلاء الطرف</Link></section>
 <section className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 border-b font-black">سجل طلبات إخلاء الطرف</div>{loading?<div className="p-10 text-center">جارٍ التحميل...</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-100"><tr><th className="p-3 text-right">الموظف</th><th className="p-3 text-right">القسم</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">الجهاز</th><th className="p-3 text-right">IP</th><th className="p-3 text-right">التاريخ</th><th className="p-3 text-right">الإجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-bold">{r.employee_name||'—'}<div className="text-xs text-slate-500">{r.employee_number||''}</div></td><td className="p-3">{r.department||'—'}</td><td className="p-3">{r.status}</td><td className="p-3">{r.submitted_via_link?r.last_device_name||'غير معروف':'داخلي'}</td><td className="p-3 font-mono text-xs">{r.submitted_via_link?r.last_ip_address||'—':'—'}</td><td className="p-3">{new Date(r.updated_at).toLocaleString('ar-SA')}</td><td className="p-3"><Link href={`/forms/clearance/records/${r.id}`} className="bg-[#09233f] text-white rounded-lg px-3 py-1.5 font-bold">فتح ملف الإخلاء</Link></td></tr>)}</tbody></table>{!rows.length&&<div className="p-8 text-center text-slate-500">لا توجد نماذج مسجلة.</div>}</div>}</section></div></main>}
