'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {ArrowRight,ClipboardCheck,UserRound,Briefcase,CalendarDays,ExternalLink,CheckCircle2,FileText,Pencil,Trash2,ArrowLeftRight} from 'lucide-react'
import {useParams,useRouter} from 'next/navigation'
import {supabase} from '@/lib/supabase'

type Requirement={id:string;name:string;category:string;weight:number;required:boolean}
type Score={requirement_id:string;score:number;evidence:string}
type JobRequest={id:string;exact_type:string|null;request_type:string|null;status:string|null}

export default function CandidatePage(){
 const{id,candidateId}=useParams<{id:string;candidateId:string}>();const router=useRouter();const[candidate,setCandidate]=useState<any>(null),[request,setRequest]=useState<any>(null),[requirements,setRequirements]=useState<Requirement[]>([]),[scores,setScores]=useState<Score[]>([]),[requests,setRequests]=useState<JobRequest[]>([]),[target,setTarget]=useState(id),[loading,setLoading]=useState(true),[moving,setMoving]=useState(false),[deleting,setDeleting]=useState(false)
 useEffect(()=>{(async()=>{const[{data:c},{data:r},{data:req},{data:ss},{data:rs}]=await Promise.all([supabase.from('candidates').select('*').eq('id',candidateId).eq('request_id',id).single(),supabase.from('requests').select('*').eq('id',id).single(),supabase.from('request_requirements').select('*').eq('request_id',id).order('sort_order'),supabase.from('candidate_requirement_scores').select('*').eq('candidate_id',candidateId),supabase.from('requests').select('id,exact_type,request_type,status').order('created_at',{ascending:false})]);setCandidate(c);setRequest(r);setRequirements(req||[]);setScores(ss||[]);setRequests(rs||[]);setTarget(c?.request_id||id);setLoading(false)})()},[id,candidateId])
 const scoreMap=useMemo(()=>new Map(scores.map(s=>[s.requirement_id,s])),[scores]);const totalWeight=requirements.reduce((s,r)=>s+Number(r.weight||0),0);const overall=totalWeight?Math.round(requirements.reduce((s,r)=>s+Number(r.weight||0)*Number(scoreMap.get(r.id)?.score||0)/100,0)/totalWeight*100):0;const required=requirements.filter(r=>r.required);const requiredMatch=required.length?Math.round(required.filter(r=>Number(scoreMap.get(r.id)?.score||0)>=50).length/required.length*100):100
 const moveCandidate=async()=>{if(!candidate||!target||target===candidate.request_id)return;if(!confirm(`سيتم تغيير الوظيفة للمرشح «${candidate.full_name}» فقط إلى «${requests.find(r=>r.id===target)?.exact_type||'الطلب المحدد'}». لن يتأثر أي مرشح آخر. هل تريد المتابعة؟`))return;setMoving(true);try{const res=await fetch('/api/candidates/transfer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidateId,targetRequestId:target})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.ok){alert(data.error||'تعذر تغيير وظيفة المرشح.');setMoving(false);return}router.replace(`/requests/${target}/candidates/${candidateId}`);router.refresh()}catch{alert('تعذر الاتصال بالخادم أثناء نقل المرشح.');setMoving(false)}}
 const removeCandidate=async()=>{if(!confirm(`هل أنت متأكد من حذف المرشح «${candidate?.full_name||''}» فقط؟ لن يتم حذف الطلب أو أي مرشح آخر.`))return;setDeleting(true);const{error}=await supabase.from('candidates').delete().eq('id',candidateId);if(error){alert(`تعذر حذف المرشح: ${error.message}`);setDeleting(false);return}router.push(`/requests/${id}`);router.refresh()}
 if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#f5f7fa]">جاري تحميل بيانات المرشح...</main>
 if(!candidate)return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#f5f7fa]"><div className="bg-white border-2 border-red-200 rounded-2xl p-8 text-red-700 font-bold">المرشح غير موجود.</div></main>
 const previousRequest=requests.find(r=>r.id===candidate.previous_request_id)
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-6xl mx-auto"><div className="flex flex-wrap items-center justify-between gap-3 mb-5"><Link href={`/requests/${id}`} className="border-2 border-slate-200 bg-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><ArrowRight size={17}/> العودة للطلب</Link><div className="flex flex-wrap gap-2"><Link href={`/requests/${id}/candidates/${candidateId}/edit`} className="border-2 border-[#b88618] text-[#7b590d] bg-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><Pencil size={17}/> تعديل المرشح</Link><button onClick={removeCandidate} disabled={deleting} className="bg-red-600 text-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><Trash2 size={17}/>{deleting?'جاري الحذف...':'حذف المرشح'}</button><Link href="/interviews/links" className="bg-[#09233f] text-white border-2 border-[#09233f] rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><CalendarDays size={17}/> جدولة Teams والتقييم</Link><Link href={`/reports/candidate/${candidateId}`} className="border-2 border-slate-200 bg-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><FileText size={17}/> تقرير المرشح</Link></div></div>
 <header className="bg-[#09233f] text-white rounded-2xl p-6 md:p-8 shadow-lg"><div className="text-[#d4a72c] font-bold">تفاصيل المرشح</div><h1 className="text-3xl font-black mt-2">{candidate.full_name}</h1><div className="grid md:grid-cols-4 gap-3 mt-5"><div className="border-2 border-white/20 rounded-xl p-3"><UserRound size={17} className="inline ml-2"/><b>الجوال:</b> {candidate.phone||'—'}</div><div className="border-2 border-white/20 rounded-xl p-3"><b>البريد:</b> {candidate.email||'—'}</div><div className="border-2 border-white/20 rounded-xl p-3"><Briefcase size={17} className="inline ml-2"/><b>الوظيفة الحالية:</b> {request?.exact_type||'—'}</div><div className="border-2 border-white/20 rounded-xl p-3"><b>الحالة:</b> {candidate.status||'جديد'}</div></div></header>
 <section className="bg-white border-2 border-[#b88618] rounded-2xl p-5 mt-5"><div className="flex items-center gap-2"><ArrowLeftRight className="text-[#b88618]" size={20}/><div><h2 className="text-lg font-black text-[#09233f]">تغيير الوظيفة لهذا المرشح</h2><p className="text-xs text-slate-500 mt-1">التغيير يطبق على <b>هذا المرشح فقط</b> ويحفظ آخر طلب وظيفي سابق.</p></div></div>{previousRequest&&<div className="mt-3 rounded-xl bg-slate-50 border border-slate-200 p-3 text-sm"><b>آخر وظيفة سابقة:</b> {previousRequest.exact_type||previousRequest.request_type||'—'}{candidate.moved_at?` — تم النقل بتاريخ ${new Date(candidate.moved_at).toLocaleString('ar-SA')}`:''}</div>}<div className="flex flex-col md:flex-row gap-3 mt-4"><select value={target} onChange={e=>setTarget(e.target.value)} className="flex-1 border-2 border-slate-200 rounded-xl p-3 bg-white"><option value={id}>{request?.exact_type||'الوظيفة الحالية'}</option>{requests.filter(r=>r.id!==id).map(r=><option key={r.id} value={r.id}>{r.exact_type||r.request_type||'طلب وظيفي'}{r.status?` — ${r.status}`:''}</option>)}</select><button onClick={moveCandidate} disabled={moving||target===candidate.request_id} className="bg-[#09233f] text-white rounded-xl px-6 py-3 font-bold inline-flex items-center justify-center gap-2"><ArrowLeftRight size={17}/>{moving?'جاري النقل...':'تغيير وظيفة المرشح فقط'}</button></div></section>
 <section className="grid md:grid-cols-3 gap-4 mt-5"><div className="bg-white border-2 border-slate-200 rounded-2xl p-5"><div className="text-sm text-slate-500">المطابقة العامة</div><div className="text-4xl font-black text-[#09233f] mt-1">{overall}%</div></div><div className="bg-white border-2 border-slate-200 rounded-2xl p-5"><div className="text-sm text-slate-500">مطابقة المتطلبات الأساسية</div><div className="text-4xl font-black text-[#09233f] mt-1">{requiredMatch}%</div></div><div className="bg-white border-2 border-slate-200 rounded-2xl p-5"><div className="text-sm text-slate-500">الخبرة</div><div className="text-2xl font-black text-[#09233f] mt-2">{candidate.total_experience_years??'—'} سنة</div><div className="text-xs text-slate-500">السعودية: {candidate.saudi_experience_years??'—'} سنة</div></div></section>
 <section className="bg-white border-2 border-slate-200 rounded-2xl p-6 mt-5"><div className="flex items-center gap-2 mb-5"><ClipboardCheck className="text-[#b88618]"/><h2 className="text-xl font-black text-[#09233f]">متطلبات الوظيفة كاملة</h2></div>{requirements.length?<div className="space-y-3">{requirements.map(r=>{const s=Number(scoreMap.get(r.id)?.score||0);return <div key={r.id} className={`border-2 rounded-2xl p-4 ${r.required?'border-[#d4a72c] bg-amber-50/30':'border-slate-200 bg-white'}`}><div className="flex flex-wrap justify-between gap-3"><div><b className="text-[#09233f]">{r.name}</b><div className="text-xs text-slate-500 mt-1">{r.category||'عام'} • {r.required?'متطلب أساسي':'متطلب إضافي'}</div></div><div className="text-left"><div className="font-black text-[#b88618]">الوزن {Number(r.weight)}%</div><div className="text-sm font-bold mt-1">المطابقة {s}%</div></div></div><div className="h-2 bg-slate-100 rounded-full mt-3 overflow-hidden"><div className="h-full bg-[#b88618]" style={{width:`${Math.max(0,Math.min(100,s))}%`}}/></div>{scoreMap.get(r.id)?.evidence&&<div className="text-xs text-slate-500 mt-2">الدليل: {scoreMap.get(r.id)?.evidence}</div>}</div>})}</div>:<div className="border-2 border-amber-200 bg-amber-50 rounded-xl p-5 font-bold">لا توجد متطلبات مسجلة لهذا الطلب.</div>}</section>
 <section className="bg-white border-2 border-slate-200 rounded-2xl p-6 mt-5"><h2 className="text-xl font-black text-[#09233f] mb-4">التقييم المرحلي</h2><p className="text-slate-500 mb-5">يتم التقييم من خلال روابط مستقلة لكل مرحلة، وبنفس تصميم صفحة تقييم الطلب.</p><div className="grid md:grid-cols-4 gap-3">{[['hr','الموارد البشرية'],['specialized','الإدارة المختصة'],['executive','الإدارة التنفيذية'],['general_manager','المدير العام']].map(x=><div key={x[0]} className="border-2 border-slate-200 rounded-2xl p-4"><div className="font-black text-[#09233f]">{x[1]}</div><Link href="/interviews/links" className="mt-3 w-full border-2 border-[#b88618] text-[#7b590d] rounded-xl py-2 text-center font-bold inline-flex items-center justify-center gap-2"><ExternalLink size={15}/> فتح إدارة الروابط</Link></div>)}</div></section>
 <section className="bg-white border-2 border-slate-200 rounded-2xl p-6 mt-5"><h2 className="text-xl font-black text-[#09233f] mb-4">الخطوة التالية</h2><div className="flex flex-wrap gap-3"><Link href="/interviews/links" className="bg-[#b88618] text-white border-2 border-[#b88618] rounded-xl px-5 py-3 font-bold inline-flex items-center gap-2"><CalendarDays size={17}/> تحديد موعد Microsoft Teams</Link><Link href={`/reports/candidate/${candidateId}`} className="border-2 border-slate-200 rounded-xl px-5 py-3 font-bold inline-flex items-center gap-2"><FileText size={17}/> فتح التقرير التفصيلي</Link><CheckCircle2 size={22} className="text-green-600 self-center"/></div></section></div></main>}
