'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {ArrowRight,ClipboardCheck,UserRound,Briefcase,CalendarDays,ExternalLink,CheckCircle2,FileText,Pencil,ClipboardList,Trash2,ArrowLeftRight} from 'lucide-react'
import {useParams,useRouter} from 'next/navigation'

type Requirement={id:string;name:string;category:string;weight:number;required:boolean}
type Score={requirement_id:string;score:number;evidence:string}
type JobRequest={id:string;exact_type:string|null;request_type:string|null;status:string|null}
export default function CandidatePage(){
 const{id,candidateId}=useParams<{id:string;candidateId:string}>();const router=useRouter();const[candidate,setCandidate]=useState<any>(null),[request,setRequest]=useState<any>(null),[requirements,setRequirements]=useState<Requirement[]>([]),[scores,setScores]=useState<Score[]>([]),[requests,setRequests]=useState<JobRequest[]>([]),[target,setTarget]=useState(id),[loading,setLoading]=useState(true),[error,setError]=useState(''),[moving,setMoving]=useState(false),[deleting,setDeleting]=useState(false),[readOnly,setReadOnly]=useState(false)
 useEffect(()=>{(async()=>{try{const r=await fetch(`/api/candidates/${candidateId}/data?requestId=${id}`,{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'تعذر تحميل بيانات المرشح');setCandidate(b.candidate);setRequest(b.request);setRequirements(b.requirements||[]);setScores(b.scores||[]);setRequests(b.requests||[]);setTarget(b.candidate?.request_id||id);setReadOnly(b.role==='interview_viewer')}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل بيانات المرشح')}finally{setLoading(false)}})()},[id,candidateId])
 const scoreMap=useMemo(()=>new Map(scores.map(s=>[s.requirement_id,s])),[scores]);const totalWeight=requirements.reduce((s,r)=>s+Number(r.weight||0),0);const overall=totalWeight?Math.round(requirements.reduce((s,r)=>s+Number(r.weight||0)*Number(scoreMap.get(r.id)?.score||0)/100,0)/totalWeight*100):0;const required=requirements.filter(r=>r.required);const requiredMatch=required.length?Math.round(required.filter(r=>Number(scoreMap.get(r.id)?.score||0)>=50).length/required.length*100):100
 const moveCandidate=async()=>{if(readOnly||!candidate||!target||target===candidate.request_id)return;if(!confirm(`سيتم تغيير الوظيفة للمرشح «${candidate.full_name}» فقط. هل تريد المتابعة؟`))return;setMoving(true);try{const res=await fetch('/api/candidates/transfer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidateId,targetRequestId:target})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.ok)throw new Error(data.error||'تعذر تغيير وظيفة المرشح');router.replace(`/requests/${target}/candidates/${candidateId}`)}catch(e){setError(e instanceof Error?e.message:'تعذر نقل المرشح')}finally{setMoving(false)}}
 const removeCandidate=async()=>{if(readOnly||!confirm(`هل أنت متأكد من حذف المرشح «${candidate?.full_name||''}» فقط؟`))return;setDeleting(true);try{const r=await fetch('/api/candidates/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',candidateId})});const b=await r.json();if(!r.ok)throw new Error(b.error||'تعذر حذف المرشح');router.push(`/requests/${id}`)}catch(e){setError(e instanceof Error?e.message:'تعذر حذف المرشح')}finally{setDeleting(false)}}
 if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#f5f7fa]">جاري تحميل بيانات المرشح...</main>
 if(error&&!candidate)return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#f5f7fa] p-6"><div className="bg-white border-2 border-red-200 rounded-2xl p-8 text-red-700 font-bold">{error}</div></main>
 const previousRequest=requests.find(r=>r.id===candidate.previous_request_id)
 return <main dir="rtl" className="min-h-screen bg-[#f5f7fa] p-5 md:p-8"><div className="max-w-6xl mx-auto">{error&&<div className="mb-4 bg-red-50 text-red-700 p-4 rounded-xl">{error}</div>}{readOnly&&<div className="mb-4 bg-blue-50 border border-blue-200 text-blue-800 p-4 rounded-xl font-bold">وضع الاطلاع فقط: بيانات المرشح والتقييمات للعرض فقط.</div>}<div className="flex flex-wrap items-center justify-between gap-3 mb-5"><Link href={`/requests/${id}`} className="border-2 border-slate-200 bg-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><ArrowRight size={17}/> العودة للطلب</Link><div className="flex flex-wrap gap-2">{!readOnly&&<Link href={`/requests/${id}/candidates/${candidateId}/edit`} className="border-2 border-[#b88618] text-[#7b590d] bg-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><Pencil size={17}/> تعديل المرشح</Link>}{!readOnly&&<button onClick={removeCandidate} disabled={deleting} className="bg-red-600 text-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><Trash2 size={17}/>{deleting?'جاري الحذف...':'حذف المرشح'}</button>}<Link href="#initial-evaluation" className="bg-[#b88618] text-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><ClipboardList size={17}/> التقييم المبدئي</Link><Link href={`/interviews/links?candidateId=${candidateId}`} className="bg-[#09233f] text-white rounded-xl px-4 py-2 font-bold inline-flex items-center gap-2"><CalendarDays size={17}/> التقييم والمقابلات</Link></div></div>
 <header className="bg-[#09233f] text-white rounded-2xl p-6 md:p-8 shadow-lg"><div className="text-[#d4a72c] font-bold">تفاصيل المرشح</div><h1 className="text-3xl font-black mt-2">{candidate.full_name}</h1><div className="grid md:grid-cols-4 gap-3 mt-5"><div className="border-2 border-white/20 rounded-xl p-3"><UserRound size={17} className="inline ml-2"/><b>الجوال:</b> {candidate.phone||'—'}</div><div className="border-2 border-white/20 rounded-xl p-3"><b>البريد:</b> {candidate.email||'—'}</div><div className="border-2 border-white/20 rounded-xl p-3"><Briefcase size={17} className="inline ml-2"/><b>الوظيفة:</b> {request?.exact_type||'—'}</div><div className="border-2 border-white/20 rounded-xl p-3"><b>الحالة:</b> {candidate.status||'جديد'}</div></div></header>
 <section className="bg-white border-2 border-[#b88618] rounded-2xl p-5 mt-5"><div className="flex items-center gap-2"><ArrowLeftRight className="text-[#b88618]" size={20}/><div><h2 className="text-lg font-black text-[#09233f]">تغيير الوظيفة لهذا المرشح</h2><p className="text-xs text-slate-500 mt-1">التغيير يطبق على هذا المرشح فقط.</p></div></div>{previousRequest&&<div className="mt-3 rounded-xl bg-slate-50 border border-slate-200 p-3 text-sm"><b>آخر وظيفة سابقة:</b> {previousRequest.exact_type||previousRequest.request_type||'—'}</div>}{!readOnly&&<div className="flex flex-col md:flex-row gap-3 mt-4"><select value={target} onChange={e=>setTarget(e.target.value)} className="flex-1 border-2 border-slate-200 rounded-xl p-3 bg-white"><option value={id}>{request?.exact_type||'الوظيفة الحالية'}</option>{requests.filter(r=>r.id!==id).map(r=><option key={r.id} value={r.id}>{r.exact_type||r.request_type||'طلب وظيفي'}{r.status?` — ${r.status}`:''}</option>)}</select><button onClick={moveCandidate} disabled={moving||target===candidate.request_id} className="bg-[#09233f] text-white rounded-xl px-6 py-3 font-bold inline-flex items-center justify-center gap-2"><ArrowLeftRight size={17}/>{moving?'جاري النقل...':'تغيير الوظيفة'}</button></div>}</section>
 <section className="grid md:grid-cols-3 gap-4 mt-5"><div className="bg-white border-2 border-slate-200 rounded-2xl p-5"><div className="text-sm text-slate-500">المطابقة العامة</div><div className="text-4xl font-black text-[#09233f] mt-1">{overall}%</div></div><div className="bg-white border-2 border-slate-200 rounded-2xl p-5"><div className="text-sm text-slate-500">مطابقة المتطلبات الأساسية</div><div className="text-4xl font-black text-[#09233f] mt-1">{requiredMatch}%</div></div><div className="bg-white border-2 border-slate-200 rounded-2xl p-5"><div className="text-sm text-slate-500">الخبرة</div><div className="text-2xl font-black text-[#09233f] mt-2">{candidate.total_experience_years??'—'} سنة</div><div className="text-xs text-slate-500">السعودية: {candidate.saudi_experience_years??'—'} سنة</div></div></section>
 <section id="initial-evaluation" className="bg-white border-2 border-slate-200 rounded-2xl p-6 mt-5"><div className="flex items-center gap-2 mb-5"><ClipboardCheck className="text-[#b88618]"/><h2 className="text-xl font-black text-[#09233f]">متطلبات الوظيفة كاملة</h2></div>{requirements.length?<div className="space-y-3">{requirements.map(r=>{const s=Number(scoreMap.get(r.id)?.score||0);return <div key={r.id} className={`border-2 rounded-2xl p-4 ${r.required?'border-[#d4a72c] bg-amber-50/30':'border-slate-200 bg-white'}`}><div className="flex flex-wrap justify-between gap-3"><div><b className="text-[#09233f]">{r.name}</b><div className="text-xs text-slate-500 mt-1">{r.category||'عام'} • {r.required?'متطلب أساسي':'متطلب إضافي'}</div></div><div className="text-left"><div className="font-black text-[#b88618]">الوزن {Number(r.weight)}%</div><div className="text-sm font-bold mt-1">المطابقة {s}%</div></div></div><div className="h-2 bg-slate-100 rounded-full mt-3 overflow-hidden"><div className="h-full bg-[#b88618]" style={{width:`${Math.max(0,Math.min(100,s))}%`}}/></div>{scoreMap.get(r.id)?.evidence&&<div className="text-xs text-slate-500 mt-2">الدليل: {scoreMap.get(r.id)?.evidence}</div>}</div>})}</div>:<div className="border-2 border-amber-200 bg-amber-50 rounded-xl p-5 font-bold">لا توجد متطلبات مسجلة لهذا الطلب.</div>}</section>
 <section className="bg-white border-2 border-slate-200 rounded-2xl p-6 mt-5"><h2 className="text-xl font-black text-[#09233f] mb-4">التقييم المرحلي</h2><div className="grid md:grid-cols-4 gap-3">{[['hr','الموارد البشرية'],['specialized','الإدارة المختصة'],['executive','الإدارة التنفيذية'],['general_manager','المدير العام']].map(x=><div key={x[0]} className="border-2 border-slate-200 rounded-2xl p-4"><div className="font-black text-[#09233f]">{x[1]}</div><Link href={`/interviews/links?candidateId=${candidateId}`} className="mt-3 w-full border-2 border-[#b88618] text-[#7b590d] rounded-xl py-2 text-center font-bold inline-flex items-center justify-center gap-2"><ExternalLink size={15}/> فتح إدارة الروابط</Link></div>)}</div></section><section className="bg-white border-2 border-slate-200 rounded-2xl p-6 mt-5"><div className="flex flex-wrap gap-3"><Link href="#initial-evaluation" className="bg-[#b88618] text-white rounded-xl px-5 py-3 font-bold inline-flex items-center gap-2"><ClipboardList size={17}/> التقييم المبدئي</Link><Link href={`/interviews/links?candidateId=${candidateId}`} className="border-2 border-slate-200 rounded-xl px-5 py-3 font-bold inline-flex items-center gap-2"><CalendarDays size={17}/> تحديد موعد Teams</Link><Link href={`/reports/candidate/${candidateId}`} className="border-2 border-slate-200 rounded-xl px-5 py-3 font-bold inline-flex items-center gap-2"><FileText size={17}/> التقرير الشامل</Link><CheckCircle2 size={22} className="text-green-600 self-center"/></div></section></div></main>}
